6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        32         28         45         64         50         48         24         30         58          8
         1         17         35         42         51         59         31         47         40         53
         2         43         62         54         10         11         63         52         39         25
        18         22         61         23          4         15         60         56         37         16
         6          3         27         29         36         21         33         41         14         44
         9         38         57         46         34         13          7          5         12         20
        49         55         26         19