6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        57          3         59         15         27         54         41         29         43         62
        63         64         49         17          9         37          6         52         60         39
         5         31         55         48         40         44         35         46         28         47
        51         33         18         16         13         42         36          4          7         24
        22         12         19         50         26         30         25         32         56         34
        53         23         45         10         11         61          1         21          8         14
        38         58         20          2