6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        12         39         18         50          3         53          8         20          7         57
        64         43          5         45         58         51         14         44          1         62
        26         36         38         19         28          4         27         55          9         16
        46         13          2         48         31         42         11         60         59         23
        33         25         29         40         22         34         47         37         32         61
        49         15         30         56         17         21          6         54         52         35
        24         41         10         63