6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        45         55         15         60         14         39         41          7         31         50
        23         33         58          4         52         47         48          9         34         19
        43          2         44         27         10         61          6         49         28         29
        57         37         12          8         16         20         46         25         62          5
        59         24          3         22         17         21         30         18         51          1
        53         35         40         38         56         54         11         13         64         32
        63         42         36         26