6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         2         37         20          1         35         21          5         33         61         14
        40         50         36         25         39         54         27         44         15         48
        52          7          6         22         58         49         10         11         51         60
        23         34         53         55         41         30         38         12         42         57
        17          9         26          3         59         18         62         28         43         13
        46         56         32          4          8         63         29         31         16         64
        24         45         47         19