6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         6         20         52         35         49         47         36         59         54         57
        18         38         28         60         42         41         16         22         13         29
        17         27         51          5         64         55         63         24         62         31
         3         12          7         58         15         37         50          4         32         33
         2         14         30         11         23         56         44         43         40          8
        45         25         19         46          1         26         61          9         39         10
        34         21         48         53