6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        63         30         35         23         32         11          9         37         49         42
        45         61         34          3          7         21         47         12         39         24
        17         44         51         54         29         16          8         22         60          6
        64         36         56         18         48         20         59         55         28         46
         5         43          4         26         15         25         62          1         38         27
        10         14         19         52         50         57         31         40         33         58
        41          2         13         53