6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        32          5          4          9         21         28         26         25         29         54
        12         16         56         20         15         61         23         31         58         19
        51         35          8         30         63         60         59         55         39         33
        27         37         44         17         52          2         43          1         42         24
        18         36         53         14          7         48         50         34          6         57
        40         49         64         47         38         41         10         11         45         62
         3         13         46         22