6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        35         10         51          8         36         20         23         56         11         58
        64         38         27         25         29         52          3         32         13         21
         2         40          4         16         50         43         37         24         54         46
        44         63         14         18         60          6         59         53         41         28
        22         55         45          9          5         47         12         62         31         34
        39         30          7         49         57         19         61         48         42         17
         1         26         33         15