6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        22         55          2         35         11         12         21         64          4         56
         7         24         29         45         30         38          8         15         52         57
        51         61         34         54         13         26         47         10         27         58
        59         31         16         43          3         46         41         42          1          6
        25         40         62         17         49         50         60         37         18         63
        20          9         53         39         48         36         23         19          5         32
        44         28         14         33