6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        54         14         49         24         64          2         57         48         25          7
        16         37         61         19         46         45         52         53         38         31
        56         40         12          4         18         47         42         60         21         36
        50         26         59         51          5         10         20         32         33         44
        35         62          6         63         15         34         27         29          1          9
        17         58         22         41          3          8         30         11         23         28
        39         13         55         43