6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         8          9         50         18         20         30          4         49         24         21
        51         31         59          5         60         34         22         27         33         29
        17          7         39         15         40         14          3         36         44         42
        46          2         47         35         23         53         19         41         16          1
         6         32         61         63         58         26         54         52         25         13
        45         55         11         57         64         48         43         28         12         62
        56         38         37         10