6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 1024.000    y 1024.000    z 1024.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 63
         4         52         25          6          8         17         39         23         19         21
        27         28         22         60         63         45         34         41         24         42
        30         51         15         29          3         16         13         55         40         33
        50         43         36          2         49         31         32         35         44         18
        59          5         38         26         58         11         37         57         20         53
         7         10         54         12         14         18          1          9         62         47
        61         48         46         56