6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 1024.000    y 1024.000    z 1024.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 63
        61          9         15         10         21         42          2         16         57         60
        28          3          6         37         22         25         55         24         58         20
        49         11         50         32          5         54         18         31         26         19
        52         51         44         38          1         12         56         17         63         43
        35         53         33         45         30         62         13         46         40          7
        47         36         29         48         39         14          8         41         59         45
        34         23         27          4