6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        37          8         54         61          9         59          1         63         22         53
        43         14         24         40         15          6         32         10         42         34
        51         39         33         48         29         50         26         58         23          3
        35          2         46         20         31         55         52         62         41         47
        64         12         30         49         28          5         36         45         57          7
        25         60         44          4         56         19         27         16         11         38
        13         21         18         17