6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        13         21         41         53         19          4         16         26         42         50
        27          7         38         51         15         52         49         11         59         64
        55         23         63          6          8         58         28         12         31         18
        46         61          1         30         22         56         20         34         47         40
        43         62         25         45         17         10         14         24         48         32
        54          5         35          9          3         60         33         36         44          2
        57         39         29         37