6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        48         23         44         36         55         19         30         53         16         61
        52         29         11         32         15         22         45          8         38         60
        24         47          7         64         54         49         43         12         57         37
        18          5         50         26         63         13         51          3         59         58
        41          9         40         27          6         31         28         42         10         56
        20         33         62         39         25         35          2          1         14          4
        17         34         21         46