6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        26          6         11         40         47          9          3         29         10         50
        19          2         41          7         48         37         23         64          4         25
        20         52         34          1         12         30         56         43         18         63
        21         13         55         45         44         15         35         27         60         42
         8         24         38         57         59         36         46         62         54         32
        58         51         53         31         16         49         17         22         61         33
        28         39          5         14