6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         5         39         15         24         12         59         31          6         28         32
        57         33         62         30         36         23         46         11          7         20
        25         51         50         55         42         26         17         61         53         49
        35         14         52         58         60         44         56         40         38         64
         1         13         22         47          2         19          3         43         48         10
        21         27         29         37          9         18         16         41          4         54
        63         34          8         45