6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         4          2         36         59         41         13         44          7         48         30
        38         63         57         40         21         52         50         11         26          1
        20          5          3         35         64         19          9         53         54         17
        61         22         34         39          8         45         24         62         56         49
        43         46         31         18         58         28         33         16         60         47
        25         12         55         32         42         51         14         10         27         37
        29         15          6         23