6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         8         45         63         33          3          9         59         18         61         30
        19         35         26         47         54         41         55         57         64         49
        48         62         51          2         39         13         56         15          7         52
        37         42         38         58         27          5         46         11          4          1
        29         21         53         43         28         23         34         14         31         25
         6         50         24         16         36         10         60         20         22         40
        12         17         32         44