6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        25         34         59         52         41         12         40         24         15         17
        28         49         45         30         63          9         53         36         38          3
         1         51         47         11         39         14         29         35         19         62
        27         50         33          2          5         55         54          6         22         21
        57         56         26         61         42          7         16         31         46         48
        60         20         44         32         23         13          4         10         18         58
        64         37          8         43