6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        29         40          7         33         64         49         60         19         47         30
        26         37         16         12         56         22         32         36         51         61
         6          5         53         38         35         55         14         45         59         48
        25         27         10         17          1         18         39         42         58         62
        31          3         34         52         24         50         21         54         57          8
        46          2         63         15         43         41         28         23         11         44
        13         20          9          4