6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 9
         1          9          1          1          8          9          9          1          7          7
         7          3          7          7          7          1          8          8          1          1
         8          8          1          1          7          7          7          4          7          7
         7          1          8          9          9          9          8          8          9          9
         2          2          6          6          2          2          6          6          5          9
         9          9          9          9          9          9          3          7          6          3
         2          2          6          3