6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        28         41         64         31         33         48         35          3         45         60
        29         23         15         53         62         40         12         16         21         37
        19         36         39         22         30          2         63          9         55         57
        49         27         42         61          8          7         56         58         52         25
         4         18         34         47         59         44         24         32         51         26
        46         17         20         43          1         50         10         38         13          5
        14         11         54          6