6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        19         39         31         33         17         18          4         45         25         28
        46         15         37         10         20          8         34          6         36         53
        27         59         29          1         63         41         54         57         51         61
        11         64         55         30         38         35         42          2         16         50
        58         48         13         32         26         62          5         47         49         12
         9         14          3         40         21         52         43         56         23         22
        24          7         44         60