6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        64          3         33         16          7         36         27         29         26         62
         5         63         50          8         37         24         10         45          2         22
        48         58         41         49         30          6         12         57         60         40
        55         39         43          4         17         13         35          9         56         59
        21         14         32         25         11         31         51         44         38         23
        46         28          1         53         19         15         20         61         52         47
        18         42         54         34