6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         6         29         53         51         14         25         62          2         44         50
         3         42         57         37         18         34         22         12         13         10
        36         40         46         39         15         20         48         60          9         26
        28         38         11         45         17          7         56         33          8         21
        61         52         43         27          5         35         23         55          4         64
        47         49         63         58          1         30         41         19         16         59
        32         31         24         54