6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 6
         5          5          1          1          5          5          1          5          5          5
         1          1          5          5          1          1          4          4          3          3
         5          5          3          3          5          5          6          6          4          4
         6          6          4          4          3          3          5          5          3          3
         5          5          3          6          4          4          6          6          2          2
         1          1          5          5          3          3          5          5          1          1
         2          5          1          1