6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        57         63         16         14          4         34         10         58         55         15
        25         29         64         22         19         38         30         48         62         20
         9         17          2          7         18         21          6         49         42         37
        40         11         44         47         35          3         24          5         51         53
        61         36         59         12         60         54         26         50         46         32
        31         52         13         28         56         23          1         41         45         27
        43          8         39         33