6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        36         45         46         16         44         54         40          4         15         52
        58         64         39         62         22         14         34          3         48          9
        20         27         61         23         12         30         29         33         35          8
         2         59         53         17         13          5         47          6         56         57
        24         42         43         41         10         11         50          1         37          7
        26         31         51         18         32         60         38         21         63         49
        55         19         25         28