6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        52         47          5         18          8         12         64         42         10         45
        26         23         17         20         21         57         60         14         24         15
         7          2         34         25         46          3         56         36         44         27
        41          1         31         50         48         19          6         39         54         29
        33         16         61         28          4         62         63         37         13         59
        53          9         22         30         51         58         43         49         35         40
        55         38         32         11