6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         6         15         55         60         14          4         37         42         44         47
        18         34         54          5         51         17         13         43         27         26
        21         33         20         12         36         57         31         64          2         52
         8         35         40         63         30         38         41         50         61         62
        25         48         23          7         46         39          1         53         22         58
        59         24         56         29         49          3         11         32         16         10
        28          9         19         45