6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        18         20         14         19         26         53         21         57          2         33
        12         29          6         41         39         42         37         43         27         22
        17         30         55         32         52         13         36          4         11         54
         3         49         34          8         50         25         62         28         38         64
         7         59          9         24         60         40         23         15         63         48
        61         46         45          1         44         58         35         31         16         47
        10          5         56         51