6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        61         12         28         44         15         59         60          5         54         23
        25         48         51         52          4         36         49          1         26         62
        22          8         40         47         37         56         29          6         58         55
        19          2         50          3         31         20         38         64          9         42
        53         13         17         45          7         24         32         30         39         21
        63         16         18         33         57         34         27         46         10         11
        41         43         35         14