6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         5         33         46          1         21         50         53         39          3         12
        49          2         42         41         61         59         19          7         26         62
        47         45         31         30         35         14         63         43         60         40
        23         28         13         37         16         18         64         51         15          8
         6         54         25         17         27         57         20          4         22         24
         9         55         58         29         32         56         34         44         10         36
        48         11         38         52