6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        52         21         60         59          9         50         55         40         43         20
        64         14         48         15         34         31          4         27         23         62
        63         36          7         32         54         29          6         18          1         28
        44         11         58         41         16         51         49         38         22         42
        24         17         53         39         61         10         47         57          8          3
        26         13         37         35         12         45         46         19         33          5
        56         25         30          2