6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        19         28          1         14         46         10         52          8         44         41
        49         27         61         59         12         20         16          4          6         26
        21         43          7         54         45          3         48         62          9         50
        32         17         30         51         35         38         53         31         55          2
        64         47         23         34         22         25         42         58         33         63
        18         11         37         13          5         57         29         36         40         15
        39         56         60         24