6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        32         10         60         17         15         11         30         26         54         31
        42         44         43          6         29         23         57         45         56         40
        18         61         46          3          1          5         53         16         24         39
        34         50         19         13         47          7         52         25         36         21
        14         51         28         62         27         41         33         37         20         22
         2         58          4         38         64          8         63         48         35         49
        55          9         59         12