6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        29         64         12         26          4         10          7         22         50         40
        23         20         36         44         24         62         38         51         49          3
         5         53         37          9         46         11         15         58         21          6
         2         33         14         42         28         30         31         48         17         13
        52         43         61         47         54          1         41         19         18         27
        32          8         25         59         16         56         34         60         45         55
        57         63         39         35