6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        13         20         60         38         15         54         56         18         32         14
        16          8         40          7          5         50         53          1          9         51
        47         44         52         41         63         43         55         25         22         29
        31         64         26         30         58         61         11         36         42         37
        17          6         59         33          4         48         28         57         10         27
        23          2         35         34         46         62         12         24         45         39
         3         19         49         21