6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        64         49         36         22         25         60         40         54         23         51
        47         15         44          4         57         55         34         26         14          8
         1         56          3         52         24         28         50         39         13         42
        61         45         18         43          7         35          5         29         63         27
        48         32         33         20         37         16          6         11         21         62
        19         46         38         58          2         59         12         30         53         17
        10         31         41          9