6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        49          9         23         34          7         21          4         19         14         33
        24         44         64          6         51          8         12         29         55         40
        42         39         25         57         46         30         50         48         62         36
        37         13          2          5         53         10         27         18         32         38
        52         31         63         26         59         28          3         11         20         35
        56         16         22         17         15         58         43         60         41          1
        61         54         45         47