6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        34          3         14         45         63         12          9         51         64         22
        20         55         50         32         18          8         23         28         53         35
         4          1         56         61         17         44         57         37         16          6
        46         47         33         31         62         38         39         49         48         54
         2         29         21         10          5         30         59         43         41         58
        13          7         24         15         25         42         19         36         52         60
        27         11         26         40