6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        44          6         14          9          4          5          7          2         56         64
        51         16         19         33         34         27         15         20         22         58
        60         48         46         49         26         17         42         28         50         55
         8         45         53         30         21         29          3         10         62         12
        61         25         63         35         31         11         24         36         13         47
        59         38         39         23         37         57          1         18         54         52
        32         41         43         40