6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        47         40         48         58          9          5         59         19         24         64
        61         44          8          7         25         54          1         18         33         27
        15         41          2          6         39         57         42         45         20         52
        16         49         26         28         53         14         29         31         56         35
        13         51         55         30         50         17         32         10          3         11
        23         62         46         36         34         12         63         60          4         43
        37         21         22         38