6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        11          5         55         62          3         51         32         56         59         64
        25         24          7         20         31         40         52         49         45         23
        63         44         35         13         19         22         28         27         15          8
        30         39         48         57         33         43         26         37         14         47
        16         18         50         58         54          2          1         41         53         34
         9         42         36         21         60         29         12          6          4         38
        46         10         61         17