6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        13         51         53         50         57          7         32         38          8         23
        19         28         52         15         49         35         44         20         62         56
        48         22         59         39         10         21         41          2          6         27
        58         55         43         12          1         33         29         16         14          3
        24         26         11         61         37         18         17         30         36          5
        46          9         25         54         47         63         60         42         45         31
        64          4         34         40