6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        20          8         29         42          1         39          4         10         26         60
        14         24         18         12         15         31         28          7          6         43
        58         11          5          2         49         41         52         48         17         59
        55         27         30         37         38         51         36          3         40         32
        23         53         57         50         64         54         34         62         61         33
        44         46         16         47          9         22         35         25         63         13
        19         56         21         45