6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        47         55         61         37         24         49         41         46         31         17
        36         28         11         60         48         16         45         20          9         18
        39         30         50         53         33         52         23         62         32          2
        25          7          3         12          5          4         22         64         59         21
        14         19          8         42         43         34         13         54         58         15
         6         26         29          1         10         27         56         44         35         51
        63         57         38         40