6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 5
         1          1          2          1          1          1          4          1          5          5
         4          4          5          5          2          2          1          1          4          1
         1          1          4          1          5          5          4          4          5          5
         2          5          3          2          2          2          3          3          2          2
         3          3          2          2          3          2          2          2          3          2
         2          2          3          3          2          2          3          3          2          2
         3          2          2          2