6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         7         14         21         36         16         15         61         40         30         31
         5          1         29          6         12          9         32         60         13         46
        19          3         49         48         18         10          4         37         20         33
        35         25         47         41         24         42         22         11         28         51
        53         45         43         26         38         64         44         59         55         58
        50         54          2         17         57         27         34         62         63         52
        39         56         23          8