6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        34         46         23         27         50         37         48          6         31         56
        28          1          2         40          7         19         10         36         44         58
        38         11         49         55         12         21         15         47         29         51
        45         17         39         14         32          9         59         16         13          4
        26         24          5         33         22         20         18         64         30         53
        43         25         41         63         42         60         52         57          3         35
        61          8         54         62