6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        61         10         35         24         12         42         63         43         39         23
        25          2         18         20         64          3         62         46         26         41
        55          9         44         29          6         53          7         19         30         32
        52         13         58         37         22         21         36         45         31         14
        56         11         48         49         50          5         28         60         16          8
        57         51         27         33         59          4         38         34         47         15
         1         40         54         17