6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         1         50         63         48         53         38         29         18         41         21
        16         61          5         46          6          4          8         30         58         57
        42         56         49          7         26         64         47         62         39         13
        35         17         55         27         10         54         45         20         37         15
        24         32         12         28         36         60         11         34         14         22
        25          9         19         40         23         44         52          3         59         33
        31          2         51         43