6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        62         53          2         18         38         24         16         57         22         56
        60         52          7          9         59         19         30         51          1         64
        21         46         41         12         47         35         55         29         20         23
        39         17         10         44         13         58         42         61          3          4
        27         54         31         25          6         36         40         14         26         33
        63         45          8         49         11         43         34         48         50          5
        28         15         37         32