6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        47         36         20         52          6         10         22         40          1         17
        21         26         43         41         27         12         24         49         28          9
         5          7         34         39          8         54         50         33         15         38
        37         53         60         18         55         19         44         46         59         35
        14          3         30         32         64          2         63         57         25         58
         4         13         29         11         48         23         61         45         51         62
        16         42         56         31