6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         7         20         16         23         51         17         34          5         26          4
        19         13         14          8         41         44         46         21         49         37
        24         32          3         47         39         45         10         40         42         53
         1         52         36         22         15         29         59         31         62         38
        64         27         28         60         48          9         61         43         50         30
        56         63         54         33         55         18         57          6          2         58
        25         11         35         12