6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        34         25         15          4         59         17         61         62         31         27
        22         39         48         60          6          2         30         53         52         12
        50         38         54          1          5          9         45         33         20         32
        37         16         26         46         29         10         57          3         63         56
        14         11         42         64         36         24         40         49         43         51
        47         41          7         23         35         18         13          8         28         55
        19         44         21         58