6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        56         47         39         28          8         35         29         36          1         53
        59         27         57         20         43         17         22         15         61         40
        38         21          2         42         46         55         52         51         45         30
        32         44         34         33          4         24          3         26         62         19
        64         60         41         10         54         31         13         37         23         58
        11         14          5          6         50         49         12          7          9         63
        16         18         48         25