6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        37         49         23         13         59         25         33          7         32         36
        20         38         41          4          5          6         12         48         19         28
        26         53          3         56          9         51         27         54         14         62
        46         21         60         44         61         10          1         64         39         57
        42         34          8         58         55         16         45         63          2         47
        35         15         40         18         29         31         43         50         11         52
        30         22         17         24