6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        41         45         16         60          3         18         42         20         10          1
        63         24         51         12         34         27         40         19          5         55
         8         39         46         62         37         28         29         21          7         22
        15         33         25         13         14         30         31         61          9         35
        47         64         38          4         44         36         23         59         53         48
        56         49          6         54         32         43         58         50         52         11
         2         57         26         17