6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        27         14          4         36         55         37         20         18          8         15
        39         41         17         10         56         60         21         13          6          3
        30         47         28         40         51         43         44         26         61         11
        19         49         50         54         33         32         34         38         48          2
        63         31         53         42          5         59         25          7         64         45
        23         58         22         29         62         52         12         46          9         35
        24         16          1         57