6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        56         43         38         13         22         26         51         14         36          5
        28         35         16          8         62         12         47         25         39          9
        11         31         46         63         34         60         58         27         61         57
        49         24         53         29         10         48         54         55         52         23
         1         41          4         33         44         40         30         32         42          2
        50         59         17         19          3         20         37         21          7         45
        18          6         15         64