6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        34         10         43         17         64         26          7         55         53         25
        18         15         21         44         11          5          1          9         48         37
        42         35         24         50         13         58          2         27         47         61
        63         36         39         14         33          4         46         12         62         57
        31         19         60         40         38         22         51         23         54         45
        41         28         32         29         52          8         16         20         49         30
         3          6         56         59