6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        57         52         22         45         63         41         39         38         11         17
        54         49         27         37         64         35         12         20         25          5
         3         14         10         40         47         13          8         19         16         53
        15         24         18         44         46         28          2         29         50          1
        32         61          6         23          4         60         21         42         55         62
        48         58         34         43          7         33         31          9         26         56
        51         36         30         59