6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        37         63         15         61         54         11         28         41         49         30
        64         51          8          7         32         45         26         46          3         34
        29         48         22          9         17         27         33         47          5         42
        13         43         23         59         19         38         20         16         58         24
        35         25         55         50         52         57         60         12         53         36
        14         31          4         21         18         40         44         10         39          6
         1         62          2         56