6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        39         52         45         32         27          5         60         53          1         62
        34         54         22         12         19         42         29         24         55          8
        57         14          6          3         43         61         26         35         59         23
        41         16         47         18         17         30         37         20         21         33
        56         49         10          9          4         36          7         13         51         48
        58         40         11         31         15          2         46         28         50         64
        63         25         44         38