6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        63         28         55         10         33         47         38         53         48         57
        17         30         19         62         39         40         56         25         15          4
        54          1         46         52         18         42          2          3          5         34
        26          9         13         22         50         49         21         59         44         27
        11          7         45         43         12         36         37         58         51         23
        20         64         29         60          8         41         35         14         24         61
        31         16         32          6