6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         4          1         24         15         55          9         40         41         21         52
        62         29         38         30         33         11         43          5         57          7
        37         56         60          2         39         61         59         49         19         46
        17         50         36         31         10         28         16         34         54         26
        20         47         13         23          3         53         22         64         58         12
        63         48          6         27         25         35         51         32          8         42
        18         45         14         44