6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         6         14         61         47         58         13          4         21         20         36
        28          5         52         43         64         38         56         60         12         29
        39         62         40         46         54          7         31          1         27         11
        30         24         63         37         50         59         10         18         17         45
        25          3         34         53         32         49         15         41         35         26
        19         16         44         33          9          8         22         23         57         55
        42         51          2         48