6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        59         40         35         61         60         17          2         24         54         16
        22         38         32         56          5         46          1         41         44         58
         3         12         13         29         50         33         62         34         14         11
         6         36         18         25         49         55         19          9         51         48
        10         39         20         23         63         52          4          8         43         30
        47         21         26         57         42         15         27         45         37          7
        31         64         53         28