6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        20          3         41         56         42         52         23         38         58          5
        60         24         51         43          9         62         48          7         53         46
        33         12         54         49         59         36          1          6         26         22
        13         16         32         50         11          4         18         19          2         29
        28         31         55         57         14         35          8         15         47         30
        17         34         37         64         10         39         25         27         45         61
        21         40         63         44