6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         4         58         30         45         17         35         57         43         18         53
        16          1         34         15         52         56          6         23          2         54
        59         38         46         31         20         29         12         37         24         19
        32         55         13         40         48         41         51         62         21         22
        50         36          9         33         60         63         11         28         49          7
        26          8          5         44         47         25         10         42         61         14
        39         27          3         64