6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        13         31         11         45         26         57         62          5         42         55
        25          9         51         34         59          7         63         17          1         39
        20         40         10         28         60         44         53         12          4         43
        24         37         50         15         35         32         27         54         33          3
        18         23         38         29         41         58         56         46         16          6
        48         19          8         22         61         30         21         64         49         14
         2         47         36         52