6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        41         52         31         62          3         14          9         18         23         39
        17         53         63         34         19         26         51         27         50          6
        15         33         30         57         37         47         46         21         48         28
        11         45          5         10         36         61         44         16         13         40
         8          4         56         49          7         58         12         54         43         59
        38         60          1         24         55          2         35         32         25         64
        42         20         29         22