6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        32         20          7         28         42         49          2         59         27         50
        53          9         46         21         47         12         14         30         23         58
        24         45         33         60         25         44         19         31         34          6
         5         29          1         10         35         51         63         17          3         52
        55          8         48         38         64         13         22         61         57         41
        26         40         37         36         43         16         15         39         54         18
        56         62          4         11