6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        52         11         49          5          1         34         31         22         12         45
        32         14         28         10         43         39         18         29         27         33
        25         47         48         38          9         21         55         17         24         51
        40         44         16         41         15         30         20         56          6         64
        23         37          7         63         13          8         42         53         60         35
        62          2         36         26         58         19         54         57         50         61
         3          4         46         59