6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        38         61         55          9         42         29         35         60         32         48
        33         15         56         23         28         25          1         17         20         39
        44         26         12          5         59         21         24         13         46         34
        53          7         27         54          3         63         62         18         36         19
        43         22         64         31         51          4         47         45         52          8
        58         11         57         10         49         50         16         30          2         37
        41          6         14         40