6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        37         36         28         63         51         40         57          9         19          8
        33         64          7         23         58         43         25         39         54         31
        35         62         41         18         22         52         15         21         53          3
        61         32         48         34         24         20         56          5         49         12
        60         46          2         38         59         11          6         16         14         26
        47         29         17         50         10         55         42          1          4         44
        27         45         13         30