6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        15         49         34         36         57         54         14         21         50          1
        16         47         55         38         20          8         52         22         63         10
        40          2         13          7         41         32         39         64          6         56
        11         43         17         59         25          5         61          3         44         33
        46         60         26          9         29         28         53         42         27         18
        48         30         19         62         23          4         35         12         37         45
        31         24         51         58