6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        34         26         43         32         60          2         57         17         40         45
         7         29         62         50         35         31         61         56         49         36
         3          6         14         48         15         47          8         58         42         33
        11         10         28         39         20         55          9         13         64         46
        53         12         27         21         52          1         16         24         22         41
        59         18         44         51          4         63         37         25         23         54
        30          5         38         19