6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        13         25         60         39         50          2         53         46         38         34
        40         30         49         16         41         14         59         55         61         44
        52         51         33          9         56         18         29         43         37          8
        24          4         48          6         17         19         28          7         42         15
        31         64         11         36         26         45         63         12         47         20
         3         54          1         58         23         27         32         10         21         35
         5         62         57         22