6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        32         43          6         19         16         60         39          4         47         20
        49          7          5         62         11         34         26         40         63         37
        50         48         30         14         45         15         51         28         23          8
        54         44          2         57         10         53         25         56         27         42
        52          3         12         46          9          1         61         33         35         21
        36         18         55         29         13         24         17         38         58         31
        64         41         59         22