6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        25         26         16         24          4         19         12          9         55         60
        21         20         28         30         63         64         53          2         49         43
         1         38         48         15         46         17         18         22         11         29
        52         37         47         40          6         54          5         44         51         56
        34         36         50         45         57         13         58         32         59         33
         3         42         14         10         23         41         31         62         39         61
         8         27          7         35