6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        51         54         56          9         23          1         17         22         58         52
        35         28          4         43         49         36         41         15          6         13
        21         16         29         47         33         14         50         63         25         38
        60         46         42         19         32          2         59         11         31         12
        18          3          8         30         34         26         62         53         64         48
        61          5          7         24         20         45         44         37         55         10
        40         39         57         27