6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        61         28         43         12         14         48         53         63          5          3
        64         13         47         29         45         31         59         56         22         23
        30         40          8         58         21          7         49         25         38         60
        34         57         16         46         42         10         20         17         36         26
         4         33         27         55         41         50          9         52         44         32
        37         11         24         51         19          6         54         15          1         35
        39          2         18         62