6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        50          3          4         54          7         57         39         34         22         61
         5         37         14         47         41         26         56          6          1         51
        53         46         29         40         18         15         42         62         49         20
        35         58         33         63         30         38         32         31         13         21
        28          2         55         52         27         60         17         19         24         43
        10         44         25         36         23         45         16         48         11         59
        64          9          8         12