6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        14         57         53         36         17         31         20          8         63         39
        15         22         52         34          5         55         61         40         45          9
        19         49         33         54         18         26         51         16         43          7
        42         59         64         23          1         44         37         30         60         46
         6         25         29         58         28          2         48         41         38         35
        50          4         13         11         21         56         12          3         62         47
        32         10         27         24