6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        47         41         61         18         48         64         36         28         43          7
        29          5         34          8         35         17         12         30         56         32
        52         33         63         60         10         19         53         42          1         11
        62         58         55         22         15          4         24         39         26         14
        59          6         44         13         27         31         49         25         45         23
         2         40         38         54         50          9         46         51         16          3
        57         21         37         20