6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        62         14          1         43          7         32          5         36         58         15
        25         21          4         18         49         61         27         63         41         28
        46         13         54         29         30         24         12         42         16         17
        59         55         23         52         47         20         45         60         51         44
         3         31         26         19         39          2         33          9          8         10
        57         38         64         50         37          6         40         22         35         34
        53         56         48         11