6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        29         36         16         15         13         31         25         62         28         17
        33         44         35         46         19         45         61         64          9         27
         8         47         14         30         10          1         56         37         54         38
        41         57         24         58         23         18          5          4         11         48
        42         52         26         20         59         50          6         63         22         55
        43          7         12         32         40         51         39         49         21         60
        53         34          3          2