6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         2         23         10         28         44         11         17         62         59          9
        38          3         24         40         42          7         34         33         27         55
        52         32         58         56         31         25         19         13         14         50
        61         41         12         21         37         60         53         49         36         22
        57         45         18         26          6         54          1         35         29         20
        47          5         16         30         46         64          8         43         48         15
        63         39         51          4