#!/bin/bash


startLineNum=$(grep -inr 'Generated by DREAM.3D' material.config | cut -d":" -f1)
startLineNum=$(( $startLineNum - 1 ))
# echo $startLineNum

# sed -n '${startLineNum},$p' material.config > dream3d.material.config
tail -n +"${startLineNum}" material.config > dream3d.material.config

