6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 6
         1          1          4          4          1          1          5          5          5          2
         5          5          2          2          4          5          1          1          3          3
         1          1          5          5          5          2          5          5          2          2
         3          3          6          6          4          4          6          6          6          4
         6          6          6          5          6          6          4          4          4          6
         4          4          6          6          4          4          6          6          6          4
         6          6          4          4