6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        39         54         56         15          8         33         47         41         46         16
        52          1         50         17         49         62          7         34          5          9
        28         48         21          4          2         57         37         10          3         36
        22         19         55         58         27         53         25         31         24         12
        29         11         14         38         63         32         18         42          6         51
        61         64         45         20         60         30         43         23         13         59
        35         26         44         40