6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        14         39          2         41         46         45         26         57         18         23
        11          1         50         24         20         25         16         34         53         12
        59          7         30          5          3         29         52         49         47         38
        35         36         63          9          8         10         33         22          6         37
        51         28         31         54         17         19         55         48         56         43
        58         61         21         42         13         60         44         15         62         40
        27         32          4         64