6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         2         61         27         57         24         59         23         43         18         47
        46          8         17         15         42          7          6         16         19         44
        62         31          1         54         48         63         51         36         49         35
        34         38         39         58         53         60         64          4         37         33
        29          3         40         10         22         20         26         32         12         13
        45         50         21         56         14         28         52         11          5         30
        41          9         55         25