6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        12          3         34         24          9         46         50         41         13         62
        51         16          5         37         39         58          6         64         54         17
        43         48         36         32         31         21          2         44         60         56
        28         26         35         10         29         23         38         49         20         53
        61         14          7         59         19         42         63         18         11          1
        30         40          8          4         22         57         47         45         55         27
        33         15         52         25