6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         7          3         30         43          5         31         46         62         41         34
        55         17         37         11         35         16         14          1         57         58
        56         51         61         19         44         48         24         40         20         50
        22         49         36         29          2         26         28          9         64         47
         8         52         54         10         63         12         27         25         15         18
        39         59         53         21          6         45          4         23         33         42
        60         38         32         13