6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         9         42         36         54         17         58         22          7          2         61
        18          5         37         34          8         53         28         50         29         40
        41         13         64          3         62         44          1         12         33         25
        47         21         49         60         51         32          6         39         46         16
        56         15         27         30         19         43         55         20         10         57
        45         11         31         59         24         23         63         52          4         26
        38         48         14         35