6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        14          1         48         47          8         33         38         42         53          6
        49         26         63         13         21          4         54         51         41         36
        37         29         64          5         46         39         15         16         28         60
         9         30          3         52         40         44         45         61         19         32
        23         31         27         58         24         17         59         62         20         34
        56          7         55         50         10         11         12         43         18          2
        25         57         22         35