6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        42          6         40         59         54         35          8         49         16         13
         3         64          5         57         30         24         25          9         14         38
        46         31         27         43         11          4         18         17          1         10
        56         63         23         34         19         22         53         45         39         62
        26         37         52         21         20         33         60         15          2         48
        29         58         61         41          7         50         51         44         36         47
        28         32         12         55