6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        43         40         50         36         26         45         59         23         14         38
        33         17         21         57         58         52         27         55         18         12
         5         54         22         46          2         47         32         20         64          6
        25         44         42          8         30          1          7         56         19         39
        34         10         31         37         24         48         13         41         63         28
        15         16         53          4          9         35         49         11         29         60
        62         51          3         61