6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         6         57         44         16          5         60         25         34         45         31
        42         10         13         12         30         50         27         26         62         24
        41         49         20         22         56         54         21         61         36         53
        38          4         17         11         33         52         63         37          7         40
        43         28         18         58         59         15          9          1          3         39
        35          8         32         46         47         29         55         48         19         14
        64         51         23          2