6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        28         42          6         25         61         24         14         58         16         15
        60         22         50         53         30         47         46         57         31         64
        34          5         44          3         45          2         40         19         39         54
        35         49         48         17         18         36         23          8          1         55
        33          9         41         38         11         26         27         52         56          7
        13         21          4         12         62         59         51         63         43         37
        29         32         20         10