6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        26         49          1         28         16         62         63         64         29         52
        31         38         58          9         41         13         20         22         61         11
        12          2         40          8         53         57         23         15         44         17
        55         37         34         42         10         43         36         51         39         18
         3          4         24         56         19          6          7         14         45         48
        30         35         25         50         54          5         27         46         47         32
        33         60         21         59