DAMASK with MSC.Marc FEM solver: kinematics_thermal_expansion Module Reference
kinematics_thermal_expansion Module Reference
material subroutine incorporating kinematics resulting from thermal expansion
Data Types
type tparameters
Functions/Subroutines
subroutine, public kinematics_thermal_expansion_init
module initialization
pure real(preal) function, dimension(3, 3), public kinematics_thermal_expansion_initialstrain (homog, phase, offset)
report initial thermal strain based on current temperature deviation from reference
subroutine, public kinematics_thermal_expansion_lianditstangent (Li, dLi_dTstar, ipc, ip, el)
contains the constitutive equation for calculating the velocity gradient
Variables
integer, dimension(:), allocatable kinematics_thermal_expansion_instance
type(tparameters), dimension(:), allocatable param
Detailed Description
material subroutine incorporating kinematics resulting from thermal expansion
Author
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
to be done
Function/Subroutine Documentation
kinematics_thermal_expansion_init()
subroutine, public kinematics_thermal_expansion::kinematics_thermal_expansion_init
module initialization
reads in material parameters, allocates arrays, and does sanity checks
Definition at line 15725 of file DAMASK_marc.f90.
References config::config_phase, debug::debug_constitutive, debug::debug_level, debug::debug_levelbasic, material::kinematics_thermal_expansion_id, kinematics_thermal_expansion_instance, material::kinematics_thermal_expansion_label, lattice::lattice_applylatticesymmetry33(), param, and material::phase_kinematics.
Referenced by constitutive::constitutive_init().
kinematics_thermal_expansion_initialstrain()
pure real(preal) function, dimension(3,3), public kinematics_thermal_expansion::kinematics_thermal_expansion_initialstrain (integer, intent(in) homog, integer, intent(in) phase, integer, intent(in) offset)
report initial thermal strain based on current temperature deviation from reference
Returns
initial thermal strain (should be small strain, though)
Definition at line 15768 of file DAMASK_marc.f90.
References kinematics_thermal_expansion_instance, and param.
Referenced by constitutive::constitutive_initialfi().
kinematics_thermal_expansion_lianditstangent()
subroutine, public kinematics_thermal_expansion::kinematics_thermal_expansion_lianditstangent (real(preal), dimension(3,3), intent(out) Li, real(preal), dimension(3,3,3,3), intent(out) dLi_dTstar, integer, intent(in) ipc, integer, intent(in) ip, integer, intent(in) el)
contains the constitutive equation for calculating the velocity gradient
Parameters
[in] el element number
[out] li thermal velocity gradient
[out] dli_dtstar derivative of Li with respect to Tstar (4th-order tensor defined to be zero)
Parameters
ipc grain number
ip integration point number
Definition at line 15791 of file DAMASK_marc.f90.
References kinematics_thermal_expansion_instance, and param.
Referenced by constitutive::constitutive_lianditstangents().
Variable Documentation
kinematics_thermal_expansion_instance
integer, dimension(:), allocatable kinematics_thermal_expansion::kinematics_thermal_expansion_instance private
Definition at line 15701 of file DAMASK_marc.f90.
Referenced by kinematics_thermal_expansion_init(), kinematics_thermal_expansion_initialstrain(), and kinematics_thermal_expansion_lianditstangent().
param
type(tparameters), dimension(:), allocatable kinematics_thermal_expansion::param private
Definition at line 15710 of file DAMASK_marc.f90.
Referenced by kinematics_thermal_expansion_init(), kinematics_thermal_expansion_initialstrain(), and kinematics_thermal_expansion_lianditstangent().