DAMASK with MSC.Marc FEM solver: thermal_conduction Module Reference
thermal_conduction Module Reference
material subroutine for temperature evolution from heat conduction
Data Types
type tparameters
Functions/Subroutines
subroutine, public thermal_conduction_init
module initialization
subroutine, public thermal_conduction_getsourceanditstangent (Tdot, dTdot_dT, T, ip, el)
returns heat generation rate
real(preal) function, dimension(3, 3), public thermal_conduction_getconductivity (ip, el)
returns homogenized thermal conductivity in reference configuration
real(preal) function, public thermal_conduction_getspecificheat (ip, el)
returns homogenized specific heat capacity
real(preal) function, public thermal_conduction_getmassdensity (ip, el)
returns homogenized mass density
subroutine, public thermal_conduction_puttemperatureanditsrate (T, Tdot, ip, el)
updates thermal state with solution from heat conduction PDE
subroutine, public thermal_conduction_results (homog, group)
writes results to HDF5 output file
Variables
type(tparameters), dimension(:), allocatable param
Detailed Description
material subroutine for temperature evolution from heat conduction
Author
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
thermal_conduction_getconductivity()
real(preal) function, dimension(3,3), public thermal_conduction::thermal_conduction_getconductivity (integer, intent(in) ip, integer, intent(in) el)
returns homogenized thermal conductivity in reference configuration
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 23700 of file DAMASK_marc.f90.
References crystallite_push33toref().
thermal_conduction_getmassdensity()
real(preal) function, public thermal_conduction::thermal_conduction_getmassdensity (integer, intent(in) ip, integer, intent(in) el)
returns homogenized mass density
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 23752 of file DAMASK_marc.f90.
thermal_conduction_getsourceanditstangent()
subroutine, public thermal_conduction::thermal_conduction_getsourceanditstangent (real(preal), intent(out) Tdot, real(preal), intent(out) dTdot_dT, real(preal), intent(in) T, integer, intent(in) ip, integer, intent(in) el)
returns heat generation rate
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 23641 of file DAMASK_marc.f90.
Referenced by flux().
thermal_conduction_getspecificheat()
real(preal) function, public thermal_conduction::thermal_conduction_getspecificheat (integer, intent(in) ip, integer, intent(in) el)
returns homogenized specific heat capacity
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 23726 of file DAMASK_marc.f90.
thermal_conduction_init()
subroutine, public thermal_conduction::thermal_conduction_init
module initialization
reads in material parameters, allocates arrays, and does sanity checks
Definition at line 23605 of file DAMASK_marc.f90.
References config::config_homogenization, prec::emptystringarray, material::material_homogenizationat, material::material_homogenizationmemberat, material::temperature, material::temperaturerate, material::thermal_conduction_id, material::thermal_initialt, material::thermal_type, material::thermal_typeinstance, material::thermalmapping, and material::thermalstate.
Referenced by homogenization::homogenization_init().
thermal_conduction_puttemperatureanditsrate()
subroutine, public thermal_conduction::thermal_conduction_puttemperatureanditsrate (real(preal), intent(in) T, real(preal), intent(in) Tdot, integer, intent(in) ip, integer, intent(in) el)
updates thermal state with solution from heat conduction PDE
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 23779 of file DAMASK_marc.f90.
thermal_conduction_results()
subroutine, public thermal_conduction::thermal_conduction_results (integer, intent(in) homog, character(len=*), intent(in) group)
writes results to HDF5 output file
Definition at line 23802 of file DAMASK_marc.f90.
References param.
Referenced by homogenization::homogenization_results().
Variable Documentation
param
type(tparameters), dimension(:), allocatable thermal_conduction::param private
Definition at line 23585 of file DAMASK_marc.f90.
Referenced by thermal_conduction_results().