DAMASK with MSC.Marc FEM solver: discretization_marc Module Reference
discretization_marc Module Reference
Sets up the mesh for the solver MSC.Marc.
Data Types
type tcellnodedefinition
Functions/Subroutines
subroutine, public discretization_marc_init (ip, el)
initializes the mesh by calling all necessary private routines the mesh module Order and routines strongly depend on type of solver
subroutine writegeometry (elem, connectivity_elem, connectivity_cell, coordinates_nodes, coordinates_points)
Write all information needed for the DADF5 geometry.
subroutine inputread (elem, node0_elem, connectivity_elem, microstructureAt, homogenizationAt)
Read mesh from marc input file.
subroutine inputread_fileformat (fileFormat, fileContent)
Figures out version of Marc input file format.
subroutine inputread_tablestyles (initialcond, hypoelastic, fileContent)
Figures out table styles for initial cond and hypoelastic.
subroutine inputread_matnumber (matNumber, tableStyle, fileContent)
Figures out material number of hypoelastic material.
subroutine inputread_nnodesandelements (nNodes, nElems, fileContent)
Count overall number of nodes and elements.
subroutine inputread_nelemsets (nElemSets, maxNelemInSet, fileContent)
Count overall number of element sets in mesh.
subroutine inputread_mapelemsets (nameElemSet, mapElemSet, fileContent)
map element sets
subroutine inputread_mapelems (FEM2DAMASK, nElems, nNodesPerElem, fileContent)
Maps elements from FE ID to internal (consecutive) representation.
subroutine inputread_mapnodes (FEM2DAMASK, nNodes, fileContent)
Maps node from FE ID to internal (consecutive) representation.
subroutine inputread_elemnodes (nodes, nNode, fileContent)
store x,y,z coordinates of all nodes in mesh.
subroutine inputread_elemtype (elem, nElem, fileContent)
Gets element type (and checks if the whole mesh comprises of only one type)
integer function, dimension(nnodes, nelem) inputread_connectivityelem (nElem, nNodes, fileContent)
Stores node IDs.
subroutine inputread_microstructureandhomogenization (microstructureAt, homogenizationAt, nElem, nNodes, nameElemSet, mapElemSet, initialcondTableStyle, fileContent)
Stores homogenization and microstructure ID.
subroutine buildcells (connectivity_cell, cellNodeDefinition, elem, connectivity_elem)
Calculates cell node coordinates from element node coordinates.
subroutine buildcellnodes (node_cell, definition, node_elem)
Calculates cell node coordinates from element node coordinates.
subroutine buildipcoordinates (IPcoordinates, connectivity_cell, node_cell)
Calculates IP coordinates as center of cell.
real(preal) function, dimension(elem%nips, size(connectivity, 3)) ipvolume (elem, node, connectivity)
Calculates IP volume.
real(preal) function, dimension(3, elem%nipneighbors, elem%nips, nelem) ipareanormal (elem, nElem, connectivity, node)
calculation of IP interface areas
integer function, dimension(1+maxn) continuousintvalues (fileContent, maxN, lookupName, lookupMap, lookupMaxN)
return integer list corresponding to items in consecutive lines. First integer in array is counter
logical function containsrange (str, chunkPos)
return whether a line contains a range ('X to Y')
Variables
type(tcellnodedefinition), dimension(:), allocatable cellnodedefinition
real(preal), public, protected mesh_unitlength
physical length of one unit in mesh
integer, dimension(:), allocatable, public mesh_fem2damask_elem
DAMASK element ID for Marc element ID.
integer, dimension(:), allocatable, public mesh_fem2damask_node
DAMASK node ID for Marc node ID.
Detailed Description
Sets up the mesh for the solver MSC.Marc.
Author
Franz Roters, Max-Planck-Institut für Eisenforschung GmbH
Philip Eisenlohr, Max-Planck-Institut für Eisenforschung GmbH
Christoph Kords, Max-Planck-Institut für Eisenforschung GmbH
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
buildcellnodes()
subroutine discretization_marc::buildcellnodes (real(preal), dimension(:,:), intent(out) node_cell, type(tcellnodedefinition), dimension(:), intent(in) definition, real(preal), dimension(:,:), intent(in) node_elem) private
Calculates cell node coordinates from element node coordinates.
Parameters
[out] node_cell cell node coordinates
[in] definition cell node definition (weights and parents)
[in] node_elem element nodes
Definition at line 10933 of file DAMASK_marc.f90.
References cellnodedefinition.
Referenced by discretization_marc_init().
buildcells()
subroutine discretization_marc::buildcells (integer, dimension(:,:,:), intent(out) connectivity_cell, type(tcellnodedefinition), dimension(:), intent(out) cellNodeDefinition, type(telement), intent(in) elem, integer, dimension(:,:), intent(in) connectivity_elem) private
Calculates cell node coordinates from element node coordinates.
Definition at line 10776 of file DAMASK_marc.f90.
References math::math_sort(), and uniquerows().
Referenced by discretization_marc_init().
buildipcoordinates()
subroutine discretization_marc::buildipcoordinates (real(preal), dimension(:,:), intent(out) IPcoordinates, integer, dimension(:,:), intent(in) connectivity_cell, real(preal), dimension(:,:), intent(in) node_cell) private
Calculates IP coordinates as center of cell.
Parameters
[out] ipcoordinates cell-center/IP coordinates
[in] connectivity_cell connectivity for each cell
[in] node_cell cell node coordinates
Definition at line 10963 of file DAMASK_marc.f90.
Referenced by discretization_marc_init().
containsrange()
logical function discretization_marc::containsrange (character(len=*), intent(in) str, integer, dimension(:), intent(in) chunkPos) private
return whether a line contains a range ('X to Y')
Parameters
[in] chunkpos positions of start and end of each tag/chunk in given string
Definition at line 11153 of file DAMASK_marc.f90.
References io::io_lc(), and io::io_stringvalue().
Referenced by continuousintvalues(), and inputread_nelemsets().
continuousintvalues()
integer function, dimension(1+maxn) discretization_marc::continuousintvalues (character(len=*), dimension(:), intent(in) fileContent, integer, intent(in) maxN, character(len=*), dimension(:), intent(in) lookupName, integer, dimension(:,:), intent(in) lookupMap, integer, intent(in) lookupMaxN) private
return integer list corresponding to items in consecutive lines. First integer in array is counter
ints concatenated by "c" as last char, range of a "to" b, or named set
Parameters
[in] filecontent file content, separated per lines
Definition at line 11097 of file DAMASK_marc.f90.
References containsrange(), io::io_intvalue(), io::io_lc(), io::io_stringpos(), and io::io_stringvalue().
Referenced by inputread_mapelemsets(), and inputread_microstructureandhomogenization().
discretization_marc_init()
subroutine, public discretization_marc::discretization_marc_init (integer, intent(in) ip, integer, intent(in) el)
initializes the mesh by calling all necessary private routines the mesh module Order and routines strongly depend on type of solver
Definition at line 10093 of file DAMASK_marc.f90.
References buildcellnodes(), buildcells(), buildipcoordinates(), fesolving::calcmode, cellnodedefinition, debug::debug_e, debug::debug_i, discretization::discretization_init(), fesolving::fesolving_execelem, fesolving::fesolving_execip, geometry_plastic_nonlocal::geometry_plastic_nonlocal_results(), geometry_plastic_nonlocal::geometry_plastic_nonlocal_setiparea(), geometry_plastic_nonlocal::geometry_plastic_nonlocal_setipareanormal(), geometry_plastic_nonlocal::geometry_plastic_nonlocal_setipvolume(), inputread(), io::io_error(), ipareanormal(), ipvolume(), mesh_fem2damask_elem, mesh_unitlength, numerics::numerics_unitlength, and writegeometry().
Referenced by cpfem_initall().
inputread()
subroutine discretization_marc::inputread (type(telement), intent(out) elem, real(preal), dimension(:,:), intent(out), allocatable node0_elem, integer, dimension(:,:), intent(out), allocatable connectivity_elem, integer, dimension(:), intent(out), allocatable microstructureAt, integer, dimension(:), intent(out), allocatable homogenizationAt) private
Read mesh from marc input file.
Parameters
[out] node0_elem node x,y,z coordinates (initially!)
Definition at line 10214 of file DAMASK_marc.f90.
References damask_interface::getsolverjobname(), damask_interface::inputfileextension, inputread_connectivityelem(), inputread_elemnodes(), inputread_elemtype(), inputread_fileformat(), inputread_mapelems(), inputread_mapelemsets(), inputread_mapnodes(), inputread_matnumber(), inputread_microstructureandhomogenization(), inputread_nnodesandelements(), inputread_tablestyles(), io::io_read_ascii(), mesh_fem2damask_elem, and mesh_fem2damask_node.
Referenced by discretization_marc_init().
inputread_connectivityelem()
integer function, dimension(nnodes,nelem) discretization_marc::inputread_connectivityelem (integer, intent(in) nElem, integer, intent(in) nNodes, character(len=*), dimension(:), intent(in) fileContent) private
Stores node IDs.
Parameters
[in] nnodes number of nodes per element
[in] filecontent file content, separated per lines
Definition at line 10670 of file DAMASK_marc.f90.
References io::io_intvalue(), io::io_lc(), io::io_stringpos(), io::io_stringvalue(), mesh_fem2damask_elem, and mesh_fem2damask_node.
Referenced by inputread().
inputread_elemnodes()
subroutine discretization_marc::inputread_elemnodes (real(preal), dimension(:,:), intent(out), allocatable nodes, integer, intent(in) nNode, character(len=*), dimension(:), intent(in) fileContent) private
store x,y,z coordinates of all nodes in mesh.
Parameters
[in] filecontent file content, separated per lines
Definition at line 10554 of file DAMASK_marc.f90.
References io::io_floatvalue(), io::io_intvalue(), io::io_lc(), io::io_stringpos(), io::io_stringvalue(), mesh_fem2damask_node, and mesh_unitlength.
Referenced by inputread().
inputread_elemtype()
subroutine discretization_marc::inputread_elemtype (type(telement), intent(out) elem, integer, intent(in) nElem, character(len=*), dimension(:), intent(in) fileContent) private
Gets element type (and checks if the whole mesh comprises of only one type)
Parameters
[in] filecontent file content, separated per lines
Definition at line 10587 of file DAMASK_marc.f90.
References io::io_error(), io::io_lc(), io::io_stringpos(), io::io_stringvalue(), and mapelemtype().
Referenced by inputread().
inputread_fileformat()
subroutine discretization_marc::inputread_fileformat (integer, intent(out) fileFormat, character(len=*), dimension(:), intent(in) fileContent) private
Figures out version of Marc input file format.
Parameters
[in] filecontent file content, separated per lines
Definition at line 10279 of file DAMASK_marc.f90.
References io::io_intvalue(), io::io_lc(), io::io_stringpos(), and io::io_stringvalue().
Referenced by inputread().
inputread_mapelems()
subroutine discretization_marc::inputread_mapelems (integer, dimension(:), intent(out), allocatable FEM2DAMASK, integer, intent(in) nElems, integer, intent(in) nNodesPerElem, character(len=*), dimension(:), intent(in) fileContent) private
Maps elements from FE ID to internal (consecutive) representation.
Parameters
[in] nnodesperelem number of nodes per element
[in] filecontent file content, separated per lines
Parameters
nElems number of elements
Definition at line 10474 of file DAMASK_marc.f90.
References io::io_intvalue(), io::io_lc(), io::io_stringpos(), io::io_stringvalue(), and math::math_sort().
Referenced by inputread().
inputread_mapelemsets()
subroutine discretization_marc::inputread_mapelemsets (character(len=pstringlen), dimension(:), intent(out), allocatable nameElemSet, integer, dimension(:,:), intent(out), allocatable mapElemSet, character(len=*), dimension(:), intent(in) fileContent) private
map element sets
Parameters
[in] filecontent file content, separated per lines
Definition at line 10441 of file DAMASK_marc.f90.
References continuousintvalues(), inputread_nelemsets(), io::io_lc(), io::io_stringpos(), and io::io_stringvalue().
Referenced by inputread().
inputread_mapnodes()
subroutine discretization_marc::inputread_mapnodes (integer, dimension(:), intent(out), allocatable FEM2DAMASK, integer, intent(in) nNodes, character(len=*), dimension(:), intent(in) fileContent) private
Maps node from FE ID to internal (consecutive) representation.
Parameters
[in] nnodes number of nodes
[in] filecontent file content, separated per lines
Definition at line 10518 of file DAMASK_marc.f90.
References io::io_intvalue(), io::io_lc(), io::io_stringpos(), io::io_stringvalue(), and math::math_sort().
Referenced by inputread().
inputread_matnumber()
subroutine discretization_marc::inputread_matnumber (integer, dimension(:), intent(out), allocatable matNumber, integer, intent(in) tableStyle, character(len=*), dimension(:), intent(in) fileContent) private
Figures out material number of hypoelastic material.
Parameters
[in] filecontent file content, separated per lines
Definition at line 10330 of file DAMASK_marc.f90.
References io::io_intvalue(), io::io_lc(), io::io_stringpos(), and io::io_stringvalue().
Referenced by inputread().
inputread_microstructureandhomogenization()
subroutine discretization_marc::inputread_microstructureandhomogenization (integer, dimension(:), intent(out), allocatable microstructureAt, integer, dimension(:), intent(out), allocatable homogenizationAt, integer, intent(in) nElem, integer, intent(in) nNodes, character(len=*), dimension(:), intent(in) nameElemSet, integer, dimension(:,:), intent(in) mapElemSet, integer, intent(in) initialcondTableStyle, character(len=*), dimension(:), intent(in) fileContent) private
Stores homogenization and microstructure ID.
Parameters
[in] mapelemset list of elements in elementSet
[in] filecontent file content, separated per lines
Parameters
nNodes number of nodes per element
Definition at line 10721 of file DAMASK_marc.f90.
References continuousintvalues(), io::io_floatvalue(), io::io_intvalue(), io::io_lc(), io::io_stringpos(), io::io_stringvalue(), and mesh_fem2damask_elem.
Referenced by inputread().
inputread_nelemsets()
subroutine discretization_marc::inputread_nelemsets (integer, intent(out) nElemSets, integer, intent(out) maxNelemInSet, character(len=*), dimension(:), intent(in) fileContent) private
Count overall number of element sets in mesh.
Parameters
[in] filecontent file content, separated per lines
Definition at line 10395 of file DAMASK_marc.f90.
References containsrange(), io::io_intvalue(), io::io_lc(), io::io_stringpos(), and io::io_stringvalue().
Referenced by inputread_mapelemsets().
inputread_nnodesandelements()
subroutine discretization_marc::inputread_nnodesandelements (integer, intent(out) nNodes, integer, intent(out) nElems, character(len=*), dimension(:), intent(in) fileContent) private
Count overall number of nodes and elements.
Parameters
[in] filecontent file content, separated per lines
Definition at line 10366 of file DAMASK_marc.f90.
References io::io_intvalue(), io::io_lc(), io::io_stringpos(), and io::io_stringvalue().
Referenced by inputread().
inputread_tablestyles()
subroutine discretization_marc::inputread_tablestyles (integer, intent(out) initialcond, integer, intent(out) hypoelastic, character(len=*), dimension(:), intent(in) fileContent) private
Figures out table styles for initial cond and hypoelastic.
Parameters
[in] filecontent file content, separated per lines
Definition at line 10302 of file DAMASK_marc.f90.
References io::io_intvalue(), io::io_lc(), io::io_stringpos(), and io::io_stringvalue().
Referenced by inputread().
ipareanormal()
real(preal) function, dimension(3,elem%nipneighbors,elem%nips,nelem) discretization_marc::ipareanormal (type(telement), intent(in) elem, integer, intent(in) nElem, integer, dimension(:,:,:), intent(in) connectivity, real(preal), dimension(:,:), intent(in) node) private
calculation of IP interface areas
Definition at line 11046 of file DAMASK_marc.f90.
References math::math_cross().
Referenced by discretization_marc_init().
ipvolume()
real(preal) function, dimension(elem%nips,size(connectivity,3)) discretization_marc::ipvolume (type(telement), intent(in) elem, real(preal), dimension(:,:), intent(in) node, integer, dimension(:,:,:), intent(in) connectivity) private
Calculates IP volume.
The IP volume is calculated differently depending on the cell type. 2D cells assume an element depth of 1.0
Definition at line 10988 of file DAMASK_marc.f90.
References math::math_areatriangle(), math::math_cross(), and math::math_voltetrahedron().
Referenced by discretization_marc_init().
writegeometry()
subroutine discretization_marc::writegeometry (type(telement), intent(in) elem, integer, dimension(:,:), intent(in) connectivity_elem, integer, dimension(:,:), intent(in) connectivity_cell, real(preal), dimension(:,:), intent(in) coordinates_nodes, real(preal), dimension(:,:), intent(in) coordinates_points) private
Write all information needed for the DADF5 geometry.
Definition at line 10170 of file DAMASK_marc.f90.
References results::results_addgroup(), results::results_closegroup(), results::results_closejobfile(), and results::results_openjobfile().
Referenced by discretization_marc_init().
Variable Documentation
cellnodedefinition
type(tcellnodedefinition), dimension(:), allocatable discretization_marc::cellnodedefinition private
Definition at line 10074 of file DAMASK_marc.f90.
Referenced by buildcellnodes(), and discretization_marc_init().
mesh_fem2damask_elem
integer, dimension(:), allocatable, public discretization_marc::mesh_fem2damask_elem
DAMASK element ID for Marc element ID.
Definition at line 10079 of file DAMASK_marc.f90.
Referenced by cpfem_general(), discretization_marc_init(), flux(), hypela2(), inputread(), inputread_connectivityelem(), and inputread_microstructureandhomogenization().
mesh_fem2damask_node
integer, dimension(:), allocatable, public discretization_marc::mesh_fem2damask_node
DAMASK node ID for Marc node ID.
Definition at line 10079 of file DAMASK_marc.f90.
Referenced by inputread(), inputread_connectivityelem(), and inputread_elemnodes().
mesh_unitlength
real(preal), public, protected discretization_marc::mesh_unitlength
physical length of one unit in mesh
Definition at line 10076 of file DAMASK_marc.f90.
Referenced by discretization_marc_init(), and inputread_elemnodes().