DAMASK with MSC.Marc FEM solver: material Module Reference
material Module Reference
Parses material config file, either solverJobName.materialConfig or material.config.
Enumerations
enum {
elasticity_undefined_id, plasticity_undefined_id, source_undefined_id, kinematics_undefined_id,
stiffness_degradation_undefined_id, homogenization_undefined_id
}
Functions/Subroutines
subroutine, public material_init
parses material configuration file
subroutine material_parsehomogenization
parses the homogenization part from the material configuration
subroutine material_parsemicrostructure
parses the microstructure part in the material configuration file
subroutine material_parsephase
parses the phase part in the material configuration file
subroutine material_parsetexture
parses the texture part in the material configuration file
subroutine, public material_allocateplasticstate (phase, NipcMyPhase, sizeState, sizeDotState, sizeDeltaState)
allocates the plastic state of a phase
subroutine, public material_allocatesourcestate (phase, of, NipcMyPhase, sizeState, sizeDotState, sizeDeltaState)
allocates the source state of a phase
Variables
character(len= *), parameter, public elasticity_hooke_label = 'hooke'
character(len= *), parameter, public plasticity_none_label = 'none'
character(len= *), parameter, public plasticity_isotropic_label = 'isotropic'
character(len= *), parameter, public plasticity_phenopowerlaw_label = 'phenopowerlaw'
character(len= *), parameter, public plasticity_kinehardening_label = 'kinehardening'
character(len= *), parameter, public plasticity_dislotwin_label = 'dislotwin'
character(len= *), parameter, public plasticity_disloucla_label = 'disloucla'
character(len= *), parameter, public plasticity_nonlocal_label = 'nonlocal'
character(len= *), parameter, public source_thermal_dissipation_label = 'thermal_dissipation'
character(len= *), parameter, public source_thermal_externalheat_label = 'thermal_externalheat'
character(len= *), parameter, public source_damage_isobrittle_label = 'damage_isobrittle'
character(len= *), parameter, public source_damage_isoductile_label = 'damage_isoductile'
character(len= *), parameter, public source_damage_anisobrittle_label = 'damage_anisobrittle'
character(len= *), parameter, public source_damage_anisoductile_label = 'damage_anisoductile'
character(len= *), parameter, public kinematics_thermal_expansion_label = 'thermal_expansion'
character(len= *), parameter, public kinematics_cleavage_opening_label = 'cleavage_opening'
character(len= *), parameter, public kinematics_slipplane_opening_label = 'slipplane_opening'
character(len= *), parameter, public stiffness_degradation_damage_label = 'damage'
character(len= *), parameter, public thermal_isothermal_label = 'isothermal'
character(len= *), parameter, public thermal_adiabatic_label = 'adiabatic'
character(len= *), parameter, public thermal_conduction_label = 'conduction'
character(len= *), parameter, public damage_none_label = 'none'
character(len= *), parameter, public damage_local_label = 'local'
character(len= *), parameter, public damage_nonlocal_label = 'nonlocal'
character(len= *), parameter, public homogenization_none_label = 'none'
character(len= *), parameter, public homogenization_isostrain_label = 'isostrain'
character(len= *), parameter, public homogenization_rgc_label = 'rgc'
@, public elasticity_hooke_id
@, public plasticity_none_id
@, public plasticity_isotropic_id
@, public plasticity_phenopowerlaw_id
@, public plasticity_kinehardening_id
@, public plasticity_dislotwin_id
@, public plasticity_disloucla_id
@, public plasticity_nonlocal_id
@, public source_thermal_dissipation_id
@, public source_thermal_externalheat_id
@, public source_damage_isobrittle_id
@, public source_damage_isoductile_id
@, public source_damage_anisobrittle_id
@, public source_damage_anisoductile_id
@, public kinematics_cleavage_opening_id
@, public kinematics_slipplane_opening_id
@, public kinematics_thermal_expansion_id
@, public stiffness_degradation_damage_id
@, public thermal_isothermal_id
@, public thermal_adiabatic_id
@, public thermal_conduction_id
@, public damage_none_id
@, public damage_local_id
@, public damage_nonlocal_id
@, public homogenization_none_id
@, public homogenization_isostrain_id
@, public homogenization_rgc_id
integer(kind(elasticity_undefined_id)), dimension(:), allocatable, public, protected phase_elasticity
elasticity of each phase
integer(kind(plasticity_undefined_id)), dimension(:), allocatable, public, protected phase_plasticity
plasticity of each phase
integer(kind(thermal_isothermal_id)), dimension(:), allocatable, public, protected thermal_type
thermal transport model
integer(kind(damage_none_id)), dimension(:), allocatable, public, protected damage_type
nonlocal damage model
integer(kind(homogenization_undefined_id)), dimension(:), allocatable, public, protected homogenization_type
type of each homogenization
integer, public, protected material_nphase
number of phases
integer, public, protected material_nhomogenization
number of homogenizations
integer(kind(source_undefined_id)), dimension(:,:), allocatable, public, protected phase_source
active sources mechanisms of each phase
integer(kind(source_undefined_id)), dimension(:,:), allocatable, public, protected phase_kinematics
active kinematic mechanisms of each phase
integer(kind(source_undefined_id)), dimension(:,:), allocatable, public, protected phase_stiffnessdegradation
active stiffness degradation mechanisms of each phase
integer, public, protected homogenization_maxngrains
max number of grains in any USED homogenization
integer, dimension(:), allocatable, public, protected phase_nsources
number of source mechanisms active in each phase
integer, dimension(:), allocatable, public, protected phase_nkinematics
number of kinematic mechanisms active in each phase
integer, dimension(:), allocatable, public, protected phase_nstiffnessdegradations
number of stiffness degradation mechanisms active in each phase
integer, dimension(:), allocatable, public, protected phase_elasticityinstance
instance of particular elasticity of each phase
integer, dimension(:), allocatable, public, protected phase_plasticityinstance
instance of particular plasticity of each phase
integer, dimension(:), allocatable, public, protected homogenization_ngrains
number of grains in each homogenization
integer, dimension(:), allocatable, public, protected homogenization_typeinstance
instance of particular type of each homogenization
integer, dimension(:), allocatable, public, protected thermal_typeinstance
instance of particular type of each thermal transport
integer, dimension(:), allocatable, public, protected damage_typeinstance
instance of particular type of each nonlocal damage
real(preal), dimension(:), allocatable, public, protected thermal_initialt
initial temperature per each homogenization
real(preal), dimension(:), allocatable, public, protected damage_initialphi
initial damage per each homogenization
integer, dimension(:), allocatable, public, protected material_homogenizationat
homogenization ID of each element (copy of discretization_homogenizationAt)
integer, dimension(:,:), allocatable, target, public material_homogenizationmemberat
position of the element within its homogenization instance
integer, dimension(:,:), allocatable, public, protected material_phaseat
phase ID of each element
integer, dimension(:,:,:), allocatable, public, protected material_phasememberat
position of the element within its phase instance
type(tplasticstate), dimension(:), allocatable, public plasticstate
type(tsourcestate), dimension(:), allocatable, public sourcestate
type(tstate), dimension(:), allocatable, public homogstate
type(tstate), dimension(:), allocatable, public thermalstate
type(tstate), dimension(:), allocatable, public damagestate
integer, dimension(:,:,:), allocatable, public, protected material_texture
texture (index) of each grain,IP,element. Only used by plastic_nonlocal
type(rotation), dimension(:,:,:), allocatable, public, protected material_orientation0
initial orientation of each grain,IP,element
logical, dimension(:), allocatable, public, protected phase_localplasticity
flags phases with local constitutive law
integer, dimension(:), allocatable, private microstructure_nconstituents
number of constituents in each microstructure
integer, dimension(:,:), allocatable, private microstructure_phase
phase IDs of each microstructure
integer, dimension(:,:), allocatable, private microstructure_texture
texture IDs of each microstructure
type(rotation), dimension(:), allocatable, private texture_orientation
Euler angles in material.config (possibly rotated for alignment)
integer, dimension(:,:), allocatable, target, private mappinghomogenizationconst
mapping from material points to offset in constant state/field
type(thomogmapping), dimension(:), allocatable, public thermalmapping
mapping for thermal state/fields
type(thomogmapping), dimension(:), allocatable, public damagemapping
mapping for damage state/fields
type(group_float), dimension(:), allocatable, public temperature
temperature field
type(group_float), dimension(:), allocatable, public damage
damage field
type(group_float), dimension(:), allocatable, public temperaturerate
temperature change rate field
Detailed Description
Parses material config file, either solverJobName.materialConfig or material.config.
Author
Franz Roters, Max-Planck-Institut für Eisenforschung GmbH
Philip Eisenlohr, Max-Planck-Institut für Eisenforschung GmbH
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
Enumeration Type Documentation
anonymous enum
anonymous enum private
Enumerator
elasticity_undefined_id
plasticity_undefined_id
source_undefined_id
kinematics_undefined_id
stiffness_degradation_undefined_id
homogenization_undefined_id
Definition at line 11219 of file DAMASK_marc.f90.
Function/Subroutine Documentation
material_allocateplasticstate()
subroutine, public material::material_allocateplasticstate (integer, intent(in) phase, integer, intent(in) NipcMyPhase, integer, intent(in) sizeState, integer, intent(in) sizeDotState, integer, intent(in) sizeDeltaState)
allocates the plastic state of a phase
Definition at line 11876 of file DAMASK_marc.f90.
References numerics::numerics_integrator, and plasticstate.
material_allocatesourcestate()
subroutine, public material::material_allocatesourcestate (integer, intent(in) phase, integer, intent(in) of, integer, intent(in) NipcMyPhase, integer, intent(in) sizeState, integer, intent(in) sizeDotState, integer, intent(in) sizeDeltaState)
allocates the source state of a phase
Definition at line 11915 of file DAMASK_marc.f90.
References numerics::numerics_integrator, and sourcestate.
Referenced by source_damage_anisobrittle::source_damage_anisobrittle_init(), source_damage_anisoductile::source_damage_anisoductile_init(), source_damage_isobrittle::source_damage_isobrittle_init(), source_damage_isoductile::source_damage_isoductile_init(), source_thermal_dissipation::source_thermal_dissipation_init(), and source_thermal_externalheat::source_thermal_externalheat_init().
material_init()
subroutine, public material::material_init
parses material configuration file
Definition at line 11382 of file DAMASK_marc.f90.
References config::config_deallocate(), config::config_homogenization, config::config_microstructure, config::config_name_homogenization, config::config_name_microstructure, config::config_name_phase, config::config_name_texture, config::config_phase, config::config_texture, damage, damage_initialphi, damagemapping, damagestate, debug::debug_level, debug::debug_levelbasic, debug::debug_levelextensive, debug::debug_material, discretization::discretization_homogenizationat, discretization::discretization_microstructureat, discretization::discretization_nelem, discretization::discretization_nip, homogenization_maxngrains, homogenization_ngrains, homogenization_type, homogstate, io::io_error(), mappinghomogenizationconst, material_homogenizationat, material_homogenizationmemberat, material_nhomogenization, material_nphase, material_orientation0, material_parsehomogenization(), material_parsemicrostructure(), material_parsephase(), material_parsetexture(), material_phaseat, material_phasememberat, material_texture, microstructure_nconstituents, microstructure_phase, microstructure_texture, phase_nsources, plasticstate, results::results_closejobfile(), results::results_mapping_constituent(), results::results_mapping_materialpoint(), results::results_openjobfile(), sourcestate, temperature, temperaturerate, texture_orientation, thermal_initialt, thermalmapping, and thermalstate.
Referenced by cpfem_initall().
material_parsehomogenization()
subroutine material::material_parsehomogenization private
parses the homogenization part from the material configuration
Definition at line 11539 of file DAMASK_marc.f90.
References config::config_homogenization, damage_initialphi, damage_local_id, damage_local_label, damage_none_id, damage_none_label, damage_nonlocal_id, damage_nonlocal_label, damage_type, damage_typeinstance, discretization::discretization_homogenizationat, homogenization_isostrain_id, homogenization_isostrain_label, homogenization_maxngrains, homogenization_ngrains, homogenization_none_id, homogenization_none_label, homogenization_rgc_id, homogenization_rgc_label, homogenization_type, homogenization_typeinstance, homogenization_undefined_id, io::io_error(), thermal_adiabatic_id, thermal_adiabatic_label, thermal_conduction_id, thermal_conduction_label, thermal_initialt, thermal_isothermal_id, thermal_isothermal_label, thermal_type, and thermal_typeinstance.
Referenced by material_init().
material_parsemicrostructure()
subroutine material::material_parsemicrostructure private
parses the microstructure part in the material configuration file
Definition at line 11630 of file DAMASK_marc.f90.
References config::config_microstructure, config::config_name_microstructure, discretization::discretization_microstructureat, prec::dneq(), io::io_error(), io::io_floatvalue(), io::io_intvalue(), io::io_stringpos(), io::io_stringvalue(), microstructure_nconstituents, microstructure_phase, and microstructure_texture.
Referenced by material_init().
material_parsephase()
subroutine material::material_parsephase private
parses the phase part in the material configuration file
Definition at line 11687 of file DAMASK_marc.f90.
References config::config_phase, elasticity_hooke_id, elasticity_hooke_label, elasticity_undefined_id, io::io_error(), kinematics_cleavage_opening_id, kinematics_cleavage_opening_label, kinematics_slipplane_opening_id, kinematics_slipplane_opening_label, kinematics_thermal_expansion_id, kinematics_thermal_expansion_label, kinematics_undefined_id, phase_elasticity, phase_elasticityinstance, phase_kinematics, phase_localplasticity, phase_nkinematics, phase_nsources, phase_nstiffnessdegradations, phase_plasticity, phase_plasticityinstance, phase_source, phase_stiffnessdegradation, plasticity_dislotwin_id, plasticity_dislotwin_label, plasticity_disloucla_id, plasticity_disloucla_label, plasticity_isotropic_id, plasticity_isotropic_label, plasticity_kinehardening_id, plasticity_kinehardening_label, plasticity_none_id, plasticity_none_label, plasticity_nonlocal_id, plasticity_nonlocal_label, plasticity_phenopowerlaw_id, plasticity_phenopowerlaw_label, plasticity_undefined_id, source_damage_anisobrittle_id, source_damage_anisobrittle_label, source_damage_anisoductile_id, source_damage_anisoductile_label, source_damage_isobrittle_id, source_damage_isobrittle_label, source_damage_isoductile_id, source_damage_isoductile_label, source_thermal_dissipation_id, source_thermal_dissipation_label, source_thermal_externalheat_id, source_thermal_externalheat_label, source_undefined_id, stiffness_degradation_damage_id, stiffness_degradation_damage_label, and stiffness_degradation_undefined_id.
Referenced by material_init().
material_parsetexture()
subroutine material::material_parsetexture private
parses the texture part in the material configuration file
Definition at line 11809 of file DAMASK_marc.f90.
References config::config_texture, io::io_error(), io::io_floatvalue(), io::io_stringpos(), io::io_stringvalue(), and texture_orientation.
Referenced by material_init().
Variable Documentation
damage
type(group_float), dimension(:), allocatable, public material::damage
damage field
Definition at line 11339 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_hooke_sanditstangents(), damage_local::damage_local_init(), damage_none::damage_none_init(), damage_nonlocal::damage_nonlocal_init(), and material_init().
damage_initialphi
real(preal), dimension(:), allocatable, public, protected material::damage_initialphi
initial damage per each homogenization
Definition at line 11289 of file DAMASK_marc.f90.
Referenced by damage_local::damage_local_init(), damage_none::damage_none_init(), damage_nonlocal::damage_nonlocal_init(), material_init(), and material_parsehomogenization().
damage_local_id
@, public material::damage_local_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by damage_local::damage_local_init(), homogenization::homogenization_init(), material_parsehomogenization(), and homogenization::updatestate().
damage_local_label
character(len=*), parameter, public material::damage_local_label = 'local'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsehomogenization().
damage_none_id
@, public material::damage_none_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by damage_none::damage_none_init(), homogenization::homogenization_init(), and material_parsehomogenization().
damage_none_label
character(len=*), parameter, public material::damage_none_label = 'none'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsehomogenization().
damage_nonlocal_id
@, public material::damage_nonlocal_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by damage_nonlocal::damage_nonlocal_init(), homogenization::homogenization_init(), and material_parsehomogenization().
damage_nonlocal_label
character(len=*), parameter, public material::damage_nonlocal_label = 'nonlocal'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsehomogenization().
damage_type
integer(kind(damage_none_id)), dimension(:), allocatable, public, protected material::damage_type
nonlocal damage model
Definition at line 11261 of file DAMASK_marc.f90.
Referenced by damage_local::damage_local_init(), damage_none::damage_none_init(), damage_nonlocal::damage_nonlocal_init(), homogenization::homogenization_init(), material_parsehomogenization(), and homogenization::updatestate().
damage_typeinstance
integer, dimension(:), allocatable, public, protected material::damage_typeinstance
instance of particular type of each nonlocal damage
Definition at line 11278 of file DAMASK_marc.f90.
Referenced by damage_local::damage_local_init(), damage_nonlocal::damage_nonlocal_init(), and material_parsehomogenization().
damagemapping
type(thomogmapping), dimension(:), allocatable, public material::damagemapping
mapping for damage state/fields
Definition at line 11335 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_hooke_sanditstangents(), damage_local::damage_local_init(), damage_nonlocal::damage_nonlocal_init(), and material_init().
damagestate
type(tstate), dimension(:), allocatable, public material::damagestate
Definition at line 11306 of file DAMASK_marc.f90.
Referenced by damage_local::damage_local_init(), damage_none::damage_none_init(), damage_nonlocal::damage_nonlocal_init(), material_init(), and homogenization::materialpoint_stressanditstangent().
elasticity_hooke_id
@, public material::elasticity_hooke_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by material_parsephase().
elasticity_hooke_label
character(len=*), parameter, public material::elasticity_hooke_label = 'hooke'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase().
homogenization_isostrain_id
@, public material::homogenization_isostrain_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by homogenization::averagestressanditstangent(), material_parsehomogenization(), and homogenization::partitiondeformation().
homogenization_isostrain_label
character(len=*), parameter, public material::homogenization_isostrain_label = 'isostrain'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsehomogenization().
homogenization_maxngrains
integer, public, protected material::homogenization_maxngrains
max number of grains in any USED homogenization
Definition at line 11275 of file DAMASK_marc.f90.
Referenced by crystallite_init(), material_init(), material_parsehomogenization(), and select_rotations().
homogenization_ngrains
integer, dimension(:), allocatable, public, protected material::homogenization_ngrains
number of grains in each homogenization
Definition at line 11278 of file DAMASK_marc.f90.
Referenced by homogenization::averagestressanditstangent(), crystallite_init(), crystallite_orientations(), crystallite_stress(), crystallite_stresstangent(), homogenization::homogenization_init(), integratestatefpi(), material_init(), material_parsehomogenization(), homogenization::materialpoint_stressanditstangent(), homogenization::partitiondeformation(), and homogenization::updatestate().
homogenization_none_id
@, public material::homogenization_none_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by homogenization::averagestressanditstangent(), material_parsehomogenization(), and homogenization::partitiondeformation().
homogenization_none_label
character(len=*), parameter, public material::homogenization_none_label = 'none'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsehomogenization().
homogenization_rgc_id
@, public material::homogenization_rgc_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by homogenization::averagestressanditstangent(), material_parsehomogenization(), homogenization::partitiondeformation(), and homogenization::updatestate().
homogenization_rgc_label
character(len=*), parameter, public material::homogenization_rgc_label = 'rgc'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsehomogenization().
homogenization_type
integer(kind(homogenization_undefined_id)), dimension(:), allocatable, public, protected material::homogenization_type
type of each homogenization
Definition at line 11263 of file DAMASK_marc.f90.
Referenced by homogenization::averagestressanditstangent(), material_init(), material_parsehomogenization(), homogenization::materialpoint_stressanditstangent(), and homogenization::updatestate().
homogenization_typeinstance
integer, dimension(:), allocatable, public, protected material::homogenization_typeinstance
instance of particular type of each homogenization
Definition at line 11278 of file DAMASK_marc.f90.
Referenced by homogenization::averagestressanditstangent(), and material_parsehomogenization().
homogstate
type(tstate), dimension(:), allocatable, public material::homogstate
Definition at line 11306 of file DAMASK_marc.f90.
Referenced by material_init(), and homogenization::materialpoint_stressanditstangent().
kinematics_cleavage_opening_id
@, public material::kinematics_cleavage_opening_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_init(), constitutive::constitutive_lianditstangents(), kinematics_cleavage_opening::kinematics_cleavage_opening_init(), and material_parsephase().
kinematics_cleavage_opening_label
character(len=*), parameter, public material::kinematics_cleavage_opening_label = 'cleavage_opening'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by kinematics_cleavage_opening::kinematics_cleavage_opening_init(), and material_parsephase().
kinematics_slipplane_opening_id
@, public material::kinematics_slipplane_opening_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_init(), constitutive::constitutive_lianditstangents(), kinematics_slipplane_opening::kinematics_slipplane_opening_init(), and material_parsephase().
kinematics_slipplane_opening_label
character(len=*), parameter, public material::kinematics_slipplane_opening_label = 'slipplane_opening'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by kinematics_slipplane_opening::kinematics_slipplane_opening_init(), and material_parsephase().
kinematics_thermal_expansion_id
@, public material::kinematics_thermal_expansion_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_init(), constitutive::constitutive_initialfi(), constitutive::constitutive_lianditstangents(), kinematics_thermal_expansion::kinematics_thermal_expansion_init(), and material_parsephase().
kinematics_thermal_expansion_label
character(len=*), parameter, public material::kinematics_thermal_expansion_label = 'thermal_expansion'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by kinematics_thermal_expansion::kinematics_thermal_expansion_init(), and material_parsephase().
mappinghomogenizationconst
integer, dimension(:,:), allocatable, target, private material::mappinghomogenizationconst private
mapping from material points to offset in constant state/field
Definition at line 11332 of file DAMASK_marc.f90.
Referenced by material_init().
material_homogenizationat
integer, dimension(:), allocatable, public, protected material::material_homogenizationat
homogenization ID of each element (copy of discretization_homogenizationAt)
Definition at line 11293 of file DAMASK_marc.f90.
Referenced by homogenization::averagestressanditstangent(), constitutive::constitutive_collectdotstate(), constitutive::constitutive_dependentstate(), constitutive::constitutive_hooke_sanditstangents(), constitutive::constitutive_initialfi(), constitutive::constitutive_lpanditstangents(), cpfem_general(), crystallite_init(), crystallite_orientations(), crystallite_stress(), crystallite_stresstangent(), damage_local::damage_local_init(), damage_none::damage_none_init(), damage_nonlocal::damage_nonlocal_init(), homogenization::homogenization_init(), integratestatefpi(), material_init(), homogenization::materialpoint_stressanditstangent(), homogenization::partitiondeformation(), thermal_adiabatic::thermal_adiabatic_init(), thermal_conduction::thermal_conduction_init(), thermal_isothermal::thermal_isothermal_init(), and homogenization::updatestate().
material_homogenizationmemberat
integer, dimension(:,:), allocatable, target, public material::material_homogenizationmemberat
position of the element within its homogenization instance
Definition at line 11295 of file DAMASK_marc.f90.
Referenced by damage_local::damage_local_init(), damage_nonlocal::damage_nonlocal_init(), material_init(), homogenization::materialpoint_stressanditstangent(), thermal_adiabatic::thermal_adiabatic_init(), and thermal_conduction::thermal_conduction_init().
material_nhomogenization
integer, public, protected material::material_nhomogenization
number of homogenizations
Definition at line 11266 of file DAMASK_marc.f90.
Referenced by material_init().
material_nphase
integer, public, protected material::material_nphase
number of phases
Definition at line 11266 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_init(), and material_init().
material_orientation0
type(rotation), dimension(:,:,:), allocatable, public, protected material::material_orientation0
initial orientation of each grain,IP,element
Definition at line 11314 of file DAMASK_marc.f90.
Referenced by crystallite_init(), crystallite_push33toref(), and material_init().
material_phaseat
integer, dimension(:,:), allocatable, public, protected material::material_phaseat
phase ID of each element
Definition at line 11297 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdeltastate(), constitutive::constitutive_collectdotstate(), constitutive::constitutive_dependentstate(), constitutive::constitutive_homogenizedc(), constitutive::constitutive_hooke_sanditstangents(), constitutive::constitutive_initialfi(), constitutive::constitutive_lianditstangents(), constitutive::constitutive_lpanditstangents(), crystallite_init(), crystallite_orientations(), crystallite_stress(), integratestatefpi(), material_init(), homogenization::materialpoint_stressanditstangent(), select_rotations(), select_tensors(), source_damage_anisobrittle::source_damage_anisobrittle_init(), source_damage_anisoductile::source_damage_anisoductile_init(), source_damage_isobrittle::source_damage_isobrittle_init(), source_damage_isoductile::source_damage_isoductile_init(), source_thermal_dissipation::source_thermal_dissipation_init(), and source_thermal_externalheat::source_thermal_externalheat_init().
material_phasememberat
integer, dimension(:,:,:), allocatable, public, protected material::material_phasememberat
position of the element within its phase instance
Definition at line 11299 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdeltastate(), constitutive::constitutive_collectdotstate(), constitutive::constitutive_dependentstate(), constitutive::constitutive_lianditstangents(), constitutive::constitutive_lpanditstangents(), crystallite_stress(), integratestatefpi(), material_init(), and homogenization::materialpoint_stressanditstangent().
material_texture
integer, dimension(:,:,:), allocatable, public, protected material::material_texture
texture (index) of each grain,IP,element. Only used by plastic_nonlocal
Definition at line 11311 of file DAMASK_marc.f90.
Referenced by material_init().
microstructure_nconstituents
integer, dimension(:), allocatable, private material::microstructure_nconstituents private
number of constituents in each microstructure
Definition at line 11320 of file DAMASK_marc.f90.
Referenced by material_init(), and material_parsemicrostructure().
microstructure_phase
integer, dimension(:,:), allocatable, private material::microstructure_phase private
phase IDs of each microstructure
Definition at line 11323 of file DAMASK_marc.f90.
Referenced by material_init(), and material_parsemicrostructure().
microstructure_texture
integer, dimension(:,:), allocatable, private material::microstructure_texture private
texture IDs of each microstructure
Definition at line 11323 of file DAMASK_marc.f90.
Referenced by material_init(), and material_parsemicrostructure().
phase_elasticity
integer(kind(elasticity_undefined_id)), dimension(:), allocatable, public, protected material::phase_elasticity
elasticity of each phase
Definition at line 11255 of file DAMASK_marc.f90.
Referenced by material_parsephase().
phase_elasticityinstance
integer, dimension(:), allocatable, public, protected material::phase_elasticityinstance
instance of particular elasticity of each phase
Definition at line 11278 of file DAMASK_marc.f90.
Referenced by material_parsephase().
phase_kinematics
integer(kind(source_undefined_id)), dimension(:,:), allocatable, public, protected material::phase_kinematics
active kinematic mechanisms of each phase
Definition at line 11270 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_init(), constitutive::constitutive_initialfi(), constitutive::constitutive_lianditstangents(), kinematics_cleavage_opening::kinematics_cleavage_opening_init(), kinematics_slipplane_opening::kinematics_slipplane_opening_init(), kinematics_thermal_expansion::kinematics_thermal_expansion_init(), and material_parsephase().
phase_localplasticity
logical, dimension(:), allocatable, public, protected material::phase_localplasticity
flags phases with local constitutive law
Definition at line 11317 of file DAMASK_marc.f90.
Referenced by crystallite_init(), and material_parsephase().
phase_nkinematics
integer, dimension(:), allocatable, public, protected material::phase_nkinematics
number of kinematic mechanisms active in each phase
Definition at line 11278 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_initialfi(), constitutive::constitutive_lianditstangents(), and material_parsephase().
phase_nsources
integer, dimension(:), allocatable, public, protected material::phase_nsources
number of source mechanisms active in each phase
Definition at line 11278 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdeltastate(), constitutive::constitutive_collectdotstate(), constitutive::constitutive_init(), crystallite_stress(), integratestatefpi(), material_init(), material_parsephase(), homogenization::materialpoint_stressanditstangent(), source_damage_anisobrittle::source_damage_anisobrittle_init(), source_damage_anisoductile::source_damage_anisoductile_init(), source_damage_isobrittle::source_damage_isobrittle_init(), source_damage_isoductile::source_damage_isoductile_init(), source_thermal_dissipation::source_thermal_dissipation_init(), and source_thermal_externalheat::source_thermal_externalheat_init().
phase_nstiffnessdegradations
integer, dimension(:), allocatable, public, protected material::phase_nstiffnessdegradations
number of stiffness degradation mechanisms active in each phase
Definition at line 11278 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_hooke_sanditstangents(), and material_parsephase().
phase_plasticity
integer(kind(plasticity_undefined_id)), dimension(:), allocatable, public, protected material::phase_plasticity
plasticity of each phase
Definition at line 11257 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdeltastate(), constitutive::constitutive_collectdotstate(), constitutive::constitutive_dependentstate(), constitutive::constitutive_homogenizedc(), constitutive::constitutive_init(), constitutive::constitutive_lianditstangents(), constitutive::constitutive_lpanditstangents(), constitutive::constitutive_results(), and material_parsephase().
phase_plasticityinstance
integer, dimension(:), allocatable, public, protected material::phase_plasticityinstance
instance of particular plasticity of each phase
Definition at line 11278 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdeltastate(), constitutive::constitutive_collectdotstate(), constitutive::constitutive_dependentstate(), constitutive::constitutive_lianditstangents(), constitutive::constitutive_lpanditstangents(), constitutive::constitutive_results(), crystallite_orientations(), and material_parsephase().
phase_source
integer(kind(source_undefined_id)), dimension(:,:), allocatable, public, protected material::phase_source
active sources mechanisms of each phase
Definition at line 11270 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdeltastate(), constitutive::constitutive_collectdotstate(), constitutive::constitutive_init(), material_parsephase(), source_damage_anisobrittle::source_damage_anisobrittle_init(), source_damage_anisoductile::source_damage_anisoductile_init(), source_damage_isobrittle::source_damage_isobrittle_init(), source_damage_isoductile::source_damage_isoductile_init(), source_thermal_dissipation::source_thermal_dissipation_init(), and source_thermal_externalheat::source_thermal_externalheat_init().
phase_stiffnessdegradation
integer(kind(source_undefined_id)), dimension(:,:), allocatable, public, protected material::phase_stiffnessdegradation
active stiffness degradation mechanisms of each phase
Definition at line 11270 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_hooke_sanditstangents(), and material_parsephase().
plasticity_dislotwin_id
@, public material::plasticity_dislotwin_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdotstate(), constitutive::constitutive_dependentstate(), constitutive::constitutive_homogenizedc(), constitutive::constitutive_init(), constitutive::constitutive_lpanditstangents(), constitutive::constitutive_results(), and material_parsephase().
plasticity_dislotwin_label
character(len=*), parameter, public material::plasticity_dislotwin_label = 'dislotwin'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase().
plasticity_disloucla_id
@, public material::plasticity_disloucla_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdotstate(), constitutive::constitutive_dependentstate(), constitutive::constitutive_init(), constitutive::constitutive_lpanditstangents(), constitutive::constitutive_results(), and material_parsephase().
plasticity_disloucla_label
character(len=*), parameter, public material::plasticity_disloucla_label = 'disloucla'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase().
plasticity_isotropic_id
@, public material::plasticity_isotropic_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdotstate(), constitutive::constitutive_init(), constitutive::constitutive_lianditstangents(), constitutive::constitutive_lpanditstangents(), constitutive::constitutive_results(), and material_parsephase().
plasticity_isotropic_label
character(len=*), parameter, public material::plasticity_isotropic_label = 'isotropic'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase().
plasticity_kinehardening_id
@, public material::plasticity_kinehardening_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdeltastate(), constitutive::constitutive_collectdotstate(), constitutive::constitutive_init(), constitutive::constitutive_lpanditstangents(), constitutive::constitutive_results(), and material_parsephase().
plasticity_kinehardening_label
character(len=*), parameter, public material::plasticity_kinehardening_label = 'kinehardening'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase().
plasticity_none_id
@, public material::plasticity_none_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_init(), constitutive::constitutive_lpanditstangents(), and material_parsephase().
plasticity_none_label
character(len=*), parameter, public material::plasticity_none_label = 'none'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase().
plasticity_nonlocal_id
@, public material::plasticity_nonlocal_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdeltastate(), constitutive::constitutive_collectdotstate(), constitutive::constitutive_dependentstate(), constitutive::constitutive_init(), constitutive::constitutive_lpanditstangents(), constitutive::constitutive_results(), and material_parsephase().
plasticity_nonlocal_label
character(len=*), parameter, public material::plasticity_nonlocal_label = 'nonlocal'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase().
plasticity_phenopowerlaw_id
@, public material::plasticity_phenopowerlaw_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdotstate(), constitutive::constitutive_init(), constitutive::constitutive_lpanditstangents(), constitutive::constitutive_results(), and material_parsephase().
plasticity_phenopowerlaw_label
character(len=*), parameter, public material::plasticity_phenopowerlaw_label = 'phenopowerlaw'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase().
plasticstate
type(tplasticstate), dimension(:), allocatable, public material::plasticstate
Definition at line 11302 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_init(), crystallite_orientations(), crystallite_stress(), integratestatefpi(), material_allocateplasticstate(), material_init(), and homogenization::materialpoint_stressanditstangent().
source_damage_anisobrittle_id
@, public material::source_damage_anisobrittle_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdotstate(), constitutive::constitutive_init(), material_parsephase(), and source_damage_anisobrittle::source_damage_anisobrittle_init().
source_damage_anisobrittle_label
character(len=*), parameter, public material::source_damage_anisobrittle_label = 'damage_anisobrittle'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase(), and source_damage_anisobrittle::source_damage_anisobrittle_init().
source_damage_anisoductile_id
@, public material::source_damage_anisoductile_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdotstate(), constitutive::constitutive_init(), material_parsephase(), and source_damage_anisoductile::source_damage_anisoductile_init().
source_damage_anisoductile_label
character(len=*), parameter, public material::source_damage_anisoductile_label = 'damage_anisoductile'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase(), and source_damage_anisoductile::source_damage_anisoductile_init().
source_damage_isobrittle_id
@, public material::source_damage_isobrittle_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdeltastate(), constitutive::constitutive_init(), material_parsephase(), and source_damage_isobrittle::source_damage_isobrittle_init().
source_damage_isobrittle_label
character(len=*), parameter, public material::source_damage_isobrittle_label = 'damage_isobrittle'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase(), and source_damage_isobrittle::source_damage_isobrittle_init().
source_damage_isoductile_id
@, public material::source_damage_isoductile_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdotstate(), constitutive::constitutive_init(), material_parsephase(), and source_damage_isoductile::source_damage_isoductile_init().
source_damage_isoductile_label
character(len=*), parameter, public material::source_damage_isoductile_label = 'damage_isoductile'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase(), and source_damage_isoductile::source_damage_isoductile_init().
source_thermal_dissipation_id
@, public material::source_thermal_dissipation_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_init(), material_parsephase(), and source_thermal_dissipation::source_thermal_dissipation_init().
source_thermal_dissipation_label
character(len=*), parameter, public material::source_thermal_dissipation_label = 'thermal_dissipation'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase(), and source_thermal_dissipation::source_thermal_dissipation_init().
source_thermal_externalheat_id
@, public material::source_thermal_externalheat_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdotstate(), constitutive::constitutive_init(), material_parsephase(), and source_thermal_externalheat::source_thermal_externalheat_init().
source_thermal_externalheat_label
character(len=*), parameter, public material::source_thermal_externalheat_label = 'thermal_externalheat'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase(), and source_thermal_externalheat::source_thermal_externalheat_init().
sourcestate
type(tsourcestate), dimension(:), allocatable, public material::sourcestate
Definition at line 11304 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_init(), crystallite_stress(), integratestatefpi(), material_allocatesourcestate(), material_init(), homogenization::materialpoint_stressanditstangent(), source_damage_anisobrittle::source_damage_anisobrittle_init(), source_damage_anisoductile::source_damage_anisoductile_init(), source_damage_isobrittle::source_damage_isobrittle_init(), and source_damage_isoductile::source_damage_isoductile_init().
stiffness_degradation_damage_id
@, public material::stiffness_degradation_damage_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_hooke_sanditstangents(), and material_parsephase().
stiffness_degradation_damage_label
character(len=*), parameter, public material::stiffness_degradation_damage_label = 'damage'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsephase().
temperature
type(group_float), dimension(:), allocatable, public material::temperature
temperature field
Definition at line 11339 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdotstate(), constitutive::constitutive_dependentstate(), constitutive::constitutive_lpanditstangents(), cpfem_general(), material_init(), thermal_adiabatic::thermal_adiabatic_init(), thermal_conduction::thermal_conduction_init(), and thermal_isothermal::thermal_isothermal_init().
temperaturerate
type(group_float), dimension(:), allocatable, public material::temperaturerate
temperature change rate field
Definition at line 11339 of file DAMASK_marc.f90.
Referenced by material_init(), thermal_adiabatic::thermal_adiabatic_init(), thermal_conduction::thermal_conduction_init(), and thermal_isothermal::thermal_isothermal_init().
texture_orientation
type(rotation), dimension(:), allocatable, private material::texture_orientation private
Euler angles in material.config (possibly rotated for alignment)
Definition at line 11327 of file DAMASK_marc.f90.
Referenced by material_init(), and material_parsetexture().
thermal_adiabatic_id
@, public material::thermal_adiabatic_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by homogenization::homogenization_init(), material_parsehomogenization(), thermal_adiabatic::thermal_adiabatic_init(), and homogenization::updatestate().
thermal_adiabatic_label
character(len=*), parameter, public material::thermal_adiabatic_label = 'adiabatic'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsehomogenization().
thermal_conduction_id
@, public material::thermal_conduction_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by cpfem_general(), homogenization::homogenization_init(), material_parsehomogenization(), and thermal_conduction::thermal_conduction_init().
thermal_conduction_label
character(len=*), parameter, public material::thermal_conduction_label = 'conduction'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsehomogenization().
thermal_initialt
real(preal), dimension(:), allocatable, public, protected material::thermal_initialt
initial temperature per each homogenization
Definition at line 11289 of file DAMASK_marc.f90.
Referenced by material_init(), material_parsehomogenization(), thermal_adiabatic::thermal_adiabatic_init(), thermal_conduction::thermal_conduction_init(), and thermal_isothermal::thermal_isothermal_init().
thermal_isothermal_id
@, public material::thermal_isothermal_id
Definition at line 11252 of file DAMASK_marc.f90.
Referenced by material_parsehomogenization(), and thermal_isothermal::thermal_isothermal_init().
thermal_isothermal_label
character(len=*), parameter, public material::thermal_isothermal_label = 'isothermal'
Definition at line 11190 of file DAMASK_marc.f90.
Referenced by material_parsehomogenization().
thermal_type
integer(kind(thermal_isothermal_id)), dimension(:), allocatable, public, protected material::thermal_type
thermal transport model
Definition at line 11259 of file DAMASK_marc.f90.
Referenced by cpfem_general(), homogenization::homogenization_init(), material_parsehomogenization(), thermal_adiabatic::thermal_adiabatic_init(), thermal_conduction::thermal_conduction_init(), thermal_isothermal::thermal_isothermal_init(), and homogenization::updatestate().
thermal_typeinstance
integer, dimension(:), allocatable, public, protected material::thermal_typeinstance
instance of particular type of each thermal transport
Definition at line 11278 of file DAMASK_marc.f90.
Referenced by material_parsehomogenization(), thermal_adiabatic::thermal_adiabatic_init(), and thermal_conduction::thermal_conduction_init().
thermalmapping
type(thomogmapping), dimension(:), allocatable, public material::thermalmapping
mapping for thermal state/fields
Definition at line 11335 of file DAMASK_marc.f90.
Referenced by constitutive::constitutive_collectdotstate(), constitutive::constitutive_dependentstate(), constitutive::constitutive_initialfi(), constitutive::constitutive_lpanditstangents(), cpfem_general(), material_init(), thermal_adiabatic::thermal_adiabatic_init(), and thermal_conduction::thermal_conduction_init().
thermalstate
type(tstate), dimension(:), allocatable, public material::thermalstate
Definition at line 11306 of file DAMASK_marc.f90.
Referenced by material_init(), homogenization::materialpoint_stressanditstangent(), thermal_adiabatic::thermal_adiabatic_init(), thermal_conduction::thermal_conduction_init(), and thermal_isothermal::thermal_isothermal_init().