DAMASK with MSC.Marc FEM solver: thermal_adiabatic Module Reference
thermal_adiabatic Module Reference
material subroutine for adiabatic temperature evolution
Data Types
type tparameters
Functions/Subroutines
subroutine, public thermal_adiabatic_init
module initialization
logical function, dimension(2), public thermal_adiabatic_updatestate (subdt, ip, el)
calculates adiabatic change in temperature based on local heat generation model
subroutine, public thermal_adiabatic_getsourceanditstangent (Tdot, dTdot_dT, T, ip, el)
returns heat generation rate
real(preal) function, public thermal_adiabatic_getspecificheat (ip, el)
returns homogenized specific heat capacity
real(preal) function, public thermal_adiabatic_getmassdensity (ip, el)
returns homogenized mass density
subroutine, public thermal_adiabatic_results (homog, group)
writes results to HDF5 output file
Variables
type(tparameters), dimension(:), allocatable param
Detailed Description
material subroutine for adiabatic temperature evolution
Author
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
thermal_adiabatic_getmassdensity()
real(preal) function, public thermal_adiabatic::thermal_adiabatic_getmassdensity (integer, intent(in) ip, integer, intent(in) el)
returns homogenized mass density
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 23515 of file DAMASK_marc.f90.
Referenced by thermal_adiabatic_updatestate().
thermal_adiabatic_getsourceanditstangent()
subroutine, public thermal_adiabatic::thermal_adiabatic_getsourceanditstangent (real(preal), intent(out) Tdot, real(preal), intent(out) dTdot_dT, real(preal), intent(in) T, integer, intent(in) ip, integer, intent(in) el)
returns heat generation rate
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 23430 of file DAMASK_marc.f90.
Referenced by thermal_adiabatic_updatestate().
thermal_adiabatic_getspecificheat()
real(preal) function, public thermal_adiabatic::thermal_adiabatic_getspecificheat (integer, intent(in) ip, integer, intent(in) el)
returns homogenized specific heat capacity
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 23488 of file DAMASK_marc.f90.
Referenced by thermal_adiabatic_updatestate().
thermal_adiabatic_init()
subroutine, public thermal_adiabatic::thermal_adiabatic_init
module initialization
reads in material parameters, allocates arrays, and does sanity checks
Definition at line 23353 of file DAMASK_marc.f90.
References config::config_homogenization, prec::emptystringarray, material::material_homogenizationat, material::material_homogenizationmemberat, material::temperature, material::temperaturerate, material::thermal_adiabatic_id, material::thermal_initialt, material::thermal_type, material::thermal_typeinstance, material::thermalmapping, and material::thermalstate.
Referenced by homogenization::homogenization_init().
thermal_adiabatic_results()
subroutine, public thermal_adiabatic::thermal_adiabatic_results (integer, intent(in) homog, character(len=*), intent(in) group)
writes results to HDF5 output file
Definition at line 23541 of file DAMASK_marc.f90.
References param.
Referenced by homogenization::homogenization_results().
thermal_adiabatic_updatestate()
logical function, dimension(2), public thermal_adiabatic::thermal_adiabatic_updatestate (real(preal), intent(in) subdt, integer, intent(in) ip, integer, intent(in) el)
calculates adiabatic change in temperature based on local heat generation model
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 23391 of file DAMASK_marc.f90.
References thermal_adiabatic_getmassdensity(), thermal_adiabatic_getsourceanditstangent(), and thermal_adiabatic_getspecificheat().
Referenced by homogenization::updatestate().
Variable Documentation
param
type(tparameters), dimension(:), allocatable thermal_adiabatic::param private
Definition at line 23334 of file DAMASK_marc.f90.
Referenced by thermal_adiabatic_results().