DAMASK with MSC.Marc FEM solver: hdf5_utilities Module Reference
hdf5_utilities Module Reference
Data Types
interface hdf5_addattribute
attached attributes of type char, integer or real to a file/dataset/group
interface hdf5_read
reads integer or float data of defined shape from file ! ToDo: order of arguments wrong
interface hdf5_write
writes integer or real data of defined shape to file ! ToDo: order of arguments wrong
Functions/Subroutines
subroutine hdf5_utilities_init
open libary and do sanity checks
integer(hid_t) function hdf5_openfile (fileName, mode, parallel)
open and initializes HDF5 output file
subroutine hdf5_closefile (fileHandle)
close the opened HDF5 output file
integer(hid_t) function hdf5_addgroup (fileHandle, groupName)
adds a new group to the fileHandle
integer(hid_t) function hdf5_opengroup (fileHandle, groupName)
open an existing group of a file
subroutine hdf5_closegroup (group_id)
close a group
logical function hdf5_objectexists (loc_id, path)
check whether a group or a dataset exists
subroutine hdf5_addattribute_str (loc_id, attrLabel, attrValue, path)
adds a string attribute to the path given relative to the location
subroutine hdf5_addattribute_int (loc_id, attrLabel, attrValue, path)
adds a integer attribute to the path given relative to the location
subroutine hdf5_addattribute_real (loc_id, attrLabel, attrValue, path)
adds a integer attribute to the path given relative to the location
subroutine hdf5_addattribute_int_array (loc_id, attrLabel, attrValue, path)
adds a integer attribute to the path given relative to the location
subroutine hdf5_addattribute_real_array (loc_id, attrLabel, attrValue, path)
adds a real attribute to the path given relative to the location
subroutine hdf5_setlink (loc_id, target_name, link_name)
set link to object in results file
subroutine hdf5_read_real1 (loc_id, dataset, datasetName, parallel)
read dataset of type real with 1 dimension
subroutine hdf5_read_real2 (loc_id, dataset, datasetName, parallel)
read dataset of type real with 2 dimensions
subroutine hdf5_read_real3 (loc_id, dataset, datasetName, parallel)
read dataset of type real with 2 dimensions
subroutine hdf5_read_real4 (loc_id, dataset, datasetName, parallel)
read dataset of type real with 4 dimensions
subroutine hdf5_read_real5 (loc_id, dataset, datasetName, parallel)
read dataset of type real with 5 dimensions
subroutine hdf5_read_real6 (loc_id, dataset, datasetName, parallel)
read dataset of type real with 6 dimensions
subroutine hdf5_read_real7 (loc_id, dataset, datasetName, parallel)
read dataset of type real with 7 dimensions
subroutine hdf5_read_int1 (loc_id, dataset, datasetName, parallel)
read dataset of type integer with 1 dimension
subroutine hdf5_read_int2 (loc_id, dataset, datasetName, parallel)
read dataset of type integer with 2 dimensions
subroutine hdf5_read_int3 (loc_id, dataset, datasetName, parallel)
read dataset of type integer with 3 dimensions
subroutine hdf5_read_int4 (loc_id, dataset, datasetName, parallel)
read dataset of type integer withh 4 dimensions
subroutine hdf5_read_int5 (loc_id, dataset, datasetName, parallel)
read dataset of type integer with 5 dimensions
subroutine hdf5_read_int6 (loc_id, dataset, datasetName, parallel)
read dataset of type integer with 6 dimensions
subroutine hdf5_read_int7 (loc_id, dataset, datasetName, parallel)
read dataset of type integer with 7 dimensions
subroutine hdf5_write_real1 (loc_id, dataset, datasetName, parallel)
write dataset of type real with 1 dimension
subroutine hdf5_write_real2 (loc_id, dataset, datasetName, parallel)
write dataset of type real with 2 dimensions
subroutine hdf5_write_real3 (loc_id, dataset, datasetName, parallel)
write dataset of type real with 3 dimensions
subroutine hdf5_write_real4 (loc_id, dataset, datasetName, parallel)
write dataset of type real with 4 dimensions
subroutine hdf5_write_real5 (loc_id, dataset, datasetName, parallel)
write dataset of type real with 5 dimensions
subroutine hdf5_write_real6 (loc_id, dataset, datasetName, parallel)
write dataset of type real with 6 dimensions
subroutine hdf5_write_real7 (loc_id, dataset, datasetName, parallel)
write dataset of type real with 7 dimensions
subroutine hdf5_write_int1 (loc_id, dataset, datasetName, parallel)
write dataset of type integer with 1 dimension
subroutine hdf5_write_int2 (loc_id, dataset, datasetName, parallel)
write dataset of type integer with 2 dimensions
subroutine hdf5_write_int3 (loc_id, dataset, datasetName, parallel)
write dataset of type integer with 3 dimensions
subroutine hdf5_write_int4 (loc_id, dataset, datasetName, parallel)
write dataset of type integer with 4 dimensions
subroutine hdf5_write_int5 (loc_id, dataset, datasetName, parallel)
write dataset of type integer with 5 dimensions
subroutine hdf5_write_int6 (loc_id, dataset, datasetName, parallel)
write dataset of type integer with 6 dimensions
subroutine hdf5_write_int7 (loc_id, dataset, datasetName, parallel)
write dataset of type integer with 7 dimensions
subroutine hdf5_write_rotation (loc_id, dataset, datasetName, parallel)
writes a scalar orientation dataset
subroutine initialize_read (dset_id, filespace_id, memspace_id, plist_id, aplist_id, myStart, globalShape, loc_id, localShape, datasetName, parallel)
initialize HDF5 handles, determines global shape and start for parallel read
subroutine finalize_read (dset_id, filespace_id, memspace_id, plist_id, aplist_id)
closes HDF5 handles
subroutine initialize_write (dset_id, filespace_id, memspace_id, plist_id, myStart, totalShape, loc_id, myShape, datasetName, datatype, parallel)
initialize HDF5 handles, determines global shape and start for parallel write
subroutine finalize_write (plist_id, dset_id, filespace_id, memspace_id)
closes HDF5 handles
Detailed Description
Author
Vitesh Shah, Max-Planck-Institut für Eisenforschung GmbH
Yi-Chin Yang, Max-Planck-Institut für Eisenforschung GmbH
Jennifer Nastola, Max-Planck-Institut für Eisenforschung GmbH
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
finalize_read()
subroutine hdf5_utilities::finalize_read (integer(hid_t), intent(in) dset_id, integer(hid_t), intent(in) filespace_id, integer(hid_t), intent(in) memspace_id, integer(hid_t), intent(in) plist_id, integer(hid_t), intent(in) aplist_id)
closes HDF5 handles
Definition at line 8665 of file DAMASK_marc.f90.
References io::io_error().
Referenced by hdf5_read_int1(), hdf5_read_int2(), hdf5_read_int3(), hdf5_read_int4(), hdf5_read_int5(), hdf5_read_int6(), hdf5_read_int7(), hdf5_read_real1(), hdf5_read_real2(), hdf5_read_real3(), hdf5_read_real4(), hdf5_read_real5(), hdf5_read_real6(), and hdf5_read_real7().
finalize_write()
subroutine hdf5_utilities::finalize_write (integer(hid_t), intent(in) plist_id, integer(hid_t), intent(in) dset_id, integer(hid_t), intent(in) filespace_id, integer(hid_t), intent(in) memspace_id)
closes HDF5 handles
Definition at line 8752 of file DAMASK_marc.f90.
References io::io_error().
Referenced by hdf5_write_int1(), hdf5_write_int2(), hdf5_write_int3(), hdf5_write_int4(), hdf5_write_int5(), hdf5_write_int6(), hdf5_write_int7(), hdf5_write_real1(), hdf5_write_real2(), hdf5_write_real3(), hdf5_write_real4(), hdf5_write_real5(), hdf5_write_real6(), hdf5_write_real7(), and hdf5_write_rotation().
hdf5_addattribute_int()
subroutine hdf5_utilities::hdf5_addattribute_int (integer(hid_t), intent(in) loc_id, character(len=*), intent(in) attrLabel, integer, intent(in) attrValue, character(len=*), intent(in), optional path)
adds a integer attribute to the path given relative to the location
Definition at line 7193 of file DAMASK_marc.f90.
References io::io_error().
hdf5_addattribute_int_array()
subroutine hdf5_utilities::hdf5_addattribute_int_array (integer(hid_t), intent(in) loc_id, character(len=*), intent(in) attrLabel, integer, dimension(:), intent(in) attrValue, character(len=*), intent(in), optional path)
adds a integer attribute to the path given relative to the location
Definition at line 7275 of file DAMASK_marc.f90.
References io::io_error().
hdf5_addattribute_real()
subroutine hdf5_utilities::hdf5_addattribute_real (integer(hid_t), intent(in) loc_id, character(len=*), intent(in) attrLabel, real(preal), intent(in) attrValue, character(len=*), intent(in), optional path)
adds a integer attribute to the path given relative to the location
Definition at line 7234 of file DAMASK_marc.f90.
References io::io_error().
hdf5_addattribute_real_array()
subroutine hdf5_utilities::hdf5_addattribute_real_array (integer(hid_t), intent(in) loc_id, character(len=*), intent(in) attrLabel, real(preal), dimension(:), intent(in) attrValue, character(len=*), intent(in), optional path)
adds a real attribute to the path given relative to the location
Definition at line 7319 of file DAMASK_marc.f90.
References io::io_error().
hdf5_addattribute_str()
subroutine hdf5_utilities::hdf5_addattribute_str (integer(hid_t), intent(in) loc_id, character(len=*), intent(in) attrLabel, character(len=*), intent(in) attrValue, character(len=*), intent(in), optional path)
adds a string attribute to the path given relative to the location
Definition at line 7147 of file DAMASK_marc.f90.
References io::io_error().
hdf5_addgroup()
integer(hid_t) function hdf5_utilities::hdf5_addgroup (integer(hid_t), intent(in) fileHandle, character(len=*), intent(in) groupName)
adds a new group to the fileHandle
Definition at line 7036 of file DAMASK_marc.f90.
References io::io_error().
Referenced by results::results_addgroup().
hdf5_closefile()
subroutine hdf5_utilities::hdf5_closefile (integer(hid_t), intent(in) fileHandle)
close the opened HDF5 output file
Definition at line 7021 of file DAMASK_marc.f90.
References io::io_error().
Referenced by results::results_closejobfile().
hdf5_closegroup()
subroutine hdf5_utilities::hdf5_closegroup (integer(hid_t), intent(in) group_id)
close a group
Definition at line 7105 of file DAMASK_marc.f90.
References io::io_error().
Referenced by results::results_closegroup(), results::results_mapping_constituent(), results::results_mapping_materialpoint(), results::results_writescalardataset_real(), results::results_writescalardataset_rotation(), results::results_writetensordataset_int(), results::results_writetensordataset_real(), results::results_writevectordataset_int(), and results::results_writevectordataset_real().
hdf5_objectexists()
logical function hdf5_utilities::hdf5_objectexists (integer(hid_t), intent(in) loc_id, character(len=*), intent(in), optional path)
check whether a group or a dataset exists
Definition at line 7119 of file DAMASK_marc.f90.
References io::io_error().
Referenced by results::results_writescalardataset_real(), results::results_writescalardataset_rotation(), results::results_writetensordataset_int(), results::results_writetensordataset_real(), results::results_writevectordataset_int(), and results::results_writevectordataset_real().
hdf5_openfile()
integer(hid_t) function hdf5_utilities::hdf5_openfile (character(len=*), intent(in) fileName, character, intent(in), optional mode, logical, intent(in), optional parallel)
open and initializes HDF5 output file
Definition at line 6973 of file DAMASK_marc.f90.
References io::io_error().
Referenced by results::results_init(), and results::results_openjobfile().
hdf5_opengroup()
integer(hid_t) function hdf5_utilities::hdf5_opengroup (integer(hid_t), intent(in) fileHandle, character(len=*), intent(in) groupName)
open an existing group of a file
Definition at line 7069 of file DAMASK_marc.f90.
References io::io_error().
Referenced by results::results_opengroup().
hdf5_read_int1()
subroutine hdf5_utilities::hdf5_read_int1 (integer(hid_t), intent(in) loc_id, integer, dimension(:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type integer with 1 dimension
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7666 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_int2()
subroutine hdf5_utilities::hdf5_read_int2 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type integer with 2 dimensions
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7707 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_int3()
subroutine hdf5_utilities::hdf5_read_int3 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type integer with 3 dimensions
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7747 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_int4()
subroutine hdf5_utilities::hdf5_read_int4 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:,:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type integer withh 4 dimensions
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7787 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_int5()
subroutine hdf5_utilities::hdf5_read_int5 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:,:,:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type integer with 5 dimensions
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7827 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_int6()
subroutine hdf5_utilities::hdf5_read_int6 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:,:,:,:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type integer with 6 dimensions
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7867 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_int7()
subroutine hdf5_utilities::hdf5_read_int7 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:,:,:,:,:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type integer with 7 dimensions
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7907 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_real1()
subroutine hdf5_utilities::hdf5_read_real1 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type real with 1 dimension
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7385 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_real2()
subroutine hdf5_utilities::hdf5_read_real2 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type real with 2 dimensions
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7425 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_real3()
subroutine hdf5_utilities::hdf5_read_real3 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type real with 2 dimensions
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7465 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_real4()
subroutine hdf5_utilities::hdf5_read_real4 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:,:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type real with 4 dimensions
Parameters
[out] dataset read data
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7505 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_real5()
subroutine hdf5_utilities::hdf5_read_real5 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:,:,:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type real with 5 dimensions
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7545 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_real6()
subroutine hdf5_utilities::hdf5_read_real6 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:,:,:,:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type real with 6 dimensions
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7585 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_read_real7()
subroutine hdf5_utilities::hdf5_read_real7 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:,:,:,:,:,:), intent(out) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
read dataset of type real with 7 dimensions
Parameters
[out] dataset data read from file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7625 of file DAMASK_marc.f90.
References finalize_read(), initialize_read(), and io::io_error().
hdf5_setlink()
subroutine hdf5_utilities::hdf5_setlink (integer(hid_t), intent(in) loc_id, character(len=*), intent(in) target_name, character(len=*), intent(in) link_name)
set link to object in results file
Definition at line 7363 of file DAMASK_marc.f90.
References io::io_error().
Referenced by results::results_setlink().
hdf5_utilities_init()
subroutine hdf5_utilities::hdf5_utilities_init
open libary and do sanity checks
Definition at line 6945 of file DAMASK_marc.f90.
References io::io_error().
Referenced by cpfem_initall().
hdf5_write_int1()
subroutine hdf5_utilities::hdf5_write_int1 (integer(hid_t), intent(in) loc_id, integer, dimension(:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type integer with 1 dimension
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8237 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_int2()
subroutine hdf5_utilities::hdf5_write_int2 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type integer with 2 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8278 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_int3()
subroutine hdf5_utilities::hdf5_write_int3 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type integer with 3 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8319 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_int4()
subroutine hdf5_utilities::hdf5_write_int4 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:,:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type integer with 4 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8360 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_int5()
subroutine hdf5_utilities::hdf5_write_int5 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:,:,:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type integer with 5 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8401 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_int6()
subroutine hdf5_utilities::hdf5_write_int6 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:,:,:,:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type integer with 6 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8442 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_int7()
subroutine hdf5_utilities::hdf5_write_int7 (integer(hid_t), intent(in) loc_id, integer, dimension(:,:,:,:,:,:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type integer with 7 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8483 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_real1()
subroutine hdf5_utilities::hdf5_write_real1 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type real with 1 dimension
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7948 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_real2()
subroutine hdf5_utilities::hdf5_write_real2 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type real with 2 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 7989 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_real3()
subroutine hdf5_utilities::hdf5_write_real3 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type real with 3 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8030 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_real4()
subroutine hdf5_utilities::hdf5_write_real4 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:,:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type real with 4 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8071 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_real5()
subroutine hdf5_utilities::hdf5_write_real5 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:,:,:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type real with 5 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8113 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_real6()
subroutine hdf5_utilities::hdf5_write_real6 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:,:,:,:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type real with 6 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8154 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_real7()
subroutine hdf5_utilities::hdf5_write_real7 (integer(hid_t), intent(in) loc_id, real(preal), dimension(:,:,:,:,:,:,:), intent(inout) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
write dataset of type real with 7 dimensions
Parameters
[in,out] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[in] parallel dataset is distributed over multiple processes
Definition at line 8195 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
hdf5_write_rotation()
subroutine hdf5_utilities::hdf5_write_rotation (integer(hid_t), intent(in) loc_id, type(rotation), dimension(:), intent(in) dataset, character(len=*), intent(in) datasetName, logical, intent(in), optional parallel)
writes a scalar orientation dataset
Parameters
[in] dataset data written to file
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
Definition at line 8527 of file DAMASK_marc.f90.
References finalize_write(), initialize_write(), and io::io_error().
initialize_read()
subroutine hdf5_utilities::initialize_read (integer(hid_t), intent(out) dset_id, integer(hid_t), intent(out) filespace_id, integer(hid_t), intent(out) memspace_id, integer(hid_t), intent(out) plist_id, integer(hid_t), intent(out) aplist_id, integer(hsize_t), dimension(size(localshape,1)), intent(out) myStart, integer(hsize_t), dimension(size(localshape,1)), intent(out) globalShape, integer(hid_t), intent(in) loc_id, integer(hsize_t), dimension(:), intent(in) localShape, character(len=*), intent(in) datasetName, logical, intent(in) parallel)
initialize HDF5 handles, determines global shape and start for parallel read
Parameters
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[out] globalshape shape of the dataset (all processes)
Definition at line 8603 of file DAMASK_marc.f90.
References io::io_error(), and numerics::worldrank.
Referenced by hdf5_read_int1(), hdf5_read_int2(), hdf5_read_int3(), hdf5_read_int4(), hdf5_read_int5(), hdf5_read_int6(), hdf5_read_int7(), hdf5_read_real1(), hdf5_read_real2(), hdf5_read_real3(), hdf5_read_real4(), hdf5_read_real5(), hdf5_read_real6(), and hdf5_read_real7().
initialize_write()
subroutine hdf5_utilities::initialize_write (integer(hid_t), intent(out) dset_id, integer(hid_t), intent(out) filespace_id, integer(hid_t), intent(out) memspace_id, integer(hid_t), intent(out) plist_id, integer(hsize_t), dimension(size(myshape,1)), intent(out) myStart, integer(hsize_t), dimension(size(myshape,1)), intent(out) totalShape, integer(hid_t), intent(in) loc_id, integer(hsize_t), dimension(:), intent(in) myShape, character(len=*), intent(in) datasetName, integer(hid_t), intent(in) datatype, logical, intent(in) parallel)
initialize HDF5 handles, determines global shape and start for parallel write
Parameters
[in] loc_id file or group handle
[in] datasetname name of the dataset in the file
[out] totalshape shape of the dataset (all processes)
Definition at line 8689 of file DAMASK_marc.f90.
References io::io_error(), and numerics::worldrank.
Referenced by hdf5_write_int1(), hdf5_write_int2(), hdf5_write_int3(), hdf5_write_int4(), hdf5_write_int5(), hdf5_write_int6(), hdf5_write_int7(), hdf5_write_real1(), hdf5_write_real2(), hdf5_write_real3(), hdf5_write_real4(), hdf5_write_real5(), hdf5_write_real6(), hdf5_write_real7(), and hdf5_write_rotation().