DAMASK with MSC.Marc FEM solver: element Module Reference
element Module Reference
Data Types
type telement
Properties of a single element.
Functions/Subroutines
subroutine telement_init (self, elemType)
define properties of an element
Variables
integer, parameter nelemtype = 13
integer, dimension(nelemtype), parameter nnode = [ 3, 6, 4, 8, 8, 4, 5, 10, 6, 8, 8, 20, 20 ]
number of nodes that constitute a specific type of element
integer, dimension(nelemtype), parameter geomtype = [ 1, 2, 3, 4, 3, 5, 6, 6, 7, 8, 9, 9, 10 ]
geometry type (same number of cell nodes and IPs)
integer, dimension(maxval(geomtype)), parameter ncellnode = [ 3, 7, 9, 16, 4, 15, 21, 8, 27, 64 ]
number of cell nodes
integer, dimension(maxval(geomtype)), parameter nip = [ 1, 3, 4, 9, 1, 4, 6, 1, 8, 27 ]
number of IPs
integer, dimension(maxval(geomtype)), parameter celltype = [ 1, 2, 2, 2, 3, 4, 4, 4, 4, 4 ]
cell type
integer, dimension(maxval(celltype)), parameter nipneighbor = [ 3, 4, 4, 6 ]
number of ip neighbors / cell faces
integer, dimension(maxval(celltype)), parameter ncellnodepercellface = [ 2, 2, 3, 4 ]
number of cell nodes per face
integer, dimension(maxval(celltype)), parameter ncellnodepercell = [ 3, 4, 4, 8 ]
number of total cell nodes
integer, dimension(nipneighbor(celltype(1)), nip(1)), parameter ipneighbor1 = reshape([ -2,-3,-1 ], [NIPNEIGHBOR(CELLTYPE(1)),NIP(1)])
integer, dimension(nipneighbor(celltype(2)), nip(2)), parameter ipneighbor2 = reshape([ 2,-3, 3,-1, -2, 1, 3,-1, 2,-3,-2, 1 ], [NIPNEIGHBOR(CELLTYPE(2)),NIP(2)])
integer, dimension(nipneighbor(celltype(3)), nip(3)), parameter ipneighbor3 = reshape([ 2,-4, 3,-1, -2, 1, 4,-1, 4,-4,-3, 1, -2, 3,-3, 2 ], [NIPNEIGHBOR(CELLTYPE(3)),NIP(3)])
integer, dimension(nipneighbor(celltype(4)), nip(4)), parameter ipneighbor4 = reshape([ 2,-4, 4,-1, 3, 1, 5,-1, -2, 2, 6,-1, 5,-4, 7, 1, 6, 4, 8, 2, -2, 5, 9, 3, 8,-4,-3, 4, 9, 7,-3, 5, -2, 8,-3, 6 ], [NIPNEIGHBOR(CELLTYPE(4)),NIP(4)])
integer, dimension(nipneighbor(celltype(5)), nip(5)), parameter ipneighbor5 = reshape([ -1,-2,-3,-4 ], [NIPNEIGHBOR(CELLTYPE(5)),NIP(5)])
integer, dimension(nipneighbor(celltype(6)), nip(6)), parameter ipneighbor6 = reshape([ 2,-4, 3,-2, 4,-1, -2, 1, 3,-2, 4,-1, 2,-4,-3, 1, 4,-1, 2,-4, 3,-2,-3, 1 ], [NIPNEIGHBOR(CELLTYPE(6)),NIP(6)])
integer, dimension(nipneighbor(celltype(7)), nip(7)), parameter ipneighbor7 = reshape([ 2,-4, 3,-2, 4,-1, -3, 1, 3,-2, 5,-1, 2,-4,-3, 1, 6,-1, 5,-4, 6,-2,-5, 1, -3, 4, 6,-2,-5, 2, 5,-4,-3, 4,-5, 3 ], [NIPNEIGHBOR(CELLTYPE(7)),NIP(7)])
integer, dimension(nipneighbor(celltype(8)), nip(8)), parameter ipneighbor8 = reshape([ -3,-5,-4,-2,-6,-1 ], [NIPNEIGHBOR(CELLTYPE(8)),NIP(8)])
integer, dimension(nipneighbor(celltype(9)), nip(9)), parameter ipneighbor9 = reshape([ 2,-5, 3,-2, 5,-1, -3, 1, 4,-2, 6,-1, 4,-5,-4, 1, 7,-1, -3, 3,-4, 2, 8,-1, 6,-5, 7,-2,-6, 1, -3, 5, 8,-2,-6, 2, 8,-5,-4, 5,-6, 3, -3, 7,-4, 6,-6, 4 ], [NIPNEIGHBOR(CELLTYPE(9)),NIP(9)])
integer, dimension(nipneighbor(celltype(10)), nip(10)), parameter ipneighbor10 = reshape([ 2,-5, 4,-2,10,-1, 3, 1, 5,-2,11,-1, -3, 2, 6,-2,12,-1, 5,-5, 7, 1,13,-1, 6, 4, 8, 2,14,-1, -3, 5, 9, 3,15,-1, 8,-5,-4, 4,16,-1, 9, 7,-4, 5,17,-1, -3, 8,-4, 6,18,-1, 11,-5,13,-2,19, 1, 12,10,14,-2,20, 2, -3,11,15,-2,21, 3, 14,-5,16,10,22, 4, 15,13,17,11,23, 5, -3,14,18,12,24, 6, 17,-5,-4,13,25, 7, 18,16,-4,14,26, 8, -3,17,-4,15,27, 9, 20,-5,22,-2,-6,10, 21,19,23,-2,-6,11, -3,20,24,-2,-6,12, 23,-5,25,19,-6,13, 24,22,26,20,-6,14, -3,23,27,21,-6,15, 26,-5,-4,22,-6,16, 27,25,-4,23,-6,17, -3,26,-4,24,-6,18 ], [NIPNEIGHBOR(CELLTYPE(10)),NIP(10)])
integer, dimension(nnode(1), ncellnode(geomtype(1))), parameter cellnodeparentnodeweights1 = reshape([ 1, 0, 0, 0, 1, 0, 0, 0, 1 ], [NNODE(1),NCELLNODE(GEOMTYPE(1))])
integer, dimension(nnode(2), ncellnode(geomtype(2))), parameter cellnodeparentnodeweights2 = reshape([ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2 ], [NNODE(2),NCELLNODE(GEOMTYPE(2))])
integer, dimension(nnode(3), ncellnode(geomtype(3))), parameter cellnodeparentnodeweights3 = reshape([ 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1 ], [NNODE(3),NCELLNODE(GEOMTYPE(3))])
integer, dimension(nnode(4), ncellnode(geomtype(4))), parameter cellnodeparentnodeweights4 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 2, 4, 1, 1, 1, 8, 2, 2, 8, 1, 4, 1, 1, 8, 8, 2, 2, 1, 1, 4, 1, 2, 8, 8, 2, 1, 1, 1, 4, 2, 2, 8, 8 ], [NNODE(4),NCELLNODE(GEOMTYPE(4))])
integer, dimension(nnode(5), ncellnode(geomtype(5))), parameter cellnodeparentnodeweights5 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2 ], [NNODE(5),NCELLNODE(GEOMTYPE(5))])
integer, dimension(nnode(6), ncellnode(geomtype(6))), parameter cellnodeparentnodeweights6 = reshape([ 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 ], [NNODE(6),NcellNode(GEOMTYPE(6))])
integer, dimension(nnode(7), ncellnode(geomtype(7))), parameter cellnodeparentnodeweights7 = reshape([ 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1 ], [NNODE(7),NCELLNODE(GEOMTYPE(7))])
integer, dimension(nnode(8), ncellnode(geomtype(8))), parameter cellnodeparentnodeweights8 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 2, 2, 2, 0, 0, 0, 1, 1, 0, 1, 2, 0, 0, 2, 2, 0, 0, 1, 1, 1, 0, 2, 0, 0, 2, 2, 1, 0, 1, 1, 0, 0, 2, 2, 0, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4 ], [NNODE(8),NCELLNODE(GEOMTYPE(8))])
integer, dimension(nnode(9), ncellnode(geomtype(9))), parameter cellnodeparentnodeweights9 = reshape([ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1 ], [NNODE(9),NCELLNODE(GEOMTYPE(9))])
integer, dimension(nnode(10), ncellnode(geomtype(10))), parameter cellnodeparentnodeweights10 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1 ], [NNODE(10),NCELLNODE(GEOMTYPE(10))])
integer, dimension(nnode(11), ncellnode(geomtype(11))), parameter cellnodeparentnodeweights11 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ], [NNODE(11),NCELLNODE(GEOMTYPE(11))])
integer, dimension(nnode(12), ncellnode(geomtype(12))), parameter cellnodeparentnodeweights12 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4 ], [NNODE(12),NCELLNODE(GEOMTYPE(12))])
integer, dimension(nnode(13), ncellnode(geomtype(13))), parameter cellnodeparentnodeweights13 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 4, 1, 1, 1, 0, 0, 0, 0, 8, 2, 2, 8, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 1, 1, 0, 0, 0, 0, 8, 8, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 4, 1, 0, 0, 0, 0, 2, 8, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 4, 0, 0, 0, 0, 2, 2, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 8, 2, 0, 0, 1, 4, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 2, 8, 0, 0, 0, 4, 1, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 8, 2, 0, 0, 1, 4, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 2, 8, 0, 0, 0, 4, 1, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 8, 2, 0, 0, 1, 4, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 2, 8, 1, 0, 0, 4, 1, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 2, 2, 0, 0, 8, 4, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 2, 8, 0, 0, 2, 1, 1, 0, 0, 4, 1, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 8, 2, 0, 0, 1, 1, 0, 0, 1, 4, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 2, 8, 0, 0, 0, 1, 1, 0, 0, 4, 1, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 8, 2, 0, 0, 1, 1, 0, 0, 1, 4, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 2, 8, 0, 0, 0, 1, 1, 0, 0, 4, 1, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 8, 2, 0, 0, 1, 1, 0, 0, 1, 4, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 2, 8, 1, 0, 0, 1, 1, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 8, 2, 0, 0, 8, 1, 0, 0, 1, 4, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 8, 8, 0, 0, 2, 0, 0, 0, 0, 4, 1, 1, 1, 0, 0, 0, 0, 8, 2, 2, 8, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 1, 1, 0, 0, 0, 0, 8, 8, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 4, 1, 0, 0, 0, 0, 2, 8, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 4, 0, 0, 0, 0, 2, 2, 8, 8, 0, 0, 0, 0, 24, 8, 4, 8, 8, 4, 3, 4, 32,12,12,32, 12, 4, 4,12, 32,12, 4,12, 8,24, 8, 4, 4, 8, 4, 3, 32,32,12,12, 12,12, 4, 4, 12,32,12, 4, 4, 8,24, 8, 3, 4, 8, 4, 12,32,32,12, 4,12,12, 4, 4,12,32,12, 8, 4, 8,24, 4, 3, 4, 8, 12,12,32,32, 4, 4,12,12, 12, 4,12,32, 8, 4, 3, 4, 24, 8, 4, 8, 12, 4, 4,12, 32,12,12,32, 32,12, 4,12, 4, 8, 4, 3, 8,24, 8, 4, 12,12, 4, 4, 32,32,12,12, 12,32,12, 4, 3, 4, 8, 4, 4, 8,24, 8, 4,12,12, 4, 12,32,32,12, 4,12,32,12, 4, 3, 4, 8, 8, 4, 8,24, 4, 4,12,12, 12,12,32,32, 12, 4,12,32 ], [NNODE(13),NCELLNODE(GEOMTYPE(13))])
integer, dimension(ncellnodepercell(celltype(1)), nip(1)), parameter cell1 = reshape([ 1,2,3 ], [NCELLNODEPERCELL(CELLTYPE(1)),NIP(1)])
integer, dimension(ncellnodepercell(celltype(2)), nip(2)), parameter cell2 = reshape([ 1, 4, 7, 6, 2, 5, 7, 4, 3, 6, 7, 5 ], [NCELLNODEPERCELL(CELLTYPE(2)),NIP(2)])
integer, dimension(ncellnodepercell(celltype(3)), nip(3)), parameter cell3 = reshape([ 1, 5, 9, 8, 5, 2, 6, 9, 8, 9, 7, 4, 9, 6, 3, 7 ], [NCELLNODEPERCELL(CELLTYPE(3)),NIP(3)])
integer, dimension(ncellnodepercell(celltype(4)), nip(4)), parameter cell4 = reshape([ 1, 5,13,12, 5, 6,14,13, 6, 2, 7,14, 12,13,16,11, 13,14,15,16, 14, 7, 8,15, 11,16,10, 4, 16,15, 9,10, 15, 8, 3, 9 ], [NCELLNODEPERCELL(CELLTYPE(4)),NIP(4)])
integer, dimension(ncellnodepercell(celltype(5)), nip(5)), parameter cell5 = reshape([ 1, 2, 3, 4 ], [NCELLNODEPERCELL(CELLTYPE(5)),NIP(5)])
integer, dimension(ncellnodepercell(celltype(6)), nip(6)), parameter cell6 = reshape([ 1, 5,11, 7, 8,12,15,14, 5, 2, 6,11,12, 9,13,15, 7,11, 6, 3,14,15,13,10, 8,12,15, 4, 4, 9,13,10 ], [NCELLNODEPERCELL(CELLTYPE(6)),NIP(6)])
integer, dimension(ncellnodepercell(celltype(7)), nip(7)), parameter cell7 = reshape([ 1, 7,16, 9,10,17,21,19, 7, 2, 8,16,17,11,18,21, 9,16, 8, 3,19,21,18,12, 10,17,21,19, 4,13,20,15, 17,11,18,21,13, 5,14,20, 19,21,18,12,15,20,14, 6 ], [NCELLNODEPERCELL(CELLTYPE(7)),NIP(7)])
integer, dimension(ncellnodepercell(celltype(8)), nip(8)), parameter cell8 = reshape([ 1, 2, 3, 4, 5, 6, 7, 8 ], [NCELLNODEPERCELL(CELLTYPE(8)),NIP(8)])
integer, dimension(ncellnodepercell(celltype(9)), nip(9)), parameter cell9 = reshape([ 1, 9,21,12,17,22,27,25, 9, 2,10,21,22,18,23,27, 12,21,11, 4,25,27,24,20, 21,10, 3,11,27,23,19,24, 17,22,27,25, 5,13,26,16, 22,18,23,27,13, 6,14,26, 25,27,24,20,16,26,15, 8, 27,23,19,24,26,14, 7,15 ], [NCELLNODEPERCELL(CELLTYPE(9)),NIP(9)])
integer, dimension(ncellnodepercell(celltype(10)), nip(10)), parameter cell10 = reshape([ 1, 9,33,16,17,37,57,44, 9,10,34,33,37,38,58,57, 10, 2,11,34,38,18,39,58, 16,33,36,15,44,57,60,43, 33,34,35,36,57,58,59,60, 34,11,12,35,58,39,40,59, 15,36,14, 4,43,60,42,20, 36,35,13,14,60,59,41,42, 35,12, 3,13,59,40,19,41, 17,37,57,44,21,45,61,52, 37,38,58,57,45,46,62,61, 38,18,39,58,46,22,47,62, 44,57,60,43,52,61,64,51, 57,58,59,60,61,62,63,64, 58,39,40,59,62,47,48,63, 43,60,42,20,51,64,50,24, 60,59,41,42,64,63,49,50, 59,40,19,41,63,48,23,49, 21,45,61,52, 5,25,53,32, 45,46,62,61,25,26,54,53, 46,22,47,62,26, 6,27,54, 52,61,64,51,32,53,56,31, 61,62,63,64,53,54,55,56, 62,47,48,63,54,27,28,55, 51,64,50,24,31,56,30, 8, 64,63,49,50,56,55,29,30, 63,48,23,49,55,28, 7,29 ], [NCELLNODEPERCELL(CELLTYPE(10)),NIP(10)])
integer, dimension(ncellnodepercellface(1), nipneighbor(1)), parameter cellface1 = reshape([ 2,3, 3,1, 1,2 ], [NCELLNODEPERCELLFACE(1),NIPNEIGHBOR(1)])
integer, dimension(ncellnodepercellface(2), nipneighbor(2)), parameter cellface2 = reshape([ 2,3, 4,1, 3,4, 1,2 ], [NCELLNODEPERCELLFACE(2),NIPNEIGHBOR(2)])
integer, dimension(ncellnodepercellface(3), nipneighbor(3)), parameter cellface3 = reshape([ 1,3,2, 1,2,4, 2,3,4, 1,4,3 ], [NCELLNODEPERCELLFACE(3),NIPNEIGHBOR(3)])
integer, dimension(ncellnodepercellface(4), nipneighbor(4)), parameter cellface4 = reshape([ 2,3,7,6, 4,1,5,8, 3,4,8,7, 1,2,6,5, 5,6,7,8, 1,4,3,2 ], [NCELLNODEPERCELLFACE(4),NIPNEIGHBOR(4)])
Detailed Description
Author
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
Christoph Koords, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
telement_init()
subroutine element::telement_init (class(telement) self, integer, intent(in) elemType) private
define properties of an element
Definition at line 6745 of file DAMASK_marc.f90.
References cell1, cell10, cell2, cell3, cell4, cell5, cell6, cell7, cell8, cell9, cellface1, cellface2, cellface3, cellface4, cellnodeparentnodeweights1, cellnodeparentnodeweights10, cellnodeparentnodeweights11, cellnodeparentnodeweights12, cellnodeparentnodeweights13, cellnodeparentnodeweights2, cellnodeparentnodeweights3, cellnodeparentnodeweights4, cellnodeparentnodeweights5, cellnodeparentnodeweights6, cellnodeparentnodeweights7, cellnodeparentnodeweights8, cellnodeparentnodeweights9, celltype, geomtype, io::io_error(), ipneighbor1, ipneighbor10, ipneighbor2, ipneighbor3, ipneighbor4, ipneighbor5, ipneighbor6, ipneighbor7, ipneighbor8, ipneighbor9, ncellnode, ncellnodepercell, nip, and nnode.
Variable Documentation
cell1
integer, dimension(ncellnodepercell(celltype(1)),nip(1)), parameter element::cell1 = reshape([ 1,2,3 ], [NCELLNODEPERCELL(CELLTYPE(1)),NIP(1)]) private
Definition at line 6543 of file DAMASK_marc.f90.
Referenced by telement_init().
cell10
integer, dimension(ncellnodepercell(celltype(10)),nip(10)), parameter element::cell10 = reshape([ 1, 9,33,16,17,37,57,44, 9,10,34,33,37,38,58,57, 10, 2,11,34,38,18,39,58, 16,33,36,15,44,57,60,43, 33,34,35,36,57,58,59,60, 34,11,12,35,58,39,40,59, 15,36,14, 4,43,60,42,20, 36,35,13,14,60,59,41,42, 35,12, 3,13,59,40,19,41, 17,37,57,44,21,45,61,52, 37,38,58,57,45,46,62,61, 38,18,39,58,46,22,47,62, 44,57,60,43,52,61,64,51, 57,58,59,60,61,62,63,64, 58,39,40,59,62,47,48,63, 43,60,42,20,51,64,50,24, 60,59,41,42,64,63,49,50, 59,40,19,41,63,48,23,49, 21,45,61,52, 5,25,53,32, 45,46,62,61,25,26,54,53, 46,22,47,62,26, 6,27,54, 52,61,64,51,32,53,56,31, 61,62,63,64,53,54,55,56, 62,47,48,63,54,27,28,55, 51,64,50,24,31,56,30, 8, 64,63,49,50,56,55,29,30, 63,48,23,49,55,28, 7,29 ], [NCELLNODEPERCELL(CELLTYPE(10)),NIP(10)]) private
Definition at line 6652 of file DAMASK_marc.f90.
Referenced by telement_init().
cell2
integer, dimension(ncellnodepercell(celltype(2)),nip(2)), parameter element::cell2 = reshape([ 1, 4, 7, 6, 2, 5, 7, 4, 3, 6, 7, 5 ], [NCELLNODEPERCELL(CELLTYPE(2)),NIP(2)]) private
Definition at line 6552 of file DAMASK_marc.f90.
Referenced by telement_init().
cell3
integer, dimension(ncellnodepercell(celltype(3)),nip(3)), parameter element::cell3 = reshape([ 1, 5, 9, 8, 5, 2, 6, 9, 8, 9, 7, 4, 9, 6, 3, 7 ], [NCELLNODEPERCELL(CELLTYPE(3)),NIP(3)]) private
Definition at line 6563 of file DAMASK_marc.f90.
Referenced by telement_init().
cell4
integer, dimension(ncellnodepercell(celltype(4)),nip(4)), parameter element::cell4 = reshape([ 1, 5,13,12, 5, 6,14,13, 6, 2, 7,14, 12,13,16,11, 13,14,15,16, 14, 7, 8,15, 11,16,10, 4, 16,15, 9,10, 15, 8, 3, 9 ], [NCELLNODEPERCELL(CELLTYPE(4)),NIP(4)]) private
Definition at line 6575 of file DAMASK_marc.f90.
Referenced by telement_init().
cell5
integer, dimension(ncellnodepercell(celltype(5)),nip(5)), parameter element::cell5 = reshape([ 1, 2, 3, 4 ], [NCELLNODEPERCELL(CELLTYPE(5)),NIP(5)]) private
Definition at line 6592 of file DAMASK_marc.f90.
Referenced by telement_init().
cell6
integer, dimension(ncellnodepercell(celltype(6)),nip(6)), parameter element::cell6 = reshape([ 1, 5,11, 7, 8,12,15,14, 5, 2, 6,11,12, 9,13,15, 7,11, 6, 3,14,15,13,10, 8,12,15, 4, 4, 9,13,10 ], [NCELLNODEPERCELL(CELLTYPE(6)),NIP(6)]) private
Definition at line 6601 of file DAMASK_marc.f90.
Referenced by telement_init().
cell7
integer, dimension(ncellnodepercell(celltype(7)),nip(7)), parameter element::cell7 = reshape([ 1, 7,16, 9,10,17,21,19, 7, 2, 8,16,17,11,18,21, 9,16, 8, 3,19,21,18,12, 10,17,21,19, 4,13,20,15, 17,11,18,21,13, 5,14,20, 19,21,18,12,15,20,14, 6 ], [NCELLNODEPERCELL(CELLTYPE(7)),NIP(7)]) private
Definition at line 6613 of file DAMASK_marc.f90.
Referenced by telement_init().
cell8
integer, dimension(ncellnodepercell(celltype(8)),nip(8)), parameter element::cell8 = reshape([ 1, 2, 3, 4, 5, 6, 7, 8 ], [NCELLNODEPERCELL(CELLTYPE(8)),NIP(8)]) private
Definition at line 6627 of file DAMASK_marc.f90.
Referenced by telement_init().
cell9
integer, dimension(ncellnodepercell(celltype(9)),nip(9)), parameter element::cell9 = reshape([ 1, 9,21,12,17,22,27,25, 9, 2,10,21,22,18,23,27, 12,21,11, 4,25,27,24,20, 21,10, 3,11,27,23,19,24, 17,22,27,25, 5,13,26,16, 22,18,23,27,13, 6,14,26, 25,27,24,20,16,26,15, 8, 27,23,19,24,26,14, 7,15 ], [NCELLNODEPERCELL(CELLTYPE(9)),NIP(9)]) private
Definition at line 6636 of file DAMASK_marc.f90.
Referenced by telement_init().
cellface1
integer, dimension(ncellnodepercellface(1),nipneighbor(1)), parameter element::cellface1 = reshape([ 2,3, 3,1, 1,2 ], [NCELLNODEPERCELLFACE(1),NIPNEIGHBOR(1)]) private
Definition at line 6688 of file DAMASK_marc.f90.
Referenced by telement_init().
cellface2
integer, dimension(ncellnodepercellface(2),nipneighbor(2)), parameter element::cellface2 = reshape([ 2,3, 4,1, 3,4, 1,2 ], [NCELLNODEPERCELLFACE(2),NIPNEIGHBOR(2)]) private
Definition at line 6699 of file DAMASK_marc.f90.
Referenced by telement_init().
cellface3
integer, dimension(ncellnodepercellface(3),nipneighbor(3)), parameter element::cellface3 = reshape([ 1,3,2, 1,2,4, 2,3,4, 1,4,3 ], [NCELLNODEPERCELLFACE(3),NIPNEIGHBOR(3)]) private
Definition at line 6711 of file DAMASK_marc.f90.
Referenced by telement_init().
cellface4
integer, dimension(ncellnodepercellface(4),nipneighbor(4)), parameter element::cellface4 = reshape([ 2,3,7,6, 4,1,5,8, 3,4,8,7, 1,2,6,5, 5,6,7,8, 1,4,3,2 ], [NCELLNODEPERCELLFACE(4),NIPNEIGHBOR(4)]) private
Definition at line 6723 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights1
integer, dimension(nnode(1),ncellnode(geomtype(1))), parameter element::cellnodeparentnodeweights1 = reshape([ 1, 0, 0, 0, 1, 0, 0, 0, 1 ], [NNODE(1),NCELLNODE(GEOMTYPE(1))]) private
Definition at line 6213 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights10
integer, dimension(nnode(10),ncellnode(geomtype(10))), parameter element::cellnodeparentnodeweights10 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1 ], [NNODE(10),NCELLNODE(GEOMTYPE(10))]) private
Definition at line 6384 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights11
integer, dimension(nnode(11),ncellnode(geomtype(11))), parameter element::cellnodeparentnodeweights11 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ], [NNODE(11),NCELLNODE(GEOMTYPE(11))]) private
Definition at line 6400 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights12
integer, dimension(nnode(12),ncellnode(geomtype(12))), parameter element::cellnodeparentnodeweights12 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4 ], [NNODE(12),NCELLNODE(GEOMTYPE(12))]) private
Definition at line 6435 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights13
integer, dimension(nnode(13),ncellnode(geomtype(13))), parameter element::cellnodeparentnodeweights13 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 4, 1, 1, 1, 0, 0, 0, 0, 8, 2, 2, 8, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 1, 1, 0, 0, 0, 0, 8, 8, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 4, 1, 0, 0, 0, 0, 2, 8, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 4, 0, 0, 0, 0, 2, 2, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 8, 2, 0, 0, 1, 4, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 2, 8, 0, 0, 0, 4, 1, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 8, 2, 0, 0, 1, 4, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 2, 8, 0, 0, 0, 4, 1, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 8, 2, 0, 0, 1, 4, 0, 0, 1, 1, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 2, 8, 1, 0, 0, 4, 1, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 2, 2, 0, 0, 8, 4, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 2, 8, 0, 0, 2, 1, 1, 0, 0, 4, 1, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 8, 2, 0, 0, 1, 1, 0, 0, 1, 4, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 2, 8, 0, 0, 0, 1, 1, 0, 0, 4, 1, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 8, 2, 0, 0, 1, 1, 0, 0, 1, 4, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 2, 8, 0, 0, 0, 1, 1, 0, 0, 4, 1, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 8, 2, 0, 0, 1, 1, 0, 0, 1, 4, 0, 0, 2, 0, 0, 0, 8, 0, 0, 0, 2, 8, 1, 0, 0, 1, 1, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 8, 2, 0, 0, 8, 1, 0, 0, 1, 4, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 8, 8, 0, 0, 2, 0, 0, 0, 0, 4, 1, 1, 1, 0, 0, 0, 0, 8, 2, 2, 8, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 1, 1, 0, 0, 0, 0, 8, 8, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 4, 1, 0, 0, 0, 0, 2, 8, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 4, 0, 0, 0, 0, 2, 2, 8, 8, 0, 0, 0, 0, 24, 8, 4, 8, 8, 4, 3, 4, 32,12,12,32, 12, 4, 4,12, 32,12, 4,12, 8,24, 8, 4, 4, 8, 4, 3, 32,32,12,12, 12,12, 4, 4, 12,32,12, 4, 4, 8,24, 8, 3, 4, 8, 4, 12,32,32,12, 4,12,12, 4, 4,12,32,12, 8, 4, 8,24, 4, 3, 4, 8, 12,12,32,32, 4, 4,12,12, 12, 4,12,32, 8, 4, 3, 4, 24, 8, 4, 8, 12, 4, 4,12, 32,12,12,32, 32,12, 4,12, 4, 8, 4, 3, 8,24, 8, 4, 12,12, 4, 4, 32,32,12,12, 12,32,12, 4, 3, 4, 8, 4, 4, 8,24, 8, 4,12,12, 4, 12,32,32,12, 4,12,32,12, 4, 3, 4, 8, 8, 4, 8,24, 4, 4,12,12, 12,12,32,32, 12, 4,12,32 ], [NNODE(13),NCELLNODE(GEOMTYPE(13))]) private
Definition at line 6470 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights2
integer, dimension(nnode(2),ncellnode(geomtype(2))), parameter element::cellnodeparentnodeweights2 = reshape([ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2 ], [NNODE(2),NCELLNODE(GEOMTYPE(2))]) private
Definition at line 6224 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights3
integer, dimension(nnode(3),ncellnode(geomtype(3))), parameter element::cellnodeparentnodeweights3 = reshape([ 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1 ], [NNODE(3),NCELLNODE(GEOMTYPE(3))]) private
Definition at line 6239 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights4
integer, dimension(nnode(4),ncellnode(geomtype(4))), parameter element::cellnodeparentnodeweights4 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 2, 4, 1, 1, 1, 8, 2, 2, 8, 1, 4, 1, 1, 8, 8, 2, 2, 1, 1, 4, 1, 2, 8, 8, 2, 1, 1, 1, 4, 2, 2, 8, 8 ], [NNODE(4),NCELLNODE(GEOMTYPE(4))]) private
Definition at line 6256 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights5
integer, dimension(nnode(5),ncellnode(geomtype(5))), parameter element::cellnodeparentnodeweights5 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2 ], [NNODE(5),NCELLNODE(GEOMTYPE(5))]) private
Definition at line 6280 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights6
integer, dimension(nnode(6),ncellnode(geomtype(6))), parameter element::cellnodeparentnodeweights6 = reshape([ 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 ], [NNODE(6),NcellNode(GEOMTYPE(6))]) private
Definition at line 6297 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights7
integer, dimension(nnode(7),ncellnode(geomtype(7))), parameter element::cellnodeparentnodeweights7 = reshape([ 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1 ], [NNODE(7),NCELLNODE(GEOMTYPE(7))]) private
Definition at line 6309 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights8
integer, dimension(nnode(8),ncellnode(geomtype(8))), parameter element::cellnodeparentnodeweights8 = reshape([ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 2, 2, 2, 0, 0, 0, 1, 1, 0, 1, 2, 0, 0, 2, 2, 0, 0, 1, 1, 1, 0, 2, 0, 0, 2, 2, 1, 0, 1, 1, 0, 0, 2, 2, 0, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4 ], [NNODE(8),NCELLNODE(GEOMTYPE(8))]) private
Definition at line 6332 of file DAMASK_marc.f90.
Referenced by telement_init().
cellnodeparentnodeweights9
integer, dimension(nnode(9),ncellnode(geomtype(9))), parameter element::cellnodeparentnodeweights9 = reshape([ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1 ], [NNODE(9),NCELLNODE(GEOMTYPE(9))]) private
Definition at line 6355 of file DAMASK_marc.f90.
Referenced by telement_init().
celltype
integer, dimension(maxval(geomtype)), parameter element::celltype = [ 1, 2, 2, 2, 3, 4, 4, 4, 4, 4 ] private
cell type
Definition at line 6024 of file DAMASK_marc.f90.
Referenced by telement_init().
geomtype
integer, dimension(nelemtype), parameter element::geomtype = [ 1, 2, 3, 4, 3, 5, 6, 6, 7, 8, 9, 9, 10 ] private
geometry type (same number of cell nodes and IPs)
Definition at line 5978 of file DAMASK_marc.f90.
Referenced by telement_init().
ipneighbor1
integer, dimension(nipneighbor(celltype(1)),nip(1)), parameter element::ipneighbor1 = reshape([ -2,-3,-1 ], [NIPNEIGHBOR(CELLTYPE(1)),NIP(1)]) private
Definition at line 6068 of file DAMASK_marc.f90.
Referenced by telement_init().
ipneighbor10
integer, dimension(nipneighbor(celltype(10)),nip(10)), parameter element::ipneighbor10 = reshape([ 2,-5, 4,-2,10,-1, 3, 1, 5,-2,11,-1, -3, 2, 6,-2,12,-1, 5,-5, 7, 1,13,-1, 6, 4, 8, 2,14,-1, -3, 5, 9, 3,15,-1, 8,-5,-4, 4,16,-1, 9, 7,-4, 5,17,-1, -3, 8,-4, 6,18,-1, 11,-5,13,-2,19, 1, 12,10,14,-2,20, 2, -3,11,15,-2,21, 3, 14,-5,16,10,22, 4, 15,13,17,11,23, 5, -3,14,18,12,24, 6, 17,-5,-4,13,25, 7, 18,16,-4,14,26, 8, -3,17,-4,15,27, 9, 20,-5,22,-2,-6,10, 21,19,23,-2,-6,11, -3,20,24,-2,-6,12, 23,-5,25,19,-6,13, 24,22,26,20,-6,14, -3,23,27,21,-6,15, 26,-5,-4,22,-6,16, 27,25,-4,23,-6,17, -3,26,-4,24,-6,18 ], [NIPNEIGHBOR(CELLTYPE(10)),NIP(10)]) private
Definition at line 6177 of file DAMASK_marc.f90.
Referenced by telement_init().
ipneighbor2
integer, dimension(nipneighbor(celltype(2)),nip(2)), parameter element::ipneighbor2 = reshape([ 2,-3, 3,-1, -2, 1, 3,-1, 2,-3,-2, 1 ], [NIPNEIGHBOR(CELLTYPE(2)),NIP(2)]) private
Definition at line 6077 of file DAMASK_marc.f90.
Referenced by telement_init().
ipneighbor3
integer, dimension(nipneighbor(celltype(3)),nip(3)), parameter element::ipneighbor3 = reshape([ 2,-4, 3,-1, -2, 1, 4,-1, 4,-4,-3, 1, -2, 3,-3, 2 ], [NIPNEIGHBOR(CELLTYPE(3)),NIP(3)]) private
Definition at line 6088 of file DAMASK_marc.f90.
Referenced by telement_init().
ipneighbor4
integer, dimension(nipneighbor(celltype(4)),nip(4)), parameter element::ipneighbor4 = reshape([ 2,-4, 4,-1, 3, 1, 5,-1, -2, 2, 6,-1, 5,-4, 7, 1, 6, 4, 8, 2, -2, 5, 9, 3, 8,-4,-3, 4, 9, 7,-3, 5, -2, 8,-3, 6 ], [NIPNEIGHBOR(CELLTYPE(4)),NIP(4)]) private
Definition at line 6100 of file DAMASK_marc.f90.
Referenced by telement_init().
ipneighbor5
integer, dimension(nipneighbor(celltype(5)),nip(5)), parameter element::ipneighbor5 = reshape([ -1,-2,-3,-4 ], [NIPNEIGHBOR(CELLTYPE(5)),NIP(5)]) private
Definition at line 6117 of file DAMASK_marc.f90.
Referenced by telement_init().
ipneighbor6
integer, dimension(nipneighbor(celltype(6)),nip(6)), parameter element::ipneighbor6 = reshape([ 2,-4, 3,-2, 4,-1, -2, 1, 3,-2, 4,-1, 2,-4,-3, 1, 4,-1, 2,-4, 3,-2,-3, 1 ], [NIPNEIGHBOR(CELLTYPE(6)),NIP(6)]) private
Definition at line 6126 of file DAMASK_marc.f90.
Referenced by telement_init().
ipneighbor7
integer, dimension(nipneighbor(celltype(7)),nip(7)), parameter element::ipneighbor7 = reshape([ 2,-4, 3,-2, 4,-1, -3, 1, 3,-2, 5,-1, 2,-4,-3, 1, 6,-1, 5,-4, 6,-2,-5, 1, -3, 4, 6,-2,-5, 2, 5,-4,-3, 4,-5, 3 ], [NIPNEIGHBOR(CELLTYPE(7)),NIP(7)]) private
Definition at line 6138 of file DAMASK_marc.f90.
Referenced by telement_init().
ipneighbor8
integer, dimension(nipneighbor(celltype(8)),nip(8)), parameter element::ipneighbor8 = reshape([ -3,-5,-4,-2,-6,-1 ], [NIPNEIGHBOR(CELLTYPE(8)),NIP(8)]) private
Definition at line 6152 of file DAMASK_marc.f90.
Referenced by telement_init().
ipneighbor9
integer, dimension(nipneighbor(celltype(9)),nip(9)), parameter element::ipneighbor9 = reshape([ 2,-5, 3,-2, 5,-1, -3, 1, 4,-2, 6,-1, 4,-5,-4, 1, 7,-1, -3, 3,-4, 2, 8,-1, 6,-5, 7,-2,-6, 1, -3, 5, 8,-2,-6, 2, 8,-5,-4, 5,-6, 3, -3, 7,-4, 6,-6, 4 ], [NIPNEIGHBOR(CELLTYPE(9)),NIP(9)]) private
Definition at line 6161 of file DAMASK_marc.f90.
Referenced by telement_init().
ncellnode
integer, dimension(maxval(geomtype)), parameter element::ncellnode = [ 3, 7, 9, 16, 4, 15, 21, 8, 27, 64 ] private
number of cell nodes
Definition at line 5996 of file DAMASK_marc.f90.
Referenced by telement_init().
ncellnodepercell
integer, dimension(maxval(celltype)), parameter element::ncellnodepercell = [ 3, 4, 4, 8 ] private
number of total cell nodes
Definition at line 6054 of file DAMASK_marc.f90.
Referenced by telement_init().
ncellnodepercellface
integer, dimension(maxval(celltype)), parameter element::ncellnodepercellface = [ 2, 2, 3, 4 ] private
number of cell nodes per face
Definition at line 6046 of file DAMASK_marc.f90.
nelemtype
integer, parameter element::nelemtype = 13
Definition at line 5957 of file DAMASK_marc.f90.
nip
integer, dimension(maxval(geomtype)), parameter element::nip = [ 1, 3, 4, 9, 1, 4, 6, 1, 8, 27 ] private
number of IPs
Definition at line 6010 of file DAMASK_marc.f90.
Referenced by telement_init().
nipneighbor
integer, dimension(maxval(celltype)), parameter element::nipneighbor = [ 3, 4, 4, 6 ] private
number of ip neighbors / cell faces
Definition at line 6038 of file DAMASK_marc.f90.
nnode
integer, dimension(nelemtype), parameter element::nnode = [ 3, 6, 4, 8, 8, 4, 5, 10, 6, 8, 8, 20, 20 ] private
number of nodes that constitute a specific type of element
Definition at line 5960 of file DAMASK_marc.f90.
Referenced by telement_init().