DAMASK with MSC.Marc FEM solver: source_thermal_dissipation Module Reference
source_thermal_dissipation Module Reference
material subroutine for thermal source due to plastic dissipation
Data Types
type tparameters
container type for internal constitutive parameters
Functions/Subroutines
subroutine, public source_thermal_dissipation_init
module initialization
subroutine, public source_thermal_dissipation_getrateanditstangent (TDot, dTDot_dT, Tstar, Lp, phase)
Ninstances dissipation rate.
Variables
integer, dimension(:), allocatable source_thermal_dissipation_offset
which source is my current thermal dissipation mechanism?
integer, dimension(:), allocatable source_thermal_dissipation_instance
instance of thermal dissipation source mechanism
type(tparameters), dimension(:), allocatable param
containers of constitutive parameters (len Ninstance)
Detailed Description
material subroutine for thermal source due to plastic dissipation
Author
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
to be done
Function/Subroutine Documentation
source_thermal_dissipation_getrateanditstangent()
subroutine, public source_thermal_dissipation::source_thermal_dissipation_getrateanditstangent (real(preal), intent(out) TDot, real(preal), intent(out) dTDot_dT, real(preal), dimension(3,3), intent(in) Tstar, real(preal), dimension(3,3), intent(in) Lp, integer, intent(in) phase)
Ninstances dissipation rate.
Definition at line 14361 of file DAMASK_marc.f90.
References param, and source_thermal_dissipation_instance.
source_thermal_dissipation_init()
subroutine, public source_thermal_dissipation::source_thermal_dissipation_init
module initialization
reads in material parameters, allocates arrays, and does sanity checks
Definition at line 14320 of file DAMASK_marc.f90.
References config::config_phase, debug::debug_constitutive, debug::debug_level, debug::debug_levelbasic, discretization::discretization_nip, material::material_allocatesourcestate(), material::material_phaseat, param, material::phase_nsources, material::phase_source, material::source_thermal_dissipation_id, source_thermal_dissipation_instance, material::source_thermal_dissipation_label, and source_thermal_dissipation_offset.
Referenced by constitutive::constitutive_init().
Variable Documentation
param
type(tparameters), dimension(:), allocatable source_thermal_dissipation::param private
containers of constitutive parameters (len Ninstance)
Definition at line 14305 of file DAMASK_marc.f90.
Referenced by source_thermal_dissipation_getrateanditstangent(), and source_thermal_dissipation_init().
source_thermal_dissipation_instance
integer, dimension(:), allocatable source_thermal_dissipation::source_thermal_dissipation_instance private
instance of thermal dissipation source mechanism
Definition at line 14296 of file DAMASK_marc.f90.
Referenced by source_thermal_dissipation_getrateanditstangent(), and source_thermal_dissipation_init().
source_thermal_dissipation_offset
integer, dimension(:), allocatable source_thermal_dissipation::source_thermal_dissipation_offset private
which source is my current thermal dissipation mechanism?
Definition at line 14296 of file DAMASK_marc.f90.
Referenced by source_thermal_dissipation_init().