DAMASK with MSC.Marc FEM solver: numerics Module Reference
numerics Module Reference
Managing of parameters related to numerics.
Functions/Subroutines
subroutine, public numerics_init
reads in parameters from numerics.config and sets openMP related parameters. Also does
Variables
integer, public, protected ijacostiffness = 1
frequency of stiffness update
integer, public, protected randomseed = 0
fixed seeding for pseudo-random number generator, Default 0: use random seed
integer, public, protected worldrank = 0
MPI worldrank (/=0 for MPI simulations only)
integer, public, protected worldsize = 1
MPI worldsize (/=1 for MPI simulations only)
integer, public, protected numerics_integrator = 1
method used for state integration Default 1: fix-point iteration
integer(4), public, protected damask_numthreadsint = 0
value stored in environment variable DAMASK_NUM_THREADS, set to zero if no OpenMP directive
real(preal), public, protected defgradtolerance = 1.0e-7_pReal
deviation of deformation gradient that is still allowed (used by CPFEM to determine outdated ffn1)
real(preal), public, protected numerics_unitlength = 1.0_pReal
determines the physical length of one computational length unit
real(preal), public, protected charlength = 1.0_pReal
characteristic length scale for gradient problems
real(preal), public, protected residualstiffness = 1.0e-6_pReal
non-zero residual damage
logical, public, protected usepingpong = .true.
real(preal), public, protected err_struct_tolabs = 1.0e-10_pReal
absolute tolerance for mechanical equilibrium
real(preal), public, protected err_struct_tolrel = 1.0e-4_pReal
relative tolerance for mechanical equilibrium
real(preal), public, protected err_thermal_tolabs = 1.0e-2_pReal
absolute tolerance for thermal equilibrium
real(preal), public, protected err_thermal_tolrel = 1.0e-6_pReal
relative tolerance for thermal equilibrium
real(preal), public, protected err_damage_tolabs = 1.0e-2_pReal
absolute tolerance for damage evolution
real(preal), public, protected err_damage_tolrel = 1.0e-6_pReal
relative tolerance for damage evolution
integer, public, protected itmax = 250
maximum number of iterations
integer, public, protected itmin = 1
minimum number of iterations
integer, public, protected stagitmax = 10
max number of field level staggered iterations
integer, public, protected maxcutback = 3
max number of cut backs
Detailed Description
Managing of parameters related to numerics.
Author
Franz Roters, Max-Planck-Institut für Eisenforschung GmbH
Philip Eisenlohr, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
numerics_init()
subroutine, public numerics::numerics_init
reads in parameters from numerics.config and sets openMP related parameters. Also does
Definition at line 1199 of file DAMASK_marc.f90.
References charlength, defgradtolerance, err_damage_tolabs, err_damage_tolrel, err_struct_tolabs, err_struct_tolrel, err_thermal_tolabs, err_thermal_tolrel, ijacostiffness, io::io_error(), io::io_floatvalue(), io::io_intvalue(), io::io_isblank(), io::io_lc(), io::io_read_ascii(), io::io_stringpos(), io::io_stringvalue(), itmax, itmin, maxcutback, numerics_integrator, numerics_unitlength, randomseed, residualstiffness, stagitmax, and usepingpong.
Referenced by cpfem_initall().
Variable Documentation
charlength
real(preal), public, protected numerics::charlength = 1.0_pReal
characteristic length scale for gradient problems
Definition at line 1158 of file DAMASK_marc.f90.
Referenced by numerics_init().
damask_numthreadsint
integer(4), public, protected numerics::damask_numthreadsint = 0
value stored in environment variable DAMASK_NUM_THREADS, set to zero if no OpenMP directive
Definition at line 1156 of file DAMASK_marc.f90.
defgradtolerance
real(preal), public, protected numerics::defgradtolerance = 1.0e-7_pReal
deviation of deformation gradient that is still allowed (used by CPFEM to determine outdated ffn1)
Definition at line 1158 of file DAMASK_marc.f90.
Referenced by cpfem_general(), and numerics_init().
err_damage_tolabs
real(preal), public, protected numerics::err_damage_tolabs = 1.0e-2_pReal
absolute tolerance for damage evolution
Definition at line 1168 of file DAMASK_marc.f90.
Referenced by numerics_init().
err_damage_tolrel
real(preal), public, protected numerics::err_damage_tolrel = 1.0e-6_pReal
relative tolerance for damage evolution
Definition at line 1168 of file DAMASK_marc.f90.
Referenced by numerics_init().
err_struct_tolabs
real(preal), public, protected numerics::err_struct_tolabs = 1.0e-10_pReal
absolute tolerance for mechanical equilibrium
Definition at line 1168 of file DAMASK_marc.f90.
Referenced by numerics_init().
err_struct_tolrel
real(preal), public, protected numerics::err_struct_tolrel = 1.0e-4_pReal
relative tolerance for mechanical equilibrium
Definition at line 1168 of file DAMASK_marc.f90.
Referenced by numerics_init().
err_thermal_tolabs
real(preal), public, protected numerics::err_thermal_tolabs = 1.0e-2_pReal
absolute tolerance for thermal equilibrium
Definition at line 1168 of file DAMASK_marc.f90.
Referenced by numerics_init().
err_thermal_tolrel
real(preal), public, protected numerics::err_thermal_tolrel = 1.0e-6_pReal
relative tolerance for thermal equilibrium
Definition at line 1168 of file DAMASK_marc.f90.
Referenced by numerics_init().
ijacostiffness
integer, public, protected numerics::ijacostiffness = 1
frequency of stiffness update
Definition at line 1150 of file DAMASK_marc.f90.
Referenced by cpfem_general(), and numerics_init().
itmax
integer, public, protected numerics::itmax = 250
maximum number of iterations
Definition at line 1175 of file DAMASK_marc.f90.
Referenced by numerics_init().
itmin
integer, public, protected numerics::itmin = 1
minimum number of iterations
Definition at line 1175 of file DAMASK_marc.f90.
Referenced by numerics_init().
maxcutback
integer, public, protected numerics::maxcutback = 3
max number of cut backs
Definition at line 1175 of file DAMASK_marc.f90.
Referenced by numerics_init().
numerics_integrator
integer, public, protected numerics::numerics_integrator = 1
method used for state integration Default 1: fix-point iteration
Definition at line 1150 of file DAMASK_marc.f90.
Referenced by crystallite_init(), material::material_allocateplasticstate(), material::material_allocatesourcestate(), and numerics_init().
numerics_unitlength
real(preal), public, protected numerics::numerics_unitlength = 1.0_pReal
determines the physical length of one computational length unit
Definition at line 1158 of file DAMASK_marc.f90.
Referenced by discretization_marc::discretization_marc_init(), and numerics_init().
randomseed
integer, public, protected numerics::randomseed = 0
fixed seeding for pseudo-random number generator, Default 0: use random seed
Definition at line 1150 of file DAMASK_marc.f90.
Referenced by math::math_init(), and numerics_init().
residualstiffness
real(preal), public, protected numerics::residualstiffness = 1.0e-6_pReal
non-zero residual damage
Definition at line 1158 of file DAMASK_marc.f90.
Referenced by numerics_init().
stagitmax
integer, public, protected numerics::stagitmax = 10
max number of field level staggered iterations
Definition at line 1175 of file DAMASK_marc.f90.
Referenced by numerics_init().
usepingpong
logical, public, protected numerics::usepingpong = .true.
Definition at line 1163 of file DAMASK_marc.f90.
Referenced by crystallite_init(), hypela2(), and numerics_init().
worldrank
integer, public, protected numerics::worldrank = 0
MPI worldrank (/=0 for MPI simulations only)
Definition at line 1150 of file DAMASK_marc.f90.
Referenced by hdf5_utilities::initialize_read(), hdf5_utilities::initialize_write(), results::results_mapping_constituent(), and results::results_mapping_materialpoint().
worldsize
integer, public, protected numerics::worldsize = 1
MPI worldsize (/=1 for MPI simulations only)
Definition at line 1150 of file DAMASK_marc.f90.