DAMASK with MSC.Marc FEM solver: results Module Reference
results Module Reference
Data Types
interface results_addattribute
interface results_writedataset
Functions/Subroutines
subroutine, public results_init
subroutine, public results_openjobfile
opens the results file to append data
subroutine, public results_closejobfile
closes the results file
subroutine, public results_addincrement (inc, time)
creates the group of increment and adds time as attribute to the file
subroutine, public results_finalizeincrement
finalize increment
integer(hid_t) function, public results_opengroup (groupName)
open a group from the results file
integer(hid_t) function, public results_addgroup (groupName)
adds a new group to the results file
subroutine, public results_closegroup (group_id)
close a group
subroutine, public results_setlink (path, link)
set link to object in results file
subroutine results_addattribute_str (attrLabel, attrValue, path)
adds a string attribute to an object in the results file
subroutine results_addattribute_int (attrLabel, attrValue, path)
adds an integer attribute an object in the results file
subroutine results_addattribute_real (attrLabel, attrValue, path)
adds a real attribute an object in the results file
subroutine results_addattribute_int_array (attrLabel, attrValue, path)
adds an integer array attribute an object in the results file
subroutine results_addattribute_real_array (attrLabel, attrValue, path)
adds a real array attribute an object in the results file
subroutine, public results_removelink (link)
remove link to an object
subroutine results_writescalardataset_real (group, dataset, label, description, SIunit)
stores a scalar dataset in a group
subroutine results_writevectordataset_real (group, dataset, label, description, SIunit)
stores a vector dataset in a group
subroutine results_writetensordataset_real (group, dataset, label, description, SIunit, transposed)
stores a tensor dataset in a group
subroutine results_writevectordataset_int (group, dataset, label, description, SIunit)
stores a vector dataset in a group
subroutine results_writetensordataset_int (group, dataset, label, description, SIunit)
stores a tensor dataset in a group
subroutine results_writescalardataset_rotation (group, dataset, label, description, lattice_structure)
stores a scalar dataset in a group
subroutine, public results_mapping_constituent (phaseAt, memberAtLocal, label)
adds the unique mapping from spatial position and constituent ID to results
subroutine, public results_mapping_materialpoint (homogenizationAt, memberAtLocal, label)
adds the unique mapping from spatial position and constituent ID to results
Variables
integer(hid_t) resultsfile
Detailed Description
Author
Vitesh Shah, Max-Planck-Institut für Eisenforschung GmbH
Yi-Chin Yang, Max-Planck-Institut für Eisenforschung GmbH
Jennifer Nastola, Max-Planck-Institut für Eisenforschung GmbH
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
results_addattribute_int()
subroutine results::results_addattribute_int (character(len=*), intent(in) attrLabel, integer, intent(in) attrValue, character(len=*), intent(in), optional path) private
adds an integer attribute an object in the results file
Definition at line 8973 of file DAMASK_marc.f90.
References resultsfile.
results_addattribute_int_array()
subroutine results::results_addattribute_int_array (character(len=*), intent(in) attrLabel, integer, dimension(:), intent(in) attrValue, character(len=*), intent(in), optional path) private
adds an integer array attribute an object in the results file
Definition at line 9009 of file DAMASK_marc.f90.
References resultsfile.
results_addattribute_real()
subroutine results::results_addattribute_real (character(len=*), intent(in) attrLabel, real(preal), intent(in) attrValue, character(len=*), intent(in), optional path) private
adds a real attribute an object in the results file
Definition at line 8991 of file DAMASK_marc.f90.
References resultsfile.
results_addattribute_real_array()
subroutine results::results_addattribute_real_array (character(len=*), intent(in) attrLabel, real(preal), dimension(:), intent(in) attrValue, character(len=*), intent(in), optional path) private
adds a real array attribute an object in the results file
Definition at line 9027 of file DAMASK_marc.f90.
References resultsfile.
results_addattribute_str()
subroutine results::results_addattribute_str (character(len=*), intent(in) attrLabel, character(len=*), intent(in) attrValue, character(len=*), intent(in), optional path) private
adds a string attribute to an object in the results file
Definition at line 8956 of file DAMASK_marc.f90.
References resultsfile.
results_addgroup()
integer(hid_t) function, public results::results_addgroup (character(len=*), intent(in) groupName)
adds a new group to the results file
Definition at line 8920 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_addgroup(), and resultsfile.
Referenced by constitutive::constitutive_results(), crystallite_results(), discretization::discretization_results(), homogenization::homogenization_results(), results_addincrement(), results_init(), and discretization_marc::writegeometry().
results_addincrement()
subroutine, public results::results_addincrement (integer, intent(in) inc, real(preal), intent(in) time)
creates the group of increment and adds time as attribute to the file
Definition at line 8878 of file DAMASK_marc.f90.
References results_addgroup(), results_closegroup(), and results_setlink().
Referenced by cpfem_forward().
results_closegroup()
subroutine, public results::results_closegroup (integer(hid_t), intent(in) group_id)
close a group
Definition at line 8932 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_closegroup().
Referenced by constitutive::constitutive_results(), crystallite_results(), discretization::discretization_results(), homogenization::homogenization_results(), results_addincrement(), results_init(), and discretization_marc::writegeometry().
results_closejobfile()
subroutine, public results::results_closejobfile
closes the results file
Definition at line 8868 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_closefile(), and resultsfile.
Referenced by cpfem_results(), material::material_init(), results_init(), and discretization_marc::writegeometry().
results_finalizeincrement()
subroutine, public results::results_finalizeincrement
finalize increment
remove soft link
Definition at line 8898 of file DAMASK_marc.f90.
References results_removelink().
Referenced by cpfem_results().
results_init()
subroutine, public results::results_init
Definition at line 8833 of file DAMASK_marc.f90.
References damask_interface::getsolverjobname(), hdf5_utilities::hdf5_openfile(), results_addgroup(), results_closegroup(), results_closejobfile(), and resultsfile.
Referenced by cpfem_initall().
results_mapping_constituent()
subroutine, public results::results_mapping_constituent (integer, dimension(:,:), intent(in) phaseAt, integer, dimension(:,:,:), intent(in) memberAtLocal, character(len=pstringlen), dimension(:), intent(in) label)
adds the unique mapping from spatial position and constituent ID to results
Parameters
[in] phaseat phase section at (constituent,element)
[in] memberatlocal phase member at (constituent,IP,element)
[in] label label of each phase section
Definition at line 9259 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_closegroup(), results_opengroup(), and numerics::worldrank.
Referenced by material::material_init().
results_mapping_materialpoint()
subroutine, public results::results_mapping_materialpoint (integer, dimension(:), intent(in) homogenizationAt, integer, dimension(:,:), intent(in) memberAtLocal, character(len=pstringlen), dimension(:), intent(in) label)
adds the unique mapping from spatial position and constituent ID to results
Parameters
[in] homogenizationat homogenization section at (element)
[in] memberatlocal homogenization member at (IP,element)
[in] label label of each homogenization section
Definition at line 9385 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_closegroup(), results_opengroup(), and numerics::worldrank.
Referenced by material::material_init().
results_opengroup()
integer(hid_t) function, public results::results_opengroup (character(len=*), intent(in) groupName)
open a group from the results file
Definition at line 8908 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_opengroup(), and resultsfile.
Referenced by results_mapping_constituent(), results_mapping_materialpoint(), results_writescalardataset_real(), results_writescalardataset_rotation(), results_writetensordataset_int(), results_writetensordataset_real(), results_writevectordataset_int(), and results_writevectordataset_real().
results_openjobfile()
subroutine, public results::results_openjobfile
opens the results file to append data
Definition at line 8858 of file DAMASK_marc.f90.
References damask_interface::getsolverjobname(), hdf5_utilities::hdf5_openfile(), and resultsfile.
Referenced by cpfem_forward(), geometry_plastic_nonlocal::geometry_plastic_nonlocal_results(), material::material_init(), and discretization_marc::writegeometry().
results_removelink()
subroutine, public results::results_removelink (character(len=*), intent(in) link)
remove link to an object
Definition at line 9045 of file DAMASK_marc.f90.
References resultsfile.
Referenced by results_finalizeincrement().
results_setlink()
subroutine, public results::results_setlink (character(len=*), intent(in) path, character(len=*), intent(in) link)
set link to object in results file
Definition at line 8944 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_setlink(), and resultsfile.
Referenced by results_addincrement().
results_writescalardataset_real()
subroutine results::results_writescalardataset_real (character(len=*), intent(in) group, real(preal), dimension(:), intent(inout) dataset, character(len=*), intent(in) label, character(len=*), intent(in) description, character(len=*), intent(in), optional SIunit) private
stores a scalar dataset in a group
Definition at line 9059 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_closegroup(), hdf5_utilities::hdf5_objectexists(), and results_opengroup().
results_writescalardataset_rotation()
subroutine results::results_writescalardataset_rotation (character(len=*), intent(in) group, type(rotation), dimension(:), intent(inout) dataset, character(len=*), intent(in) label, character(len=*), intent(in) description, character(len=*), intent(in), optional lattice_structure) private
stores a scalar dataset in a group
Definition at line 9229 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_closegroup(), hdf5_utilities::hdf5_objectexists(), and results_opengroup().
results_writetensordataset_int()
subroutine results::results_writetensordataset_int (character(len=*), intent(in) group, integer, dimension(:,:,:), intent(inout) dataset, character(len=*), intent(in) label, character(len=*), intent(in) description, character(len=*), intent(in), optional SIunit) private
stores a tensor dataset in a group
Definition at line 9199 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_closegroup(), hdf5_utilities::hdf5_objectexists(), and results_opengroup().
results_writetensordataset_real()
subroutine results::results_writetensordataset_real (character(len=*), intent(in) group, real(preal), dimension(:,:,:), intent(in) dataset, character(len=*), intent(in) label, character(len=*), intent(in) description, character(len=*), intent(in), optional SIunit, logical, intent(in), optional transposed) private
stores a tensor dataset in a group
Definition at line 9118 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_closegroup(), hdf5_utilities::hdf5_objectexists(), and results_opengroup().
results_writevectordataset_int()
subroutine results::results_writevectordataset_int (character(len=*), intent(in) group, integer, dimension(:,:), intent(inout) dataset, character(len=*), intent(in) label, character(len=*), intent(in) description, character(len=*), intent(in), optional SIunit) private
stores a vector dataset in a group
Definition at line 9169 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_closegroup(), hdf5_utilities::hdf5_objectexists(), and results_opengroup().
results_writevectordataset_real()
subroutine results::results_writevectordataset_real (character(len=*), intent(in) group, real(preal), dimension(:,:), intent(inout) dataset, character(len=*), intent(in) label, character(len=*), intent(in) description, character(len=*), intent(in), optional SIunit) private
stores a vector dataset in a group
Definition at line 9088 of file DAMASK_marc.f90.
References hdf5_utilities::hdf5_closegroup(), hdf5_utilities::hdf5_objectexists(), and results_opengroup().
Variable Documentation
resultsfile
integer(hid_t) results::resultsfile private
Definition at line 8789 of file DAMASK_marc.f90.
Referenced by results_addattribute_int(), results_addattribute_int_array(), results_addattribute_real(), results_addattribute_real_array(), results_addattribute_str(), results_addgroup(), results_closejobfile(), results_init(), results_opengroup(), results_openjobfile(), results_removelink(), and results_setlink().