DAMASK with MSC.Marc FEM solver: rotations::rotation Type Reference
rotations::rotation Type Reference
Public Member Functions
procedure, public asquaternion
procedure, public aseulers
procedure, public asaxisangle
procedure, public asrodrigues
procedure, public asmatrix
procedure, public fromquaternion
procedure, public fromeulers
procedure, public fromaxisangle
procedure, public frommatrix
generic, public operator => rotrot__
generic, public rotate => rotvector, rottensor2, rottensor4
procedure, public rotvector
procedure, public rottensor2
procedure, public rottensor4
procedure, public rottensor4sym
procedure, public misorientation
procedure, public standardize
Private Member Functions
procedure, private rotrot__
Private Attributes
type(quaternion), private q
Detailed Description
Definition at line 4614 of file DAMASK_marc.f90.
Member Function/Subroutine Documentation
asaxisangle()
procedure, public rotations::rotation::asaxisangle
Definition at line 4619 of file DAMASK_marc.f90.
aseulers()
procedure, public rotations::rotation::aseulers
Definition at line 4618 of file DAMASK_marc.f90.
asmatrix()
procedure, public rotations::rotation::asmatrix
Definition at line 4621 of file DAMASK_marc.f90.
asquaternion()
procedure, public rotations::rotation::asquaternion
Definition at line 4617 of file DAMASK_marc.f90.
asrodrigues()
procedure, public rotations::rotation::asrodrigues
Definition at line 4620 of file DAMASK_marc.f90.
fromaxisangle()
procedure, public rotations::rotation::fromaxisangle
Definition at line 4625 of file DAMASK_marc.f90.
fromeulers()
procedure, public rotations::rotation::fromeulers
Definition at line 4624 of file DAMASK_marc.f90.
frommatrix()
procedure, public rotations::rotation::frommatrix
Definition at line 4626 of file DAMASK_marc.f90.
fromquaternion()
procedure, public rotations::rotation::fromquaternion
Definition at line 4623 of file DAMASK_marc.f90.
misorientation()
procedure, public rotations::rotation::misorientation
Definition at line 4635 of file DAMASK_marc.f90.
operator()
generic, public rotations::rotation::operator
Definition at line 4629 of file DAMASK_marc.f90.
References rotations::rotrot__().
rotate()
generic, public rotations::rotation::rotate
Definition at line 4630 of file DAMASK_marc.f90.
References rotations::rottensor2(), rotations::rottensor4(), and rotations::rotvector().
rotrot__()
procedure, private rotations::rotation::rotrot__ private
Definition at line 4628 of file DAMASK_marc.f90.
rottensor2()
procedure, public rotations::rotation::rottensor2
Definition at line 4632 of file DAMASK_marc.f90.
rottensor4()
procedure, public rotations::rotation::rottensor4
Definition at line 4633 of file DAMASK_marc.f90.
rottensor4sym()
procedure, public rotations::rotation::rottensor4sym
Definition at line 4634 of file DAMASK_marc.f90.
rotvector()
procedure, public rotations::rotation::rotvector
Definition at line 4631 of file DAMASK_marc.f90.
standardize()
procedure, public rotations::rotation::standardize
Definition at line 4636 of file DAMASK_marc.f90.
References rotations::eu2om(), and rotations::rotations_init().
Member Data Documentation
q
type(quaternion), private rotations::rotation::q private
Definition at line 4615 of file DAMASK_marc.f90.
The documentation for this type was generated from the following file:
DAMASK_marc.f90