6       header
# Generated by DREAM.3D
grid    a 32    b 32    c 32
size    x 352.000    y 352.000    z 352.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 32768
1 to      32768