6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        32         22         11         51         18         34         37         57         49         50
        44          5          8         20         60         59         21         30         42         28
         2         29         39         19         13         12         62         38         56         41
        24          6         53         40          9         36         46          7         55         15
         1         27         47         16         31         64         33          3          4         52
        35         45         23         63         26         10         54         61         25         43
        14         58         48         17