6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        48         30         35         39         59         33         37         46         45         20
        49         29         43         34          7         25         56         40         54         42
        60          4         14         52         53         24         27         55         41         23
        10          2         36          1         12         64         44         50         15         47
        62         31         28         16         26         11         21         58         57         63
         8          5         18         32         61          3         17          6         13         51
        22         38          9         19