6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         7         41         32         53         45          8          2         61         38         49
         3         43          9         15         35         40         39         10         60         30
        64         18         54         50         42         27         52         14         23          1
        21         34         63         57         19         16         12         33         51         11
         4         26         44         13          6         59         28         46         62          5
        20         29         22         55         17         24         37         47         56         36
        31         48         25         58