6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         2          9         19         31         23         40         62         49          6         50
        17          3         30         12         46         11         13          7         52         64
        14         28         20         15         16         32         44         38         34         27
         5         48         51          1         37         56         39         29         22         25
        26         53         55         24         18         54         41          8         43         33
         4         36         58         21         60         63         57         59         47         61
        10         42         35         45