6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        23         46         35          6         38         26         53         36          5         43
        14         11         51         21         54         58         32         34          2         57
        27         48         28          1         63         52         55         64         31         41
        40         60          4         37          9         50         59          3         18         25
        47         12         17         13         20         10         42         39         22         19
        45         24         15         29         44         30          7         61         62         56
        49         16         33          8