6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        61         51         39         13         34         23         35         62         49         12
        27         20         42         14         43          2         47         41          8         33
        59         44         48         31         53         28         55         19         58         15
        40         30         45         57         21         64         38          5         50         37
         4         17         56         60         10         36         22          7          6         52
        46         63         54          3         24         29         18         32          9         25
        11          1         16         26