6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        47         17         26          2          4         35         44         54         50         37
        58         46         21         30         11         51         27         31         25         55
        43         63         19         56         22         32         10         40         23         64
         9          8         61         36         48         53          5         45         13         57
        29         12          1         52         14          7         49         20         39         59
        18         62         60         28         41         34          3         42         24         15
        33         16          6         38