6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        15          5         40         31         11         33         61          4         25         59
        51         18         22         41         10         13          6          2         63         17
        58         56         38          1         39         12          7         52         55         28
        19         30         50         29         57         35         42          8          9         60
        64         49         48         53         14         62         34         54         47         23
        16          3         37         45         24         32         27         20         44         46
        26         36         43         21