6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        41          3         20         13         56         30         44         25         31         24
        28         19         52         50          1         37          4         18          9         17
        57         14         61         63         29         53         35         11         60         27
        64         38         34         49         40         59         12         45         32         39
         5         15          8         36         48         22         46         58         54         10
        21         43         55         23         42         62          7         26         51          2
         6         16         47         33