6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        56         11         21         15         61          3         12         17         45         27
        20         60         49         10          4         34         46         47         16         62
        32         30         50         41         42          9         28         31         43         36
        44          1         25         29          7         24         14          5         63         51
        64         37         33         55         19          6         35         39         26          8
        18         23         13         22         38         54         57         52          2         59
        53         40         48         58