6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        39         35         32         23         59         18          3         12         46         38
        33         31          7          1         29         22         63         11          5         34
        48         17         55         64         25         19         41         49         13         20
        37          4         45          2         47         40          8          6         15         56
        27         62         10         43         58         42         52         54         51         28
        14          9         60         44         61         30         36         21         53         50
        57         16         24         26