6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        22         58          9          8         32         11          3         41         12         46
        33         17          5          4         29         20         49         13         53         43
         1         59         23         42         48         50         63         21         24         35
        60         25         28         45         47         27         26         54         19         44
        57         64          6         52          7         10         62         38         36          2
        56         31         15         14         34         30         37         51         18         61
        55         16         40         39