6       header
# Generated by DREAM.3D
grid    a 2    b 2    c 2
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 8
         5          4          1          7          6          8          3          2