6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        14         36          1         53         34         15         28          3         20         19
         8         50         38         57         63         17         49         32         58         23
         6         47          2         62          9         44         24         64         48         13
        33         41         16         51         37         31         22         45         25         52
        54         21         29         26         10          7         55         59         30         40
        12          4         39         18          5         60         56         27         35         43
        11         46         42         61