6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        21         53         22         45         42         15         13         43         50         37
        25         16         47         54          4         63          6         52         26         38
        34         18          5          1         30         28         32         51          2         60
        12         20         27         23         48         36         58         64         10         39
         3         29         44         46         55         31         40         62         59         33
        49         41         11          8          7          9         14         35         24         61
        56         57         19         17