6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         3         21         24         17         23         18         38         34         32         47
        37          9         31         30         53         14         25         11         52         51
        46         62         45          6         44         20         55          4         15         54
        36          2         50         43         12         61         27         16         35         42
        26          8         10         57         56         19         39         48         58          7
        22         49         64         29          5         63          1         59         28         41
        60         33         40         13