6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        20         63         24         60         58          4         48         40         52          2
        35         56         49         34          3         41         61         12         62         18
        16         14          9         42         33         11         28         23         47         64
        19         30         51         31          6         32         43         57         21          1
        45         17         38         15         39         36         59         10         29          5
        26         27         53         46         54         25         22         50          8         37
         7         44         13         55