6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        46         32         34         39         44         43          7         25         33         17
        11          1         45         58         40         19          2         49         28         52
        23         27         63         24          5         10         30         55         35         61
        22          3         47         59          8         53         14         41         26         56
        42         37         62         51         54         29          4         57         21         13
        15          6         48         12         50         64          9         60         16         36
        20         38         31         18