6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        40         49         14         50         38         45         20         25         51         35
        32         28         58         43         54          9         11          6         34         62
        27         26         18         46         64         59         56         39         63          8
        22         10         44         57         17         42         33         24         16         31
        41         48         47          1         13         53         52         36         60         19
         7         30          5         29         23         55         21         61         37          4
        15         12          2          3