6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        33         58         64         25         56         41         42         61         12          4
         7         59         18         36         19         54         13         49          1         10
        26         35         57         30         16         39         48          9         21         28
        15         47         52         43         46         34          3         31         29          2
        11         14         44          8         22         63         55         40         62         38
        32         17         24          6         37         60         23          5         20         53
        27         51         50         45