6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         8         48          3         15         28         30         34          9         60         26
        37         56         22          5         31          1         39         62         61         10
        16         33         12         40         24         63         41          6         32         51
        53         20         50         43          2         44         13         57         49         47
        25         17         64         59         21         36         18         27         23         55
         7         38         29         14         11         58         54         42         52         45
        35         19         46          4