6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         1         59         64         16         61          5         41         22         50         46
        32         52         20         58         42         44          7         31         40         43
        39         47         55         24         28         21         33         63         14         18
        29          6         35         13         62          2         25         11         45         17
        48         57         34         56         10         54         36         15         51         27
        49          8         38         37         60         26         23          4         12          9
        30          3         19         53