6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        34         63         23          7         57         53         12         36         49         31
        10         14         45         61         20         21         15         60         41         43
        33         29         24         40         35          4         58          2         18         39
        17         64          8         51         16         38         62         25         11         27
        28         42          1         22         47         19         54         44         50         55
        46          3          9         13         32         30          5         59         48         56
        26         37          6         52