6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        16         47         63         43         39         42         21         55         45         11
         4         12         27         44         52          7         17         25          9         29
        26         53         24         30         41         10         28         57         22          6
        60         49         64         61         32         23         19         51         13         50
         1         40         34         59         62         38         46         14          5         33
        58          3         37         20         15         18          8         31         35         48
        56          2         54         36