6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        41         15         58          2         42         29         44          3         20         13
        21         27         43         59         17         49         19         57         11         64
        22          8         33         25         46         54         23         50         60         48
        63         16          5         56         37         14         26         10         47         12
        35         61         39         36         52         62         53         24         30         32
         7          6         28         40          1          9          4         51         34         45
        18         38         31         55