6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        17         60         21         36          2         28         52         47         14         49
        40         61         59         12         16          1         32         29         53         37
        13          7         25         54         20         10          5         57         41          9
        64         11         35         50         62         22         27         23         55          3
        26         44         63         33         15         45         34         39          8         56
        42          4         38         46         43         30         18         19         51         31
        58         48          6         24