6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        37         41          3         56         30         33         32         59          4         44
        60          6         58         27         28         43          1         31          5         14
        48         10         45         47         19         29         23         36         34          8
        54         26          9         63         62         17         39         49         51         52
        35         57         46         64         15         21         13         40         18         53
        24         22         25         16          7         11         50          2         38         55
        20         61         12         42