6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        16         37         51         46         30         35         41          7         54         63
        14         29         64         15         18         13         32          1         58         38
        27         45         40         11         21          6         52         34          2         23
        19          9         47          5          3         62         22         39         25         50
        26          8         53         24          4         60         48         12         57         49
        43         28         55         44         17         31         59         36         20         42
        56         33         61         10