6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        10         11          9         43         34         46         52         45         49         17
        53         39         32         56         38          7         54         33         62         27
        42         47          8         29         18         16         37          5         24         14
        57         22         35          2         12         44          1          3         61         31
        58         64          6         48         60          4         25         21         55         51
        13         50         30         63         23         40         15         19         26         28
        20         36         41         59