6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        16         21         51         41         29          9         36         38          3         32
        15         35         39         34         62         24         58         17          1         30
        54         40         48          8          2         44          6         12         55         60
        23         18         45         27         25         46         22         20          4         31
        56         64         10         61         19         26         43         57         53         59
        63         13         50         52         33         28         14         11          5         37
        47         42         49          7