6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        15         30         48         50         64          4         18         58         19         28
        29         59         63          8          7         56         32         24         53         21
        55         61         12         36         14         23         34          3         54         43
        22         37         42         16          2         11         57         47         33         60
        45         38         20         25          6         49          9         44          1         39
        26         40         10         27         35         41         52         46         31         51
         5         62         17         13