6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        55         63         32         61         28         27         42         12         51         43
        29          8         46         50          1         52         26         21         64         38
        30         45         39         41         57         58         33         34         24         54
        17         59         11          5         56          9         22         36         18          3
        31         16          2          4         47         48         10         20         15         37
        62         14          6          7         49         60         13         44         35         53
        19         40         25         23