6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        42         31          1         57         12         55         22         10         32         38
        48         49         61         41         34         19         47         29         13          6
        35         16         30         37          8          9         50         36         60         27
        54         62         20         24         43         56         45          7          4         28
         3         52         21         59          5         64         33         23         53         46
        14         15         18          2         58         11         51         25         40         26
        39         17         63         44