6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        60         42         23         36         58         54         41         19         46         51
        57         55         20         52          4         61         44         64         10          9
         6          8         14         18         24          2         53         48         56         29
        12          7         59         22          1         38         17         28         33         50
        11         47          5         49         35         45         62         13         39          3
        63         43         27         15         30         21         32         40         16         37
        34         25         31         26