6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         2          4         38         29         23         52         41         17         56          5
        42         44         25         32         59         33         10         18         13         51
         1         45          3         48         64         34         36         28         16         54
        30         47         14          9         40         60         20         21         26         57
        22         61          7         37         62         50         55         11         43         39
        58         15         63         46          6         35         27         24          8         31
        12         53         19         49