6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        17         63         54         13         47         42         34         53         57          2
         5         46         59         27         28         12         50         25         15         18
         7         23          6         10          4          8         43         39         21         19
        48         32         37         55         14         35         36         49         60         31
         3         58          1         40         38         33         24         61         20         16
        30         62         45         52         56         22         11         64         51         41
         9         44         26         29