6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         1         60         23          7         57         40         16         58         51         28
        25         59         54         45         63         22         38         20         49          6
         8         36         52         47         55         35         37         41         48         12
         3         56         53         26         21          2         27         19         39         24
        50         31         44         14         30         42         62         64         11          4
        32         18          5          9         34         46         61         29         43         13
        33         15         10         17