6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         4          2         60         21         12         51         34         23         29         54
         3         32          5         16         19         15         42         27         33         57
        64         22         45         48          7         50         53         31          1         18
        37         36         59         28         58         41          9         56         26         44
        10         11          8         52         55         38          6         43         63         14
        24         62         13         30         17         35         40         61         20         25
        46         39         47         49