6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        51         10         30         53         44         56         60         48         11         13
        37         64         22          8         39         57         47         38         21          2
        24         42         59          1         34         19         55         62          6          5
        43         31         25         26         45         35          4         58         20         15
        46         17         61         50          7         32         18         63         12         14
        54         29         49         36         33         16         41          3         40         28
        23          9         52         27