6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        10         35         23         22          9          5         53         33         11          3
        25         16          2         63         36         13         64         30         44         51
        61         43         18         20         62         39         59         17         40         56
        58         26         27         32         60         42         55         31          6         49
        14         45         37         54         28          8         21         19         46         24
         4         34         29         48          1         50         15         41         47          7
        52         57         38         12