6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        14          9         21         37         13         44         15         51         49         42
        30         36         52         64         41         61         54         35         56         32
        34         19          3         23         10          6         12         22         17          4
        60          2         47         55         45         26         38          7         11         50
        63         25         28          1         20         18         16         46          8          5
        40         27         59         31         43         58         48         53         24         39
        57         33         62         29