6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        63          7         27         47         30         55         45         57         24         41
        62         36          3         58         54         15         13          8         49         60
        37         16          1          6         39         28         19         23         10         32
        43         20         53         42          5          4         34         12         51         22
        35         64         31         14         61         25         59         56         26         50
        21         46         48         17         29         18         38          9          2         11
        40         52         33         44