6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        61          3         34         30         31         59         14         28         53          2
        54          7         13         45         57         33         17         24          9          5
        42         51         50         43         35         21          6         64          1         60
        41         62         27         10          4         46         19         15         29         36
        20         39         16         22         44         37         56         52         23         49
        55         63          8         18         11         48         40         26         58         47
        38         25         12         32