6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        22         45         59         46         43          4         16         57         31         15
        30         11         39         35         19         37         12         62          7         24
        56         17         38         50         52         23         61         40         44         42
        34         20          2          8         41         48         21         60         33          1
        63         29         18         54         58         55         36          9         64         14
        49         28         51         47          3         10         27         25          5         26
        53         13          6         32