6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        50         27         30         26         58         34         36         62         17         61
        22         42         51          2         38         15         63         33          6         24
        47         39         52          5         41         53         43         49         11         37
        48         23         25         28         60         45         46         12          4         56
         8         40         55         18         35         44         29         16          7         19
        20          3         13         57         10         32          1         59          9         31
        14         54         64         21