6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        15         34         54         43         53         27         32         44         40         41
        23         14          7         24         48          9         61         29         18         60
        10         55         25         58         56         50         28         11         30         36
        39         17         57         46         16         45         42         21         33         19
        22         52          4         51         49         64         47          6          2         38
        59         62          1          3         31         26         20          8         12         35
         5         13         37         63