6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        34         17         58         16          4         51         10         60         13         31
        64         24         61         59         39         36          2         47         49         53
        45         57         30          1         35          9         46         43         27         44
        56         50         23          5         14         18          6         33         32         62
        29         21         63         22         11         20          3         40          7         52
        12         41         37         54         42         55          8         28         38         15
        26         19         48         25