6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        40         47         37         20         15          5         57         31         64         35
        52         58          8         38         29         62         53         60         19         21
        26         44          1         49         10         63          9         28         41         51
        55         46         18         24         32         34         54         13         17         45
         2         22         56         48         33         23          7         27         61         36
         4         59         14         12          6         16         43         50         39          3
        25         30         42         11