6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        34         13         30         51         44         16         62         38         11         33
        36         31         40         45         63         50          9          4         24         28
         3         55         41         64         43         19         49         57         42         21
        27         20         14         12         54         61         32         56         29          8
         7         23         59          2         47          6          1         10         48         46
        18         39         52          5         26         37         22         17         58         35
        53         60         25         15