6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        12         55         37         34         16         60         39          6          2         40
         4         20         29         54         17         41         23         18          9         21
         8         22         57         26         59         10         43         62          1         38
        45         61         11         19         44         56         51          7         33         47
        64         30         13         53         50         52          3         49          5         58
        25         27         36         48         28         46         24         63         32         14
        35         15         42         31