6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        33         35         45         32          6         16         15         46         44          3
        49         40         43         21          8         37         56         36         48         39
         4         53         17         30         14          9         50         12         11         54
        27         47         59         52         24         10         31         19         13         51
        41         22          2          5         20         23         29         60         34         63
        25         61         57         38         58          7          1         62         18         55
        26         42         28         64