6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        31          2          7         12         56         51         42         32         10         13
        29         55         21         39         63         60         50          1         26         43
        41         47         48         30         25         34         24         52         11         22
        15         14         23         17         62          5         54         59         33         44
        18         36         40         19          4         58         35         57         53         46
        38         45         20          3         64         37         16          6         61          9
        27          8         28         49