6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        15         60         16         42         23         48         64         31         27         43
        54         19         17         56          3          1         49         40          9         25
        26          6         28         57         35         61         20         13         50         41
        21         51         14         12         33         30         59          2         38         11
        36         32         18          5         10         58          4         37         22         44
        62          8         24         39         63          7         34         45         46         55
        29         52         47         53