6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         3         24          2         34         64          1         58          7         57         35
         5         41         59         11         32         55          4         31          8         27
        39         44         13         47         17         46         52         15         61         14
        48         26          9         60         63         23         56         29         40         21
        45         16         51         25         50         54         49         20         18         36
        42         10         19         22         38         62          6         53         30         28
        43         33         37         12