6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         2          7         40         46         34         27         41          5         59         64
        25         33         56         32         38         10         45         49         13          4
        18         48         35         37          8         43         50         52         15          9
        53         31         24         39         29         63         19         42          3         11
        17         12         51         55          6         20         61         16         14         60
        44         22         47         62         21         36         28          1         54         23
        30         58         26         57