DAMASK with grid solvers: config.f90 File Reference
config.f90 File Reference
Modules
module config
Reads in the material configuration from file.
Functions/Subroutines
subroutine, public config::config_init
reads material.config and stores its content per part
recursive character(len=pstringlen) function, dimension(:), allocatable read_materialconfig (fileName, cnt)
reads material.config Recursion is triggered by "{path/to/inputfile}" in a line
subroutine parse_materialconfig (sectionNames, part, line, fileContent)
parses the material.config file
subroutine parse_debugandnumericsconfig (config_list, fileContent)
parses the material.config file
subroutine, public config::config_deallocate (what)
deallocates the linked lists that store the content of the configuration files
Variables
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config::config_phase
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config::config_microstructure
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config::config_homogenization
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config::config_texture
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config::config_crystallite
type(tpartitionedstringlist), public, protected config::config_numerics
type(tpartitionedstringlist), public, protected config::config_debug
character(len=pstringlen), dimension(:), allocatable, public, protected config::config_name_phase
name of each phase
character(len=pstringlen), dimension(:), allocatable, public, protected config::config_name_homogenization
name of each homogenization
character(len=pstringlen), dimension(:), allocatable, public, protected config::config_name_crystallite
name of each crystallite setting
character(len=pstringlen), dimension(:), allocatable, public, protected config::config_name_microstructure
name of each microstructure
character(len=pstringlen), dimension(:), allocatable, public, protected config::config_name_texture
name of each texture
Function/Subroutine Documentation
parse_debugandnumericsconfig()
subroutine config_init::parse_debugandnumericsconfig (type(tpartitionedstringlist), intent(out) config_list, character(len=pstringlen), dimension(:), intent(in) fileContent) private
parses the material.config file
Definition at line 272 of file config.f90.
Referenced by config::config_init().
parse_materialconfig()
subroutine config_init::parse_materialconfig (character(len=pstringlen), dimension(:), intent(out), allocatable sectionNames, type(tpartitionedstringlist), dimension(:), intent(inout), allocatable part, character(len=pstringlen), intent(inout) line, character(len=pstringlen), dimension(:), intent(in) fileContent) private
parses the material.config file
Definition at line 220 of file config.f90.
References io::io_error(), and io::io_gettag().
Referenced by config::config_init().
read_materialconfig()
recursive character(len=pstringlen) function, dimension(:), allocatable config_init::read_materialconfig (character(len=*), intent(in) fileName, integer, intent(in), optional cnt) private
reads material.config Recursion is triggered by "{path/to/inputfile}" in a line
Parameters
[in] filename name of the material configuration file
[in] cnt recursion counter
Returns
file content, separated per lines
Definition at line 138 of file config.f90.
References io::io_eol, io::io_error(), io::io_warning(), and prec::pstringlen.
Referenced by config::config_init().