DAMASK with grid solvers: DAMASK_grid.f90 File Reference
DAMASK_grid.f90 File Reference
Functions/Subroutines
program damask_spectral
Driver controlling inner and outer load case looping of the various spectral solvers.
Function/Subroutine Documentation
damask_spectral()
program damask_spectral
Driver controlling inner and outer load case looping of the various spectral solvers.
Author
Pratheek Shanthraj, Max-Planck-Institut f端r Eisenforschung GmbH
Martin Diehl, Max-Planck-Institut f端r Eisenforschung GmbH
Philip Eisenlohr, Max-Planck-Institut f端r Eisenforschung GmbH
doing cutbacking, forwarding in case of restart, reporting statistics, writing results
Definition at line 13 of file DAMASK_grid.f90.
References config::config_numerics, cpfem2::cpfem_forward(), cpfem2::cpfem_initall(), cpfem2::cpfem_restartwrite(), cpfem2::cpfem_results(), material::damage_nonlocal_id, material::damage_type, debug::debug_level, debug::debug_levelbasic, debug::debug_spectral, prec::dneq(), spectral_utilities::field_damage_id, spectral_utilities::field_mech_id, spectral_utilities::field_thermal_id, damask_interface::getsolverjobname(), grid_damage_spectral::grid_damage_spectral_forward(), grid_damage_spectral::grid_damage_spectral_init(), grid_damage_spectral::grid_damage_spectral_solution(), grid_mech_fem::grid_mech_fem_forward(), grid_mech_fem::grid_mech_fem_init(), grid_mech_fem::grid_mech_fem_restartwrite(), grid_mech_fem::grid_mech_fem_solution(), grid_mech_fem::grid_mech_fem_updatecoords(), grid_mech_spectral_basic::grid_mech_spectral_basic_forward(), grid_mech_spectral_basic::grid_mech_spectral_basic_init(), grid_mech_spectral_basic::grid_mech_spectral_basic_restartwrite(), grid_mech_spectral_basic::grid_mech_spectral_basic_solution(), grid_mech_spectral_basic::grid_mech_spectral_basic_updatecoords(), grid_mech_spectral_polarisation::grid_mech_spectral_polarisation_forward(), grid_mech_spectral_polarisation::grid_mech_spectral_polarisation_init(), grid_mech_spectral_polarisation::grid_mech_spectral_polarisation_restartwrite(), grid_mech_spectral_polarisation::grid_mech_spectral_polarisation_solution(), grid_mech_spectral_polarisation::grid_mech_spectral_polarisation_updatecoords(), grid_thermal_spectral::grid_thermal_spectral_forward(), grid_thermal_spectral::grid_thermal_spectral_init(), grid_thermal_spectral::grid_thermal_spectral_solution(), grid_mech_fem::incinfo, damask_interface::interface_restartinc, io::io_error(), io::io_floatvalue(), io::io_intvalue(), io::io_isblank(), io::io_lc(), io::io_read_ascii(), io::io_stringpos(), io::io_stringvalue(), io::io_warning(), damask_interface::loadcasefile, math::math_9to33(), math::math_i3, prec::preal, quit(), material::thermal_conduction_id, material::thermal_type, prec::tol_math_check, and spectral_utilities::utilities_init().