DAMASK with grid solvers: config Module Reference
config Module Reference
Reads in the material configuration from file.
Functions/Subroutines
subroutine, public config_init
reads material.config and stores its content per part
subroutine, public config_deallocate (what)
deallocates the linked lists that store the content of the configuration files
Variables
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config_phase
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config_microstructure
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config_homogenization
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config_texture
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config_crystallite
type(tpartitionedstringlist), public, protected config_numerics
type(tpartitionedstringlist), public, protected config_debug
character(len=pstringlen), dimension(:), allocatable, public, protected config_name_phase
name of each phase
character(len=pstringlen), dimension(:), allocatable, public, protected config_name_homogenization
name of each homogenization
character(len=pstringlen), dimension(:), allocatable, public, protected config_name_crystallite
name of each crystallite setting
character(len=pstringlen), dimension(:), allocatable, public, protected config_name_microstructure
name of each microstructure
character(len=pstringlen), dimension(:), allocatable, public, protected config_name_texture
name of each texture
Detailed Description
Reads in the material configuration from file.
Author
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
Reads the material configuration file, where solverJobName.materialConfig takes precedence over material.config. Stores the raw strings and the positions of delimiters for the parts 'homogenization', 'crystallite', 'phase', 'texture', and 'microstucture' Reads numerics.config and debug.config
Function/Subroutine Documentation
config_deallocate()
subroutine, public config::config_deallocate (character(len=*), intent(in) what)
deallocates the linked lists that store the content of the configuration files
Definition at line 290 of file config.f90.
References config_debug, config_homogenization, config_microstructure, config_numerics, config_phase, config_texture, and io::io_error().
Referenced by crystallite::crystallite_init(), homogenization::homogenization_init(), and material::material_init().
config_init()
subroutine, public config::config_init
reads material.config and stores its content per part
Definition at line 51 of file config.f90.
References config_crystallite, config_debug, config_homogenization, config_microstructure, config_name_crystallite, config_name_homogenization, config_name_microstructure, config_name_phase, config_name_texture, config_numerics, config_phase, config_texture, debug::debug_level, debug::debug_levelbasic, debug::debug_material, damask_interface::getsolverjobname(), io::io_error(), io::io_gettag(), io::io_lc(), io::io_read_ascii(), parse_debugandnumericsconfig(), parse_materialconfig(), and read_materialconfig().
Referenced by cpfem2::cpfem_initall().
Variable Documentation
config_crystallite
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config::config_crystallite
Definition at line 23 of file config.f90.
Referenced by config_init().
config_debug
type(tpartitionedstringlist), public, protected config::config_debug
Definition at line 30 of file config.f90.
Referenced by config_deallocate(), and config_init().
config_homogenization
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config::config_homogenization
Definition at line 23 of file config.f90.
Referenced by config_deallocate(), config_init(), damage_local::damage_local_init(), damage_none::damage_none_init(), damage_nonlocal::damage_nonlocal_init(), material::material_init(), material::material_parsehomogenization(), thermal_adiabatic::thermal_adiabatic_init(), thermal_conduction::thermal_conduction_init(), and thermal_isothermal::thermal_isothermal_init().
config_microstructure
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config::config_microstructure
Definition at line 23 of file config.f90.
Referenced by config_deallocate(), config_init(), material::material_init(), and material::material_parsemicrostructure().
config_name_crystallite
character(len=pstringlen), dimension(:), allocatable, public, protected config::config_name_crystallite
name of each crystallite setting
Definition at line 34 of file config.f90.
Referenced by config_init().
config_name_homogenization
character(len=pstringlen), dimension(:), allocatable, public, protected config::config_name_homogenization
name of each homogenization
Definition at line 34 of file config.f90.
Referenced by config_init(), homogenization::homogenization_results(), and material::material_init().
config_name_microstructure
character(len=pstringlen), dimension(:), allocatable, public, protected config::config_name_microstructure
name of each microstructure
Definition at line 34 of file config.f90.
Referenced by config_init(), material::material_init(), and material::material_parsemicrostructure().
config_name_phase
character(len=pstringlen), dimension(:), allocatable, public, protected config::config_name_phase
name of each phase
Definition at line 34 of file config.f90.
Referenced by config_init(), constitutive::constitutive_results(), crystallite::crystallite_results(), and material::material_init().
config_name_texture
character(len=pstringlen), dimension(:), allocatable, public, protected config::config_name_texture
name of each texture
Definition at line 34 of file config.f90.
Referenced by config_init(), and material::material_init().
config_numerics
type(tpartitionedstringlist), public, protected config::config_numerics
Definition at line 30 of file config.f90.
Referenced by config_deallocate(), config_init(), crystallite::crystallite_init(), damask_spectral(), grid_mech_spectral_basic::grid_mech_spectral_basic_init(), grid_mech_spectral_polarisation::grid_mech_spectral_polarisation_init(), homogenization::homogenization_init(), and spectral_utilities::utilities_init().
config_phase
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config::config_phase
Definition at line 23 of file config.f90.
Referenced by config_deallocate(), config_init(), crystallite::crystallite_init(), kinematics_cleavage_opening::kinematics_cleavage_opening_init(), kinematics_slipplane_opening::kinematics_slipplane_opening_init(), kinematics_thermal_expansion::kinematics_thermal_expansion_init(), lattice::lattice_init(), material::material_init(), material::material_parsephase(), source_damage_anisobrittle::source_damage_anisobrittle_init(), source_damage_anisoductile::source_damage_anisoductile_init(), source_damage_isobrittle::source_damage_isobrittle_init(), source_damage_isoductile::source_damage_isoductile_init(), source_thermal_dissipation::source_thermal_dissipation_init(), and source_thermal_externalheat::source_thermal_externalheat_init().
config_texture
type(tpartitionedstringlist), dimension(:), allocatable, public, protected config::config_texture
Definition at line 23 of file config.f90.
Referenced by config_deallocate(), config_init(), material::material_init(), and material::material_parsetexture().