DAMASK with grid solvers: source_thermal_externalheat Module Reference
source_thermal_externalheat Module Reference
material subroutine for variable heat source
Data Types
type tparameters
container type for internal constitutive parameters
Functions/Subroutines
subroutine, public source_thermal_externalheat_init
module initialization
subroutine, public source_thermal_externalheat_dotstate (phase, of)
rate of change of state
subroutine, public source_thermal_externalheat_getrateanditstangent (TDot, dTDot_dT, phase, of)
returns local heat generation rate
Variables
integer, dimension(:), allocatable source_thermal_externalheat_offset
which source is my current thermal dissipation mechanism?
integer, dimension(:), allocatable source_thermal_externalheat_instance
instance of thermal dissipation source mechanism
type(tparameters), dimension(:), allocatable param
containers of constitutive parameters (len Ninstance)
Detailed Description
material subroutine for variable heat source
Author
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
Philip Eisenlohr, Michigan State University
Function/Subroutine Documentation
source_thermal_externalheat_dotstate()
subroutine, public source_thermal_externalheat::source_thermal_externalheat_dotstate (integer, intent(in) phase, integer, intent(in) of)
rate of change of state
state only contains current time to linearly interpolate given heat powers
Definition at line 94 of file source_thermal_externalheat.f90.
References source_thermal_externalheat_offset.
Referenced by constitutive::constitutive_collectdotstate().
source_thermal_externalheat_getrateanditstangent()
subroutine, public source_thermal_externalheat::source_thermal_externalheat_getrateanditstangent (real(preal), intent(out) TDot, real(preal), intent(out) dTDot_dT, integer, intent(in) phase, integer, intent(in) of)
returns local heat generation rate
Definition at line 113 of file source_thermal_externalheat.f90.
References param, source_thermal_externalheat_instance, and source_thermal_externalheat_offset.
source_thermal_externalheat_init()
subroutine, public source_thermal_externalheat::source_thermal_externalheat_init
module initialization
reads in material parameters, allocates arrays, and does sanity checks
Definition at line 49 of file source_thermal_externalheat.f90.
References config::config_phase, debug::debug_constitutive, debug::debug_level, debug::debug_levelbasic, discretization::discretization_nip, material::material_allocatesourcestate(), material::material_phaseat, param, material::phase_nsources, material::phase_source, material::source_thermal_externalheat_id, source_thermal_externalheat_instance, material::source_thermal_externalheat_label, and source_thermal_externalheat_offset.
Referenced by constitutive::constitutive_init().
Variable Documentation
param
type(tparameters), dimension(:), allocatable source_thermal_externalheat::param private
containers of constitutive parameters (len Ninstance)
Definition at line 33 of file source_thermal_externalheat.f90.
Referenced by source_thermal_externalheat_getrateanditstangent(), and source_thermal_externalheat_init().
source_thermal_externalheat_instance
integer, dimension(:), allocatable source_thermal_externalheat::source_thermal_externalheat_instance private
instance of thermal dissipation source mechanism
Definition at line 21 of file source_thermal_externalheat.f90.
Referenced by source_thermal_externalheat_getrateanditstangent(), and source_thermal_externalheat_init().
source_thermal_externalheat_offset
integer, dimension(:), allocatable source_thermal_externalheat::source_thermal_externalheat_offset private
which source is my current thermal dissipation mechanism?
Definition at line 21 of file source_thermal_externalheat.f90.
Referenced by source_thermal_externalheat_dotstate(), source_thermal_externalheat_getrateanditstangent(), and source_thermal_externalheat_init().