DAMASK with grid solvers: system_routines Module Reference
system_routines Module Reference
provides wrappers to C routines
Data Types
interface chdir_C
interface getCurrentWorkDir_C
interface getHostName_C
interface isDirectory_C
interface signalterm_C
interface signalusr1_C
interface signalusr2_C
Functions/Subroutines
logical function, public isdirectory (path)
figures out if a given path is a directory (and not an ordinary file)
character(len=:) function, allocatable, public getcwd ()
gets the current working directory
character(len=:) function, allocatable, public gethostname ()
gets the current host name
logical function, public setcwd (path)
changes the current working directory
Detailed Description
provides wrappers to C routines
Author
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
getcwd()
character(len=:) function, allocatable, public system_routines::getcwd
gets the current working directory
Definition at line 118 of file system_routines.f90.
Referenced by damask_interface::damask_interface_init(), damask_interface::getgeometryfile(), damask_interface::getloadcasefile(), and damask_interface::setworkingdirectory().
gethostname()
character(len=:) function, allocatable, public system_routines::gethostname
gets the current host name
Definition at line 147 of file system_routines.f90.
Referenced by damask_interface::damask_interface_init().
isdirectory()
logical function, public system_routines::isdirectory (character(len=*), intent(in) path)
figures out if a given path is a directory (and not an ordinary file)
Definition at line 100 of file system_routines.f90.
setcwd()
logical function, public system_routines::setcwd (character(len=*), intent(in) path)
changes the current working directory
Definition at line 176 of file system_routines.f90.
Referenced by damask_interface::setworkingdirectory().