DAMASK with grid solvers: damage_nonlocal Module Reference
damage_nonlocal Module Reference
material subroutine for non-locally evolving damage field
Data Types
type tparameters
Functions/Subroutines
subroutine, public damage_nonlocal_init
module initialization
subroutine, public damage_nonlocal_getsourceanditstangent (phiDot, dPhiDot_dPhi, phi, ip, el)
calculates homogenized damage driving forces
real(preal) function, dimension(3, 3), public damage_nonlocal_getdiffusion (ip, el)
returns homogenized non local damage diffusion tensor in reference configuration
real(preal) function, public damage_nonlocal_getmobility (ip, el)
Returns homogenized nonlocal damage mobility.
subroutine, public damage_nonlocal_putnonlocaldamage (phi, ip, el)
updated nonlocal damage field with solution from damage phase field PDE
subroutine, public damage_nonlocal_results (homog, group)
writes results to HDF5 output file
Variables
type(tparameters), dimension(:), allocatable param
Detailed Description
material subroutine for non-locally evolving damage field
Author
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
damage_nonlocal_getdiffusion()
real(preal) function, dimension(3,3), public damage_nonlocal::damage_nonlocal_getdiffusion (integer, intent(in) ip, integer, intent(in) el)
returns homogenized non local damage diffusion tensor in reference configuration
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 136 of file damage_nonlocal.f90.
Referenced by grid_damage_spectral::formresidual(), and grid_damage_spectral::updatereference().
damage_nonlocal_getmobility()
real(preal) function, public damage_nonlocal::damage_nonlocal_getmobility (integer, intent(in) ip, integer, intent(in) el)
Returns homogenized nonlocal damage mobility.
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 163 of file damage_nonlocal.f90.
Referenced by grid_damage_spectral::formresidual(), and grid_damage_spectral::updatereference().
damage_nonlocal_getsourceanditstangent()
subroutine, public damage_nonlocal::damage_nonlocal_getsourceanditstangent (real(preal) phiDot, real(preal) dPhiDot_dPhi, real(preal), intent(in) phi, integer, intent(in) ip, integer, intent(in) el)
calculates homogenized damage driving forces
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 83 of file damage_nonlocal.f90.
Referenced by grid_damage_spectral::formresidual().
damage_nonlocal_init()
subroutine, public damage_nonlocal::damage_nonlocal_init
module initialization
reads in material parameters, allocates arrays, and does sanity checks
Definition at line 48 of file damage_nonlocal.f90.
References config::config_homogenization, material::damage, material::damage_initialphi, material::damage_nonlocal_id, material::damage_nonlocal_label, material::damage_type, material::damage_typeinstance, material::damagemapping, material::damagestate, prec::emptystringarray, material::material_homogenizationat, material::material_homogenizationmemberat, and param.
Referenced by homogenization::homogenization_init().
damage_nonlocal_putnonlocaldamage()
subroutine, public damage_nonlocal::damage_nonlocal_putnonlocaldamage (real(preal), intent(in) phi, integer, intent(in) ip, integer, intent(in) el)
updated nonlocal damage field with solution from damage phase field PDE
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 186 of file damage_nonlocal.f90.
Referenced by grid_damage_spectral::grid_damage_spectral_forward(), and grid_damage_spectral::grid_damage_spectral_solution().
damage_nonlocal_results()
subroutine, public damage_nonlocal::damage_nonlocal_results (integer, intent(in) homog, character(len=*), intent(in) group)
writes results to HDF5 output file
Definition at line 207 of file damage_nonlocal.f90.
References param.
Referenced by homogenization::homogenization_results().
Variable Documentation
param
type(tparameters), dimension(:), allocatable damage_nonlocal::param private
Definition at line 30 of file damage_nonlocal.f90.
Referenced by damage_nonlocal_init(), and damage_nonlocal_results().