DAMASK with grid solvers: damage_local Module Reference
damage_local Module Reference
material subroutine for locally evolving damage field
Data Types
type tparameters
Functions/Subroutines
subroutine, public damage_local_init
module initialization
logical function, dimension(2), public damage_local_updatestate (subdt, ip, el)
calculates local change in damage field
subroutine damage_local_getsourceanditstangent (phiDot, dPhiDot_dPhi, phi, ip, el)
calculates homogenized local damage driving forces
subroutine, public damage_local_results (homog, group)
writes results to HDF5 output file
Variables
type(tparameters), dimension(:), allocatable param
Detailed Description
material subroutine for locally evolving damage field
Author
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
damage_local_getsourceanditstangent()
subroutine damage_local::damage_local_getsourceanditstangent (real(preal) phiDot, real(preal) dPhiDot_dPhi, real(preal), intent(in) phi, integer, intent(in) ip, integer, intent(in) el) private
calculates homogenized local damage driving forces
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 113 of file damage_local.f90.
Referenced by damage_local_updatestate().
damage_local_init()
subroutine, public damage_local::damage_local_init
module initialization
reads in material parameters, allocates arrays, and does sanity checks
Definition at line 43 of file damage_local.f90.
References config::config_homogenization, material::damage, material::damage_initialphi, material::damage_local_id, material::damage_local_label, material::damage_type, material::damage_typeinstance, material::damagemapping, material::damagestate, prec::emptystringarray, material::material_homogenizationat, material::material_homogenizationmemberat, and param.
Referenced by homogenization::homogenization_init().
damage_local_results()
subroutine, public damage_local::damage_local_results (integer, intent(in) homog, character(len=*), intent(in) group)
writes results to HDF5 output file
Definition at line 166 of file damage_local.f90.
References param.
Referenced by homogenization::homogenization_results().
damage_local_updatestate()
logical function, dimension(2), public damage_local::damage_local_updatestate (real(preal), intent(in) subdt, integer, intent(in) ip, integer, intent(in) el)
calculates local change in damage field
Parameters
[in] el element number
Parameters
ip integration point number
Definition at line 78 of file damage_local.f90.
References damage_local_getsourceanditstangent().
Referenced by homogenization::updatestate().
Variable Documentation
param
type(tparameters), dimension(:), allocatable damage_local::param private
Definition at line 28 of file damage_local.f90.
Referenced by damage_local_init(), and damage_local_results().