DAMASK with grid solvers: crystallite Module Reference
crystallite Module Reference
crystallite state integration functions and reporting of results
Data Types
type tnumerics
type toutput
new requested output (per phase)
Functions/Subroutines
subroutine, public crystallite_init
allocates and initialize per grain variables
logical function, dimension(discretization_nip, discretization_nelem), public crystallite_stress (dummyArgumentToPreventInternalCompilerErrorWithGCC)
calculate stress (P)
subroutine, public crystallite_stresstangent
calculate tangent (dPdF)
subroutine, public crystallite_orientations
calculates orientations
real(preal) function, dimension(3, 3), public crystallite_push33toref (ipc, ip, el, tensor33)
Map 2nd order tensor to reference config.
subroutine, public crystallite_results
writes crystallite results to HDF5 output file
logical function integratestress (ipc, ip, el, timeFraction)
calculation of stress (P) with time integration based on a residuum in Lp and intermediate acceleration of the Newton-Raphson correction
subroutine integratestatefpi
integrate stress, state with adaptive 1st order explicit Euler method using Fixed Point Iteration to adapt the stepsize
subroutine integratestateeuler
integrate state with 1st order explicit Euler method
subroutine integratestateadaptiveeuler
integrate stress, state with 1st order Euler method with adaptive step size
subroutine integratestaterk4
integrate stress, state with 4th order explicit Runge Kutta method
subroutine integratestaterkck45
integrate stress, state with 5th order Runge-Kutta Cash-Karp method with adaptive step size (use 5th order solution to advance = "local extrapolation")
subroutine nonlocalconvergencecheck
sets convergence flag for nonlocal calculations
logical pure function converged (residuum, state, atol)
determines whether a point is converged
logical function statejump (ipc, ip, el)
calculates a jump in the state according to the current state and the current stress returns true, if state jump was successfull or not needed. false indicates NaN in delta state
subroutine, public crystallite_restartwrite
Write current restart information (Field and constitutive data) to file.
subroutine, public crystallite_restartread
Read data for restart.
subroutine, public crystallite_forward
Forward data after successful increment.
Variables
real(preal), dimension(:,:,:), allocatable, public crystallite_dt
requested time increment of each grain
real(preal), dimension(:,:,:), allocatable crystallite_subdt
substepped time increment of each grain
real(preal), dimension(:,:,:), allocatable crystallite_subfrac
already calculated fraction of increment
real(preal), dimension(:,:,:), allocatable crystallite_substep
size of next integration step
type(rotation), dimension(:,:,:), allocatable crystallite_orientation
current orientation
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite_fe
current "elastic" def grad (end of converged time step)
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite_p
1st Piola-Kirchhoff stress per grain
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite_s0
2nd Piola-Kirchhoff stress vector at start of FE inc
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite_fp0
plastic def grad at start of FE inc
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite_fi0
intermediate def grad at start of FE inc
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite_f0
def grad at start of FE inc
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite_lp0
plastic velocitiy grad at start of FE inc
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite_li0
intermediate velocitiy grad at start of FE inc
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_s
current 2nd Piola-Kirchhoff stress vector (end of converged time step)
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_partioneds0
2nd Piola-Kirchhoff stress vector at start of homog inc
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_fp
current plastic def grad (end of converged time step)
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_partionedfp0
plastic def grad at start of homog inc
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_fi
current intermediate def grad (end of converged time step)
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_partionedfi0
intermediate def grad at start of homog inc
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_partionedf
def grad to be reached at end of homog inc
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_partionedf0
def grad at start of homog inc
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_lp
current plastic velocitiy grad (end of converged time step)
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_partionedlp0
plastic velocity grad at start of homog inc
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_li
current intermediate velocitiy grad (end of converged time step)
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite_partionedli0
intermediate velocity grad at start of homog inc
real(preal), dimension(:,:,:,:,:), allocatable crystallite_subfp0
plastic def grad at start of crystallite inc
real(preal), dimension(:,:,:,:,:), allocatable crystallite_subfi0
intermediate def grad at start of crystallite inc
real(preal), dimension(:,:,:,:,:), allocatable crystallite_subf
def grad to be reached at end of crystallite inc
real(preal), dimension(:,:,:,:,:), allocatable crystallite_subf0
def grad at start of crystallite inc
real(preal), dimension(:,:,:,:,:), allocatable crystallite_sublp0
plastic velocity grad at start of crystallite inc
real(preal), dimension(:,:,:,:,:), allocatable crystallite_subli0
intermediate velocity grad at start of crystallite inc
real(preal), dimension(:,:,:,:,:,:,:), allocatable, public, protected crystallite_dpdf
current individual dPdF per grain (end of converged time step)
logical, dimension(:,:,:), allocatable, public crystallite_requested
used by upper level (homogenization) to request crystallite calculation
logical, dimension(:,:,:), allocatable crystallite_converged
convergence flag
logical, dimension(:,:,:), allocatable crystallite_todo
flag to indicate need for further computation
logical, dimension(:,:,:), allocatable crystallite_localplasticity
indicates this grain to have purely local constitutive law
type(toutput), dimension(:), allocatable output_constituent
type(tnumerics) num
procedure(), pointer integratestate
Detailed Description
crystallite state integration functions and reporting of results
Author
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
Franz Roters, Max-Planck-Institut für Eisenforschung GmbH
Philip Eisenlohr, Max-Planck-Institut für Eisenforschung GmbH
Christoph Kords, Max-Planck-Institut für Eisenforschung GmbH
Chen Zhang, Michigan State University
Function/Subroutine Documentation
converged()
logical pure function crystallite::converged (real(preal), dimension(:), intent(in) residuum, real(preal), dimension(:), intent(in) state, real(preal), dimension(:), intent(in) atol) private
determines whether a point is converged
Definition at line 1686 of file crystallite.f90.
References num.
Referenced by integratestateadaptiveeuler(), integratestatefpi(), integratestaterkck45(), and homogenization::materialpoint_stressanditstangent().
crystallite_forward()
subroutine, public crystallite::crystallite_forward
Forward data after successful increment.
Definition at line 1839 of file crystallite.f90.
References crystallite_fi, crystallite_fi0, crystallite_li, crystallite_li0, crystallite_s, and crystallite_s0.
Referenced by cpfem2::cpfem_forward().
crystallite_init()
subroutine, public crystallite::crystallite_init
allocates and initialize per grain variables
Definition at line 125 of file crystallite.f90.
References config::config_deallocate(), config::config_numerics, config::config_phase, constitutive::constitutive_dependentstate(), constitutive::constitutive_initialfi(), crystallite_converged, crystallite_dpdf, crystallite_dt, crystallite_f0, crystallite_fe, crystallite_fi, crystallite_fi0, crystallite_fp, crystallite_fp0, crystallite_li, crystallite_li0, crystallite_localplasticity, crystallite_lp, crystallite_lp0, crystallite_orientation, crystallite_orientations(), crystallite_p, crystallite_partionedf, crystallite_partionedf0, crystallite_partionedfi0, crystallite_partionedfp0, crystallite_partionedli0, crystallite_partionedlp0, crystallite_partioneds0, crystallite_requested, crystallite_s, crystallite_s0, crystallite_stress(), crystallite_stresstangent(), crystallite_subdt, crystallite_subf, crystallite_subf0, crystallite_subfi0, crystallite_subfp0, crystallite_subfrac, crystallite_subli0, crystallite_sublp0, crystallite_substep, crystallite_todo, discretization::discretization_nelem, discretization::discretization_nip, fesolving::fesolving_execelem, fesolving::fesolving_execip, material::homogenization_maxngrains, material::homogenization_ngrains, integratestate, integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), integratestaterkck45(), io::io_error(), material::material_homogenizationat, material::material_orientation0, material::material_phaseat, math::math_det33(), math::math_i3, math::math_inv33(), num, numerics::numerics_integrator, output_constituent, material::phase_localplasticity, and numerics::usepingpong.
Referenced by cpfem2::cpfem_initall().
crystallite_orientations()
subroutine, public crystallite::crystallite_orientations
calculates orientations
Definition at line 573 of file crystallite.f90.
References crystallite_fe, crystallite_orientation, fesolving::fesolving_execelem, fesolving::fesolving_execip, material::homogenization_ngrains, material::material_homogenizationat, material::material_phaseat, math::math_rotationalpart(), material::phase_plasticityinstance, and material::plasticstate.
Referenced by crystallite_init(), and homogenization::materialpoint_stressanditstangent().
crystallite_push33toref()
real(preal) function, dimension(3,3), public crystallite::crystallite_push33toref (integer, intent(in) ipc, integer, intent(in) ip, integer, intent(in) el, real(preal), dimension(3,3), intent(in) tensor33)
Map 2nd order tensor to reference config.
Definition at line 605 of file crystallite.f90.
References crystallite_subf, material::material_orientation0, and math::math_inv33().
crystallite_restartread()
subroutine, public crystallite::crystallite_restartread
Read data for restart.
Definition at line 1798 of file crystallite.f90.
References crystallite_f0, crystallite_fi0, crystallite_fp, crystallite_fp0, crystallite_li0, crystallite_lp, crystallite_lp0, crystallite_partionedf, and crystallite_s0.
Referenced by cpfem2::cpfem_init().
crystallite_restartwrite()
subroutine, public crystallite::crystallite_restartwrite
Write current restart information (Field and constitutive data) to file.
Definition at line 1757 of file crystallite.f90.
References crystallite_fi, crystallite_fp, crystallite_li, crystallite_lp, crystallite_partionedf, and crystallite_s.
Referenced by cpfem2::cpfem_restartwrite().
crystallite_results()
subroutine, public crystallite::crystallite_results
writes crystallite results to HDF5 output file
Definition at line 625 of file crystallite.f90.
References config::config_name_phase, crystallite_fe, crystallite_fi, crystallite_fp, crystallite_li, crystallite_lp, crystallite_orientation, crystallite_p, crystallite_partionedf, crystallite_s, lattice::lattice_bcc_id, lattice::lattice_bct_id, lattice::lattice_fcc_id, lattice::lattice_hex_id, lattice::lattice_iso_id, lattice::lattice_ort_id, lattice::lattice_structure, output_constituent, results::results_addgroup(), results::results_closegroup(), select_rotations(), and select_tensors().
Referenced by cpfem2::cpfem_results().
crystallite_stress()
logical function, dimension(discretization_nip,discretization_nelem), public crystallite::crystallite_stress (real(preal), intent(in), optional dummyArgumentToPreventInternalCompilerErrorWithGCC)
calculate stress (P)
Definition at line 284 of file crystallite.f90.
References crystallite_converged, crystallite_dt, crystallite_fe, crystallite_fi, crystallite_fp, crystallite_li, crystallite_lp, crystallite_partionedf, crystallite_partionedf0, crystallite_partionedfi0, crystallite_partionedfp0, crystallite_partionedli0, crystallite_partionedlp0, crystallite_requested, crystallite_s, crystallite_s0, crystallite_subdt, crystallite_subf, crystallite_subf0, crystallite_subfi0, crystallite_subfp0, crystallite_subfrac, crystallite_subli0, crystallite_sublp0, crystallite_substep, crystallite_todo, discretization::discretization_nip, fesolving::fesolving_execelem, fesolving::fesolving_execip, material::homogenization_ngrains, integratestate, material::material_homogenizationat, material::material_phaseat, material::material_phasememberat, math::math_inv33(), num, material::phase_nsources, material::plasticstate, and material::sourcestate.
Referenced by crystallite_init(), and homogenization::materialpoint_stressanditstangent().
crystallite_stresstangent()
subroutine, public crystallite::crystallite_stresstangent
calculate tangent (dPdF)
Definition at line 437 of file crystallite.f90.
References constitutive::constitutive_lianditstangents(), constitutive::constitutive_lpanditstangents(), constitutive::constitutive_sanditstangents(), crystallite_dpdf, crystallite_fe, crystallite_fi, crystallite_fp, crystallite_s, crystallite_subdt, crystallite_subf, crystallite_subfi0, crystallite_subfp0, fesolving::fesolving_execelem, fesolving::fesolving_execip, material::homogenization_ngrains, io::io_warning(), material::material_homogenizationat, math::math_3333to99(), math::math_99to3333(), math::math_identity2nd(), math::math_inv33(), math::math_invert(), math::math_mul3333xx3333(), and prec::tol_math_check.
Referenced by crystallite_init(), and homogenization::materialpoint_stressanditstangent().
integratestateadaptiveeuler()
subroutine crystallite::integratestateadaptiveeuler private
integrate stress, state with 1st order Euler method with adaptive step size
Definition at line 1219 of file crystallite.f90.
References converged(), crystallite_converged, crystallite_fi, crystallite_fp, crystallite_localplasticity, crystallite_partionedf, crystallite_partionedf0, crystallite_partionedfp0, crystallite_s, crystallite_subdt, crystallite_todo, integratestress(), nonlocalconvergencecheck(), and statejump().
Referenced by crystallite_init().
integratestateeuler()
subroutine crystallite::integratestateeuler private
integrate state with 1st order explicit Euler method
Definition at line 1145 of file crystallite.f90.
References crystallite_converged, crystallite_fi, crystallite_fp, crystallite_localplasticity, crystallite_partionedf, crystallite_partionedf0, crystallite_partionedfp0, crystallite_s, crystallite_subdt, crystallite_todo, integratestress(), nonlocalconvergencecheck(), and statejump().
Referenced by crystallite_init().
integratestatefpi()
subroutine crystallite::integratestatefpi private
integrate stress, state with adaptive 1st order explicit Euler method using Fixed Point Iteration to adapt the stepsize
Definition at line 979 of file crystallite.f90.
References constitutive::constitutive_collectdotstate(), constitutive::constitutive_dependentstate(), converged(), crystallite_converged, crystallite_fi, crystallite_fp, crystallite_localplasticity, crystallite_partionedf, crystallite_partionedf0, crystallite_partionedfp0, crystallite_s, crystallite_subdt, crystallite_todo, damper(), fesolving::fesolving_execelem, fesolving::fesolving_execip, material::homogenization_ngrains, integratestress(), material::material_homogenizationat, material::material_phaseat, material::material_phasememberat, nonlocalconvergencecheck(), num, material::phase_nsources, material::plasticstate, material::sourcestate, and statejump().
Referenced by crystallite_init().
integratestaterk4()
subroutine crystallite::integratestaterk4 private
integrate stress, state with 4th order explicit Runge Kutta method
Definition at line 1339 of file crystallite.f90.
References crystallite_converged, crystallite_fi, crystallite_fp, crystallite_localplasticity, crystallite_partionedf, crystallite_partionedf0, crystallite_partionedfp0, crystallite_s, crystallite_subdt, crystallite_todo, integratestress(), nonlocalconvergencecheck(), and statejump().
Referenced by crystallite_init().
integratestaterkck45()
subroutine crystallite::integratestaterkck45 private
integrate stress, state with 5th order Runge-Kutta Cash-Karp method with adaptive step size (use 5th order solution to advance = "local extrapolation")
Definition at line 1494 of file crystallite.f90.
References converged(), crystallite_converged, crystallite_fi, crystallite_fp, crystallite_localplasticity, crystallite_partionedf, crystallite_partionedf0, crystallite_partionedfp0, crystallite_s, crystallite_subdt, crystallite_todo, integratestress(), nonlocalconvergencecheck(), and statejump().
Referenced by crystallite_init().
integratestress()
logical function crystallite::integratestress (integer, intent(in) ipc, integer, intent(in) ip, integer, intent(in) el, real(preal), intent(in), optional timeFraction) private
calculation of stress (P) with time integration based on a residuum in Lp and intermediate acceleration of the Newton-Raphson correction
Definition at line 755 of file crystallite.f90.
References constitutive::constitutive_lianditstangents(), constitutive::constitutive_lpanditstangents(), constitutive::constitutive_sanditstangents(), crystallite_fe, crystallite_fi, crystallite_fp, crystallite_li, crystallite_lp, crystallite_p, crystallite_s, crystallite_subdt, crystallite_subf, crystallite_subf0, crystallite_subfi0, crystallite_subfp0, math::math_3333to99(), math::math_33to9(), math::math_9to33(), math::math_det33(), math::math_i3, math::math_identity2nd(), math::math_inv33(), math::math_invert33(), math::math_mul3333xx3333(), and num.
Referenced by integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), and integratestaterkck45().
nonlocalconvergencecheck()
subroutine crystallite::nonlocalconvergencecheck private
sets convergence flag for nonlocal calculations
one non-converged nonlocal sets all other nonlocals to non-converged to trigger cut back
Definition at line 1675 of file crystallite.f90.
Referenced by integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), and integratestaterkck45().
statejump()
logical function crystallite::statejump (integer, intent(in) ipc, integer, intent(in) ip, integer, intent(in) el) private
calculates a jump in the state according to the current state and the current stress returns true, if state jump was successfull or not needed. false indicates NaN in delta state
Definition at line 1704 of file crystallite.f90.
References crystallite_fe, crystallite_fi, and crystallite_s.
Referenced by integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), and integratestaterkck45().
Variable Documentation
crystallite_converged
logical, dimension(:,:,:), allocatable crystallite::crystallite_converged private
convergence flag
Definition at line 76 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), and integratestaterkck45().
crystallite_dpdf
real(preal), dimension(:,:,:,:,:,:,:), allocatable, public, protected crystallite::crystallite_dpdf
current individual dPdF per grain (end of converged time step)
Definition at line 72 of file crystallite.f90.
Referenced by homogenization::averagestressanditstangent(), crystallite_init(), crystallite_stresstangent(), and homogenization::updatestate().
crystallite_dt
real(preal), dimension(:,:,:), allocatable, public crystallite::crystallite_dt
requested time increment of each grain
Definition at line 35 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), and homogenization::materialpoint_stressanditstangent().
crystallite_f0
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite::crystallite_f0
def grad at start of FE inc
Definition at line 43 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_restartread(), and homogenization::materialpoint_stressanditstangent().
crystallite_fe
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite::crystallite_fe
current "elastic" def grad (end of converged time step)
Definition at line 43 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_orientations(), crystallite_results(), crystallite_stress(), crystallite_stresstangent(), integratestress(), and statejump().
crystallite_fi
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_fi
current intermediate def grad (end of converged time step)
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_forward(), crystallite_init(), crystallite_restartwrite(), crystallite_results(), crystallite_stress(), crystallite_stresstangent(), integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), integratestaterkck45(), integratestress(), homogenization::materialpoint_stressanditstangent(), and statejump().
crystallite_fi0
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite::crystallite_fi0
intermediate def grad at start of FE inc
Definition at line 43 of file crystallite.f90.
Referenced by crystallite_forward(), crystallite_init(), crystallite_restartread(), and homogenization::materialpoint_stressanditstangent().
crystallite_fp
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_fp
current plastic def grad (end of converged time step)
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_restartread(), crystallite_restartwrite(), crystallite_results(), crystallite_stress(), crystallite_stresstangent(), integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), integratestaterkck45(), integratestress(), and homogenization::materialpoint_stressanditstangent().
crystallite_fp0
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite::crystallite_fp0
plastic def grad at start of FE inc
Definition at line 43 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_restartread(), and homogenization::materialpoint_stressanditstangent().
crystallite_li
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_li
current intermediate velocitiy grad (end of converged time step)
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_forward(), crystallite_init(), crystallite_restartwrite(), crystallite_results(), crystallite_stress(), integratestress(), and homogenization::materialpoint_stressanditstangent().
crystallite_li0
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite::crystallite_li0
intermediate velocitiy grad at start of FE inc
Definition at line 43 of file crystallite.f90.
Referenced by crystallite_forward(), crystallite_init(), crystallite_restartread(), and homogenization::materialpoint_stressanditstangent().
crystallite_localplasticity
logical, dimension(:,:,:), allocatable crystallite::crystallite_localplasticity private
indicates this grain to have purely local constitutive law
Definition at line 76 of file crystallite.f90.
Referenced by crystallite_init(), integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), and integratestaterkck45().
crystallite_lp
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_lp
current plastic velocitiy grad (end of converged time step)
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_restartread(), crystallite_restartwrite(), crystallite_results(), crystallite_stress(), integratestress(), and homogenization::materialpoint_stressanditstangent().
crystallite_lp0
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite::crystallite_lp0
plastic velocitiy grad at start of FE inc
Definition at line 43 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_restartread(), and homogenization::materialpoint_stressanditstangent().
crystallite_orientation
type(rotation), dimension(:,:,:), allocatable crystallite::crystallite_orientation private
current orientation
Definition at line 41 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_orientations(), and crystallite_results().
crystallite_p
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite::crystallite_p
1st Piola-Kirchhoff stress per grain
Definition at line 43 of file crystallite.f90.
Referenced by homogenization::averagestressanditstangent(), crystallite_init(), crystallite_results(), integratestress(), and homogenization::updatestate().
crystallite_partionedf
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_partionedf
def grad to be reached at end of homog inc
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_restartread(), crystallite_restartwrite(), crystallite_results(), crystallite_stress(), integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), integratestaterkck45(), homogenization::materialpoint_stressanditstangent(), homogenization::partitiondeformation(), and homogenization::updatestate().
crystallite_partionedf0
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_partionedf0
def grad at start of homog inc
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), integratestaterkck45(), homogenization::materialpoint_stressanditstangent(), and homogenization::updatestate().
crystallite_partionedfi0
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_partionedfi0
intermediate def grad at start of homog inc
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), and homogenization::materialpoint_stressanditstangent().
crystallite_partionedfp0
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_partionedfp0
plastic def grad at start of homog inc
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), integratestaterkck45(), and homogenization::materialpoint_stressanditstangent().
crystallite_partionedli0
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_partionedli0
intermediate velocity grad at start of homog inc
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), and homogenization::materialpoint_stressanditstangent().
crystallite_partionedlp0
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_partionedlp0
plastic velocity grad at start of homog inc
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), and homogenization::materialpoint_stressanditstangent().
crystallite_partioneds0
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_partioneds0
2nd Piola-Kirchhoff stress vector at start of homog inc
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_init(), and homogenization::materialpoint_stressanditstangent().
crystallite_requested
logical, dimension(:,:,:), allocatable, public crystallite::crystallite_requested
used by upper level (homogenization) to request crystallite calculation
Definition at line 74 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), and homogenization::materialpoint_stressanditstangent().
crystallite_s
real(preal), dimension(:,:,:,:,:), allocatable, public crystallite::crystallite_s
current 2nd Piola-Kirchhoff stress vector (end of converged time step)
Definition at line 52 of file crystallite.f90.
Referenced by crystallite_forward(), crystallite_init(), crystallite_restartwrite(), crystallite_results(), crystallite_stress(), crystallite_stresstangent(), integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), integratestaterkck45(), integratestress(), homogenization::materialpoint_stressanditstangent(), and statejump().
crystallite_s0
real(preal), dimension(:,:,:,:,:), allocatable, public, protected crystallite::crystallite_s0
2nd Piola-Kirchhoff stress vector at start of FE inc
Definition at line 43 of file crystallite.f90.
Referenced by crystallite_forward(), crystallite_init(), crystallite_restartread(), crystallite_stress(), and homogenization::materialpoint_stressanditstangent().
crystallite_subdt
real(preal), dimension(:,:,:), allocatable crystallite::crystallite_subdt private
substepped time increment of each grain
Definition at line 37 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), crystallite_stresstangent(), integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), integratestaterkck45(), and integratestress().
crystallite_subf
real(preal), dimension(:,:,:,:,:), allocatable crystallite::crystallite_subf private
def grad to be reached at end of crystallite inc
Definition at line 65 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_push33toref(), crystallite_stress(), crystallite_stresstangent(), and integratestress().
crystallite_subf0
real(preal), dimension(:,:,:,:,:), allocatable crystallite::crystallite_subf0 private
def grad at start of crystallite inc
Definition at line 65 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), and integratestress().
crystallite_subfi0
real(preal), dimension(:,:,:,:,:), allocatable crystallite::crystallite_subfi0 private
intermediate def grad at start of crystallite inc
Definition at line 65 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), crystallite_stresstangent(), and integratestress().
crystallite_subfp0
real(preal), dimension(:,:,:,:,:), allocatable crystallite::crystallite_subfp0 private
plastic def grad at start of crystallite inc
Definition at line 65 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), crystallite_stresstangent(), and integratestress().
crystallite_subfrac
real(preal), dimension(:,:,:), allocatable crystallite::crystallite_subfrac private
already calculated fraction of increment
Definition at line 37 of file crystallite.f90.
Referenced by crystallite_init(), and crystallite_stress().
crystallite_subli0
real(preal), dimension(:,:,:,:,:), allocatable crystallite::crystallite_subli0 private
intermediate velocity grad at start of crystallite inc
Definition at line 65 of file crystallite.f90.
Referenced by crystallite_init(), and crystallite_stress().
crystallite_sublp0
real(preal), dimension(:,:,:,:,:), allocatable crystallite::crystallite_sublp0 private
plastic velocity grad at start of crystallite inc
Definition at line 65 of file crystallite.f90.
Referenced by crystallite_init(), and crystallite_stress().
crystallite_substep
real(preal), dimension(:,:,:), allocatable crystallite::crystallite_substep private
size of next integration step
Definition at line 37 of file crystallite.f90.
Referenced by crystallite_init(), and crystallite_stress().
crystallite_todo
logical, dimension(:,:,:), allocatable crystallite::crystallite_todo private
flag to indicate need for further computation
Definition at line 76 of file crystallite.f90.
Referenced by crystallite_init(), crystallite_stress(), integratestateadaptiveeuler(), integratestateeuler(), integratestatefpi(), integratestaterk4(), and integratestaterkck45().
integratestate
procedure(), pointer crystallite::integratestate private
Definition at line 105 of file crystallite.f90.
Referenced by crystallite_init(), and crystallite_stress().
num
type(tnumerics) crystallite::num private
Definition at line 103 of file crystallite.f90.
Referenced by converged(), crystallite_init(), crystallite_stress(), homogenization::homogenization_init(), integratestatefpi(), integratestress(), and homogenization::materialpoint_stressanditstangent().
output_constituent
type(toutput), dimension(:), allocatable crystallite::output_constituent private
Definition at line 85 of file crystallite.f90.
Referenced by crystallite_init(), and crystallite_results().