DAMASK with grid solvers: debug Module Reference
debug Module Reference
Reading in and interpretating the debugging settings for the various modules.
Functions/Subroutines
subroutine, public debug_init
reads in parameters from debug.config and allocates arrays
subroutine, public debug_reset
resets all debug values
subroutine, public debug_info
writes debug statements to standard out
Variables
integer, parameter, public debug_levelselective = 2**0
integer, parameter, public debug_levelbasic = 2**1
integer, parameter, public debug_levelextensive = 2**2
integer, parameter, private debug_maxgeneral = debug_LEVELEXTENSIVE
integer, parameter, public debug_spectralrestart = debug_MAXGENERAL*2**1
integer, parameter, public debug_spectralfftw = debug_MAXGENERAL*2**2
integer, parameter, public debug_spectraldivergence = debug_MAXGENERAL*2**3
integer, parameter, public debug_spectralrotation = debug_MAXGENERAL*2**4
integer, parameter, public debug_spectralpetsc = debug_MAXGENERAL*2**5
integer, parameter, public debug_debug = 1
integer, parameter, public debug_math = 2
integer, parameter, public debug_fesolving = 3
integer, parameter, public debug_mesh = 4
stores debug level for mesh part of DAMASK bitwise coded
integer, parameter, public debug_material = 5
stores debug level for material part of DAMASK bitwise coded
integer, parameter, public debug_lattice = 6
stores debug level for lattice part of DAMASK bitwise coded
integer, parameter, public debug_constitutive = 7
stores debug level for constitutive part of DAMASK bitwise coded
integer, parameter, public debug_crystallite = 8
integer, parameter, public debug_homogenization = 9
integer, parameter, public debug_cpfem = 10
integer, parameter, public debug_spectral = 11
integer, parameter, public debug_marc = 12
integer, parameter, private debug_maxntype = debug_MARC
must be set to the maximum defined debug type
integer, dimension(debug_maxntype+2), public, protected debug_level = 0
integer, public, protected debug_e = 1
integer, public, protected debug_i = 1
integer, public, protected debug_g = 1
integer, dimension(2), public debug_stressmaxlocation = 0
integer, dimension(2), public debug_stressminlocation = 0
integer, dimension(2), public debug_jacobianmaxlocation = 0
integer, dimension(2), public debug_jacobianminlocation = 0
real(preal), public debug_stressmax = -huge(1.0_pReal)
real(preal), public debug_stressmin = huge(1.0_pReal)
real(preal), public debug_jacobianmax = -huge(1.0_pReal)
real(preal), public debug_jacobianmin = huge(1.0_pReal)
character(len=1024), parameter, public petscdebug = ' -snes_view -snes_monitor '
Detailed Description
Reading in and interpretating the debugging settings for the various modules.
Author
Franz Roters, Max-Planck-Institut für Eisenforschung GmbH
Philip Eisenlohr, Max-Planck-Institut für Eisenforschung GmbH
Christoph Kords, Max-Planck-Institut für Eisenforschung GmbH
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
debug_info()
subroutine, public debug::debug_info
writes debug statements to standard out
Definition at line 259 of file debug.f90.
References debug_cpfem, debug_jacobianmax, debug_jacobianmaxlocation, debug_jacobianmin, debug_jacobianminlocation, debug_level, debug_levelbasic, debug_stressmax, debug_stressmaxlocation, debug_stressmin, and debug_stressminlocation.
debug_init()
subroutine, public debug::debug_init
reads in parameters from debug.config and allocates arrays
Definition at line 84 of file debug.f90.
References debug_constitutive, debug_cpfem, debug_crystallite, debug_debug, debug_e, debug_fesolving, debug_g, debug_homogenization, debug_i, debug_lattice, debug_level, debug_levelbasic, debug_levelextensive, debug_levelselective, debug_marc, debug_material, debug_math, debug_maxntype, debug_mesh, debug_spectral, debug_spectraldivergence, debug_spectralfftw, debug_spectralpetsc, debug_spectralrestart, debug_spectralrotation, io::io_intvalue(), io::io_isblank(), io::io_lc(), io::io_read_ascii(), io::io_stringpos(), and io::io_stringvalue().
Referenced by cpfem2::cpfem_initall().
debug_reset()
subroutine, public debug::debug_reset
resets all debug values
Definition at line 242 of file debug.f90.
References debug_jacobianmax, debug_jacobianmaxlocation, debug_jacobianmin, debug_jacobianminlocation, debug_stressmax, debug_stressmaxlocation, debug_stressmin, and debug_stressminlocation.
Variable Documentation
debug_constitutive
integer, parameter, public debug::debug_constitutive = 7
stores debug level for constitutive part of DAMASK bitwise coded
Definition at line 32 of file debug.f90.
Referenced by debug_init(), kinematics_cleavage_opening::kinematics_cleavage_opening_init(), kinematics_slipplane_opening::kinematics_slipplane_opening_init(), kinematics_thermal_expansion::kinematics_thermal_expansion_init(), source_damage_anisobrittle::source_damage_anisobrittle_init(), source_damage_anisoductile::source_damage_anisoductile_init(), source_damage_isobrittle::source_damage_isobrittle_init(), source_damage_isoductile::source_damage_isoductile_init(), source_thermal_dissipation::source_thermal_dissipation_init(), and source_thermal_externalheat::source_thermal_externalheat_init().
debug_cpfem
integer, parameter, public debug::debug_cpfem = 10
Definition at line 32 of file debug.f90.
Referenced by debug_info(), and debug_init().
debug_crystallite
integer, parameter, public debug::debug_crystallite = 8
Definition at line 32 of file debug.f90.
Referenced by debug_init().
debug_debug
integer, parameter, public debug::debug_debug = 1
Definition at line 32 of file debug.f90.
Referenced by debug_init().
debug_e
integer, public, protected debug::debug_e = 1
Definition at line 51 of file debug.f90.
Referenced by debug_init(), discretization_grid::discretization_grid_init(), and homogenization::homogenization_init().
debug_fesolving
integer, parameter, public debug::debug_fesolving = 3
Definition at line 32 of file debug.f90.
Referenced by debug_init().
debug_g
integer, public, protected debug::debug_g = 1
Definition at line 51 of file debug.f90.
Referenced by debug_init(), and homogenization::homogenization_init().
debug_homogenization
integer, parameter, public debug::debug_homogenization = 9
Definition at line 32 of file debug.f90.
Referenced by debug_init(), and homogenization::homogenization_init().
debug_i
integer, public, protected debug::debug_i = 1
Definition at line 51 of file debug.f90.
Referenced by debug_init(), and discretization_grid::discretization_grid_init().
debug_jacobianmax
real(preal), public debug::debug_jacobianmax = -huge(1.0_pReal)
Definition at line 63 of file debug.f90.
Referenced by debug_info(), and debug_reset().
debug_jacobianmaxlocation
integer, dimension(2), public debug::debug_jacobianmaxlocation = 0
Definition at line 56 of file debug.f90.
Referenced by debug_info(), and debug_reset().
debug_jacobianmin
real(preal), public debug::debug_jacobianmin = huge(1.0_pReal)
Definition at line 63 of file debug.f90.
Referenced by debug_info(), and debug_reset().
debug_jacobianminlocation
integer, dimension(2), public debug::debug_jacobianminlocation = 0
Definition at line 56 of file debug.f90.
Referenced by debug_info(), and debug_reset().
debug_lattice
integer, parameter, public debug::debug_lattice = 6
stores debug level for lattice part of DAMASK bitwise coded
Definition at line 32 of file debug.f90.
Referenced by debug_init().
debug_level
integer, dimension(debug_maxntype+2), public, protected debug::debug_level = 0
Definition at line 48 of file debug.f90.
Referenced by config::config_init(), damask_spectral(), debug_info(), debug_init(), grid_mech_spectral_basic::formresidual(), grid_mech_fem::formresidual(), grid_mech_spectral_polarisation::formresidual(), homogenization::homogenization_init(), kinematics_cleavage_opening::kinematics_cleavage_opening_init(), kinematics_slipplane_opening::kinematics_slipplane_opening_init(), kinematics_thermal_expansion::kinematics_thermal_expansion_init(), material::material_init(), source_damage_anisobrittle::source_damage_anisobrittle_init(), source_damage_anisoductile::source_damage_anisoductile_init(), source_damage_isobrittle::source_damage_isobrittle_init(), source_damage_isoductile::source_damage_isoductile_init(), source_thermal_dissipation::source_thermal_dissipation_init(), source_thermal_externalheat::source_thermal_externalheat_init(), and spectral_utilities::utilities_init().
debug_levelbasic
integer, parameter, public debug::debug_levelbasic = 2**1
Definition at line 19 of file debug.f90.
Referenced by config::config_init(), damask_spectral(), debug_info(), debug_init(), homogenization::homogenization_init(), kinematics_cleavage_opening::kinematics_cleavage_opening_init(), kinematics_slipplane_opening::kinematics_slipplane_opening_init(), kinematics_thermal_expansion::kinematics_thermal_expansion_init(), material::material_init(), source_damage_anisobrittle::source_damage_anisobrittle_init(), source_damage_anisoductile::source_damage_anisoductile_init(), source_damage_isobrittle::source_damage_isobrittle_init(), source_damage_isoductile::source_damage_isoductile_init(), source_thermal_dissipation::source_thermal_dissipation_init(), source_thermal_externalheat::source_thermal_externalheat_init(), and spectral_utilities::utilities_init().
debug_levelextensive
integer, parameter, public debug::debug_levelextensive = 2**2
Definition at line 19 of file debug.f90.
Referenced by debug_init(), and material::material_init().
debug_levelselective
integer, parameter, public debug::debug_levelselective = 2**0
Definition at line 19 of file debug.f90.
Referenced by debug_init().
debug_marc
integer, parameter, public debug::debug_marc = 12
Definition at line 32 of file debug.f90.
Referenced by debug_init().
debug_material
integer, parameter, public debug::debug_material = 5
stores debug level for material part of DAMASK bitwise coded
Definition at line 32 of file debug.f90.
Referenced by config::config_init(), debug_init(), and material::material_init().
debug_math
integer, parameter, public debug::debug_math = 2
Definition at line 32 of file debug.f90.
Referenced by debug_init().
debug_maxgeneral
integer, parameter, private debug::debug_maxgeneral = debug_LEVELEXTENSIVE private
Definition at line 23 of file debug.f90.
debug_maxntype
integer, parameter, private debug::debug_maxntype = debug_MARC private
must be set to the maximum defined debug type
Definition at line 45 of file debug.f90.
Referenced by debug_init().
debug_mesh
integer, parameter, public debug::debug_mesh = 4
stores debug level for mesh part of DAMASK bitwise coded
Definition at line 32 of file debug.f90.
Referenced by debug_init().
debug_spectral
integer, parameter, public debug::debug_spectral = 11
Definition at line 32 of file debug.f90.
Referenced by damask_spectral(), debug_init(), grid_mech_spectral_basic::formresidual(), grid_mech_fem::formresidual(), grid_mech_spectral_polarisation::formresidual(), and spectral_utilities::utilities_init().
debug_spectraldivergence
integer, parameter, public debug::debug_spectraldivergence = debug_MAXGENERAL*2**3
Definition at line 25 of file debug.f90.
Referenced by debug_init().
debug_spectralfftw
integer, parameter, public debug::debug_spectralfftw = debug_MAXGENERAL*2**2
Definition at line 25 of file debug.f90.
Referenced by debug_init().
debug_spectralpetsc
integer, parameter, public debug::debug_spectralpetsc = debug_MAXGENERAL*2**5
Definition at line 25 of file debug.f90.
Referenced by debug_init(), and spectral_utilities::utilities_init().
debug_spectralrestart
integer, parameter, public debug::debug_spectralrestart = debug_MAXGENERAL*2**1
Definition at line 25 of file debug.f90.
Referenced by debug_init().
debug_spectralrotation
integer, parameter, public debug::debug_spectralrotation = debug_MAXGENERAL*2**4
Definition at line 25 of file debug.f90.
Referenced by debug_init(), grid_mech_spectral_basic::formresidual(), grid_mech_fem::formresidual(), grid_mech_spectral_polarisation::formresidual(), and spectral_utilities::utilities_init().
debug_stressmax
real(preal), public debug::debug_stressmax = -huge(1.0_pReal)
Definition at line 63 of file debug.f90.
Referenced by debug_info(), and debug_reset().
debug_stressmaxlocation
integer, dimension(2), public debug::debug_stressmaxlocation = 0
Definition at line 56 of file debug.f90.
Referenced by debug_info(), and debug_reset().
debug_stressmin
real(preal), public debug::debug_stressmin = huge(1.0_pReal)
Definition at line 63 of file debug.f90.
Referenced by debug_info(), and debug_reset().
debug_stressminlocation
integer, dimension(2), public debug::debug_stressminlocation = 0
Definition at line 56 of file debug.f90.
Referenced by debug_info(), and debug_reset().
petscdebug
character(len=1024), parameter, public debug::petscdebug = ' -snes_view -snes_monitor '
Definition at line 70 of file debug.f90.
Referenced by spectral_utilities::utilities_init().