DAMASK with grid solvers: kinematics_slipplane_opening Module Reference
kinematics_slipplane_opening Module Reference
material subroutine incorporating kinematics resulting from opening of slip planes
Data Types
type tparameters
container type for internal constitutive parameters
Functions/Subroutines
subroutine, public kinematics_slipplane_opening_init
module initialization
subroutine, public kinematics_slipplane_opening_lianditstangent (Ld, dLd_dTstar, S, ipc, ip, el)
contains the constitutive equation for calculating the velocity gradient
Variables
integer, dimension(:), allocatable kinematics_slipplane_opening_instance
type(tparameters), dimension(:), allocatable param
containers of constitutive parameters (len Ninstance)
Detailed Description
material subroutine incorporating kinematics resulting from opening of slip planes
Author
Luv Sharma, Max-Planck-Institut für Eisenforschung GmbH
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
to be done
Function/Subroutine Documentation
kinematics_slipplane_opening_init()
subroutine, public kinematics_slipplane_opening::kinematics_slipplane_opening_init
module initialization
reads in material parameters, allocates arrays, and does sanity checks
Definition at line 53 of file kinematics_slipplane_opening.f90.
References config::config_phase, debug::debug_constitutive, debug::debug_level, debug::debug_levelbasic, io::io_error(), material::kinematics_slipplane_opening_id, kinematics_slipplane_opening_instance, material::kinematics_slipplane_opening_label, lattice::lattice_slip_direction(), lattice::lattice_slip_normal(), lattice::lattice_slip_transverse(), math::math_expand(), math::math_outer(), param, and material::phase_kinematics.
Referenced by constitutive::constitutive_init().
kinematics_slipplane_opening_lianditstangent()
subroutine, public kinematics_slipplane_opening::kinematics_slipplane_opening_lianditstangent (real(preal), dimension(3,3), intent(out) Ld, real(preal), dimension(3,3,3,3), intent(out) dLd_dTstar, real(preal), dimension(3,3), intent(in) S, integer, intent(in) ipc, integer, intent(in) ip, integer, intent(in) el)
contains the constitutive equation for calculating the velocity gradient
Parameters
[in] el element number
[out] ld damage velocity gradient
[out] dld_dtstar derivative of Ld with respect to Tstar (4th-order tensor)
Parameters
ipc grain number
ip integration point number
Definition at line 117 of file kinematics_slipplane_opening.f90.
References kinematics_slipplane_opening_instance, and param.
Referenced by constitutive::constitutive_lianditstangents().
Variable Documentation
kinematics_slipplane_opening_instance
integer, dimension(:), allocatable kinematics_slipplane_opening::kinematics_slipplane_opening_instance private
Definition at line 23 of file kinematics_slipplane_opening.f90.
Referenced by kinematics_slipplane_opening_init(), and kinematics_slipplane_opening_lianditstangent().
param
type(tparameters), dimension(:), allocatable kinematics_slipplane_opening::param private
containers of constitutive parameters (len Ninstance)
Definition at line 39 of file kinematics_slipplane_opening.f90.
Referenced by kinematics_slipplane_opening_init(), and kinematics_slipplane_opening_lianditstangent().