DAMASK with grid solvers: discretization Module Reference
discretization Module Reference
spatial discretization
Functions/Subroutines
subroutine, public discretization_init (homogenizationAt, microstructureAt, IPcoords0, NodeCoords0, sharedNodesBegin)
stores the relevant information in globally accesible variables
subroutine, public discretization_results
write the displacements
subroutine, public discretization_setipcoords (IPcoords)
stores current IP coordinates
subroutine, public discretization_setnodecoords (NodeCoords)
stores current IP coordinates
Variables
integer, public, protected discretization_nip
integer, public, protected discretization_nelem
integer, dimension(:), allocatable, public, protected discretization_homogenizationat
integer, dimension(:), allocatable, public, protected discretization_microstructureat
real(preal), dimension(:,:), allocatable, public, protected discretization_ipcoords0
real(preal), dimension(:,:), allocatable, public, protected discretization_ipcoords
real(preal), dimension(:,:), allocatable, public, protected discretization_nodecoords0
real(preal), dimension(:,:), allocatable, public, protected discretization_nodecoords
integer discretization_sharednodesbegin
Detailed Description
spatial discretization
serves as an abstraction layer between the different solvers and DAMASK
Function/Subroutine Documentation
discretization_init()
subroutine, public discretization::discretization_init (integer, dimension(:), intent(in) homogenizationAt, integer, dimension(:), intent(in) microstructureAt, real(preal), dimension(:,:), intent(in) IPcoords0, real(preal), dimension(:,:), intent(in) NodeCoords0, integer, intent(in), optional sharedNodesBegin)
stores the relevant information in globally accesible variables
Definition at line 48 of file discretization.f90.
References discretization_homogenizationat, discretization_ipcoords, discretization_ipcoords0, discretization_microstructureat, discretization_nelem, discretization_nip, discretization_nodecoords, discretization_nodecoords0, and discretization_sharednodesbegin.
Referenced by discretization_grid::discretization_grid_init().
discretization_results()
subroutine, public discretization::discretization_results
write the displacements
Definition at line 85 of file discretization.f90.
References discretization_ipcoords, discretization_ipcoords0, discretization_nodecoords, discretization_nodecoords0, discretization_sharednodesbegin, results::results_addgroup(), and results::results_closegroup().
Referenced by cpfem2::cpfem_results().
discretization_setipcoords()
subroutine, public discretization::discretization_setipcoords (real(preal), dimension(:,:), intent(in) IPcoords)
stores current IP coordinates
Definition at line 105 of file discretization.f90.
References discretization_ipcoords.
Referenced by spectral_utilities::utilities_updatecoords().
discretization_setnodecoords()
subroutine, public discretization::discretization_setnodecoords (real(preal), dimension(:,:), intent(in) NodeCoords)
stores current IP coordinates
Definition at line 117 of file discretization.f90.
References discretization_nodecoords.
Referenced by spectral_utilities::utilities_updatecoords().
Variable Documentation
discretization_homogenizationat
integer, dimension(:), allocatable, public, protected discretization::discretization_homogenizationat
Definition at line 21 of file discretization.f90.
Referenced by discretization_init(), material::material_init(), and material::material_parsehomogenization().
discretization_ipcoords
real(preal), dimension(:,:), allocatable, public, protected discretization::discretization_ipcoords
Definition at line 25 of file discretization.f90.
Referenced by discretization_init(), discretization_results(), discretization_setipcoords(), and grid_mech_fem::formjacobian().
discretization_ipcoords0
real(preal), dimension(:,:), allocatable, public, protected discretization::discretization_ipcoords0
Definition at line 25 of file discretization.f90.
Referenced by discretization_init(), and discretization_results().
discretization_microstructureat
integer, dimension(:), allocatable, public, protected discretization::discretization_microstructureat
Definition at line 21 of file discretization.f90.
Referenced by discretization_init(), material::material_init(), and material::material_parsemicrostructure().
discretization_nelem
integer, public, protected discretization::discretization_nelem
Definition at line 17 of file discretization.f90.
Referenced by crystallite::crystallite_init(), discretization_init(), homogenization::homogenization_init(), and material::material_init().
discretization_nip
integer, public, protected discretization::discretization_nip
Definition at line 17 of file discretization.f90.
Referenced by crystallite::crystallite_init(), crystallite::crystallite_stress(), discretization_init(), homogenization::homogenization_init(), material::material_init(), select_rotations(), select_tensors(), source_damage_anisobrittle::source_damage_anisobrittle_init(), source_damage_anisoductile::source_damage_anisoductile_init(), source_damage_isobrittle::source_damage_isobrittle_init(), source_damage_isoductile::source_damage_isoductile_init(), source_thermal_dissipation::source_thermal_dissipation_init(), and source_thermal_externalheat::source_thermal_externalheat_init().
discretization_nodecoords
real(preal), dimension(:,:), allocatable, public, protected discretization::discretization_nodecoords
Definition at line 25 of file discretization.f90.
Referenced by discretization_init(), discretization_results(), and discretization_setnodecoords().
discretization_nodecoords0
real(preal), dimension(:,:), allocatable, public, protected discretization::discretization_nodecoords0
Definition at line 25 of file discretization.f90.
Referenced by discretization_init(), and discretization_results().
discretization_sharednodesbegin
integer discretization::discretization_sharednodesbegin private
Definition at line 31 of file discretization.f90.
Referenced by discretization_init(), and discretization_results().