DAMASK with grid solvers: source_damage_anisoductile Module Reference
source_damage_anisoductile Module Reference
material subroutine incorporating anisotropic ductile damage source mechanism
Data Types
type tparameters
container type for internal constitutive parameters
Functions/Subroutines
subroutine, public source_damage_anisoductile_init
module initialization
subroutine, public source_damage_anisoductile_dotstate (ipc, ip, el)
calculates derived quantities from state
subroutine, public source_damage_anisoductile_getrateanditstangent (localphiDot, dLocalphiDot_dPhi, phi, phase, constituent)
returns local part of nonlocal damage driving force
subroutine, public source_damage_anisoductile_results (phase, group)
writes results to HDF5 output file
Variables
integer, dimension(:), allocatable source_damage_anisoductile_offset
which source is my current damage mechanism?
integer, dimension(:), allocatable source_damage_anisoductile_instance
instance of damage source mechanism
type(tparameters), dimension(:), allocatable, private param
containers of constitutive parameters (len Ninstance)
Detailed Description
material subroutine incorporating anisotropic ductile damage source mechanism
Author
Luv Sharma, Max-Planck-Institut für Eisenforschung GmbH
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
to be done
Function/Subroutine Documentation
source_damage_anisoductile_dotstate()
subroutine, public source_damage_anisoductile::source_damage_anisoductile_dotstate (integer, intent(in) ipc, integer, intent(in) ip, integer, intent(in) el)
calculates derived quantities from state
Parameters
[in] el element
Parameters
ipc component-ID of integration point
ip integration point
Definition at line 115 of file source_damage_anisoDuctile.f90.
References param, source_damage_anisoductile_instance, and source_damage_anisoductile_offset.
Referenced by constitutive::constitutive_collectdotstate().
source_damage_anisoductile_getrateanditstangent()
subroutine, public source_damage_anisoductile::source_damage_anisoductile_getrateanditstangent (real(preal), intent(out) localphiDot, real(preal), intent(out) dLocalphiDot_dPhi, real(preal), intent(in) phi, integer, intent(in) phase, integer, intent(in) constituent)
returns local part of nonlocal damage driving force
Definition at line 146 of file source_damage_anisoDuctile.f90.
References source_damage_anisoductile_offset.
source_damage_anisoductile_init()
subroutine, public source_damage_anisoductile::source_damage_anisoductile_init
module initialization
reads in material parameters, allocates arrays, and does sanity checks
Definition at line 54 of file source_damage_anisoDuctile.f90.
References config::config_phase, debug::debug_constitutive, debug::debug_level, debug::debug_levelbasic, discretization::discretization_nip, prec::emptyintarray, prec::emptystringarray, io::io_error(), material::material_allocatesourcestate(), material::material_phaseat, math::math_expand(), param, material::phase_nsources, material::phase_source, material::source_damage_anisoductile_id, source_damage_anisoductile_instance, material::source_damage_anisoductile_label, source_damage_anisoductile_offset, and material::sourcestate.
Referenced by constitutive::constitutive_init().
source_damage_anisoductile_results()
subroutine, public source_damage_anisoductile::source_damage_anisoductile_results (integer, intent(in) phase, character(len=*), intent(in) group)
writes results to HDF5 output file
Definition at line 173 of file source_damage_anisoDuctile.f90.
References param, source_damage_anisoductile_instance, and source_damage_anisoductile_offset.
Variable Documentation
param
type(tparameters), dimension(:), allocatable, private source_damage_anisoductile::param private
containers of constitutive parameters (len Ninstance)
Definition at line 37 of file source_damage_anisoDuctile.f90.
Referenced by source_damage_anisoductile_dotstate(), source_damage_anisoductile_init(), and source_damage_anisoductile_results().
source_damage_anisoductile_instance
integer, dimension(:), allocatable source_damage_anisoductile::source_damage_anisoductile_instance private
instance of damage source mechanism
Definition at line 24 of file source_damage_anisoDuctile.f90.
Referenced by source_damage_anisoductile_dotstate(), source_damage_anisoductile_init(), and source_damage_anisoductile_results().
source_damage_anisoductile_offset
integer, dimension(:), allocatable source_damage_anisoductile::source_damage_anisoductile_offset private
which source is my current damage mechanism?
Definition at line 24 of file source_damage_anisoDuctile.f90.
Referenced by source_damage_anisoductile_dotstate(), source_damage_anisoductile_getrateanditstangent(), source_damage_anisoductile_init(), and source_damage_anisoductile_results().