DAMASK with grid solvers: fesolving Module Reference
fesolving Module Reference
global variables for flow control
Variables
logical terminallyill = .false.
at least one material point is terminally ill
integer, dimension(2) fesolving_execelem
for ping-pong scheme always whole range, otherwise one specific element
integer, dimension(2) fesolving_execip
for ping-pong scheme always range to max IP, otherwise one specific IP
Detailed Description
global variables for flow control
Author
Franz Roters, Max-Planck-Institut für Eisenforschung GmbH
Philip Eisenlohr, Max-Planck-Institut für Eisenforschung GmbH
Variable Documentation
fesolving_execelem
integer, dimension(2) fesolving::fesolving_execelem
for ping-pong scheme always whole range, otherwise one specific element
Definition at line 18 of file FEsolving.f90.
Referenced by crystallite::crystallite_init(), crystallite::crystallite_orientations(), crystallite::crystallite_stress(), crystallite::crystallite_stresstangent(), discretization_grid::discretization_grid_init(), crystallite::integratestatefpi(), and homogenization::materialpoint_stressanditstangent().
fesolving_execip
integer, dimension(2) fesolving::fesolving_execip
for ping-pong scheme always range to max IP, otherwise one specific IP
Definition at line 18 of file FEsolving.f90.
Referenced by crystallite::crystallite_init(), crystallite::crystallite_orientations(), crystallite::crystallite_stress(), crystallite::crystallite_stresstangent(), discretization_grid::discretization_grid_init(), crystallite::integratestatefpi(), and homogenization::materialpoint_stressanditstangent().
terminallyill
logical fesolving::terminallyill = .false.
at least one material point is terminally ill
Definition at line 15 of file FEsolving.f90.
Referenced by grid_mech_spectral_basic::converged(), grid_mech_fem::converged(), grid_mech_spectral_polarisation::converged(), grid_mech_spectral_basic::formresidual(), grid_mech_fem::formresidual(), grid_mech_spectral_polarisation::formresidual(), grid_mech_fem::grid_mech_fem_solution(), grid_mech_spectral_basic::grid_mech_spectral_basic_solution(), grid_mech_spectral_polarisation::grid_mech_spectral_polarisation_solution(), and homogenization::materialpoint_stressanditstangent().