DAMASK with grid solvers: source_damage_isoductile Module Reference
source_damage_isoductile Module Reference
material subroutine incoprorating isotropic ductile damage source mechanism
Data Types
type tparameters
container type for internal constitutive parameters
Functions/Subroutines
subroutine, public source_damage_isoductile_init
module initialization
subroutine, public source_damage_isoductile_dotstate (ipc, ip, el)
calculates derived quantities from state
subroutine, public source_damage_isoductile_getrateanditstangent (localphiDot, dLocalphiDot_dPhi, phi, phase, constituent)
returns local part of nonlocal damage driving force
subroutine, public source_damage_isoductile_results (phase, group)
writes results to HDF5 output file
Variables
integer, dimension(:), allocatable source_damage_isoductile_offset
which source is my current damage mechanism?
integer, dimension(:), allocatable source_damage_isoductile_instance
instance of damage source mechanism
type(tparameters), dimension(:), allocatable, private param
containers of constitutive parameters (len Ninstance)
Detailed Description
material subroutine incoprorating isotropic ductile damage source mechanism
Author
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
Luv Sharma, Max-Planck-Institut für Eisenforschung GmbH
to be done
Function/Subroutine Documentation
source_damage_isoductile_dotstate()
subroutine, public source_damage_isoductile::source_damage_isoductile_dotstate (integer, intent(in) ipc, integer, intent(in) ip, integer, intent(in) el)
calculates derived quantities from state
Parameters
[in] el element
Parameters
ipc component-ID of integration point
ip integration point
Definition at line 108 of file source_damage_isoDuctile.f90.
References param, source_damage_isoductile_instance, and source_damage_isoductile_offset.
Referenced by constitutive::constitutive_collectdotstate().
source_damage_isoductile_getrateanditstangent()
subroutine, public source_damage_isoductile::source_damage_isoductile_getrateanditstangent (real(preal), intent(out) localphiDot, real(preal), intent(out) dLocalphiDot_dPhi, real(preal), intent(in) phi, integer, intent(in) phase, integer, intent(in) constituent)
returns local part of nonlocal damage driving force
Definition at line 139 of file source_damage_isoDuctile.f90.
References source_damage_isoductile_offset.
source_damage_isoductile_init()
subroutine, public source_damage_isoductile::source_damage_isoductile_init
module initialization
reads in material parameters, allocates arrays, and does sanity checks
Definition at line 52 of file source_damage_isoDuctile.f90.
References config::config_phase, debug::debug_constitutive, debug::debug_level, debug::debug_levelbasic, discretization::discretization_nip, prec::emptystringarray, io::io_error(), material::material_allocatesourcestate(), material::material_phaseat, param, material::phase_nsources, material::phase_source, material::source_damage_isoductile_id, source_damage_isoductile_instance, material::source_damage_isoductile_label, source_damage_isoductile_offset, and material::sourcestate.
Referenced by constitutive::constitutive_init().
source_damage_isoductile_results()
subroutine, public source_damage_isoductile::source_damage_isoductile_results (integer, intent(in) phase, character(len=*), intent(in) group)
writes results to HDF5 output file
Definition at line 166 of file source_damage_isoDuctile.f90.
References param, source_damage_isoductile_instance, and source_damage_isoductile_offset.
Variable Documentation
param
type(tparameters), dimension(:), allocatable, private source_damage_isoductile::param private
containers of constitutive parameters (len Ninstance)
Definition at line 35 of file source_damage_isoDuctile.f90.
Referenced by source_damage_isoductile_dotstate(), source_damage_isoductile_init(), and source_damage_isoductile_results().
source_damage_isoductile_instance
integer, dimension(:), allocatable source_damage_isoductile::source_damage_isoductile_instance private
instance of damage source mechanism
Definition at line 23 of file source_damage_isoDuctile.f90.
Referenced by source_damage_isoductile_dotstate(), source_damage_isoductile_init(), and source_damage_isoductile_results().
source_damage_isoductile_offset
integer, dimension(:), allocatable source_damage_isoductile::source_damage_isoductile_offset private
which source is my current damage mechanism?
Definition at line 23 of file source_damage_isoDuctile.f90.
Referenced by source_damage_isoductile_dotstate(), source_damage_isoductile_getrateanditstangent(), source_damage_isoductile_init(), and source_damage_isoductile_results().