DAMASK with grid solvers: source_damage_isobrittle Module Reference
source_damage_isobrittle Module Reference
material subroutine incoprorating isotropic brittle damage source mechanism
Data Types
type tparameters
container type for internal constitutive parameters
Functions/Subroutines
subroutine, public source_damage_isobrittle_init
module initialization
subroutine, public source_damage_isobrittle_deltastate (C, Fe, ipc, ip, el)
calculates derived quantities from state
subroutine, public source_damage_isobrittle_getrateanditstangent (localphiDot, dLocalphiDot_dPhi, phi, phase, constituent)
returns local part of nonlocal damage driving force
subroutine, public source_damage_isobrittle_results (phase, group)
writes results to HDF5 output file
Variables
integer, dimension(:), allocatable source_damage_isobrittle_offset
integer, dimension(:), allocatable source_damage_isobrittle_instance
type(tparameters), dimension(:), allocatable param
containers of constitutive parameters (len Ninstance)
Detailed Description
material subroutine incoprorating isotropic brittle damage source mechanism
Author
Pratheek Shanthraj, Max-Planck-Institut für Eisenforschung GmbH
Luv Sharma, Max-Planck-Institut für Eisenforschung GmbH
to be done
Function/Subroutine Documentation
source_damage_isobrittle_deltastate()
subroutine, public source_damage_isobrittle::source_damage_isobrittle_deltastate (real(preal), dimension(6,6), intent(in) C, real(preal), dimension(3,3), intent(in) Fe, integer, intent(in) ipc, integer, intent(in) ip, integer, intent(in) el)
calculates derived quantities from state
Parameters
[in] el element
Parameters
ipc component-ID of integration point
ip integration point
Definition at line 109 of file source_damage_isoBrittle.f90.
References param, source_damage_isobrittle_instance, and source_damage_isobrittle_offset.
Referenced by constitutive::constitutive_collectdeltastate().
source_damage_isobrittle_getrateanditstangent()
subroutine, public source_damage_isobrittle::source_damage_isobrittle_getrateanditstangent (real(preal), intent(out) localphiDot, real(preal), intent(out) dLocalphiDot_dPhi, real(preal), intent(in) phi, integer, intent(in) phase, integer, intent(in) constituent)
returns local part of nonlocal damage driving force
Definition at line 155 of file source_damage_isoBrittle.f90.
References param, source_damage_isobrittle_instance, and source_damage_isobrittle_offset.
source_damage_isobrittle_init()
subroutine, public source_damage_isobrittle::source_damage_isobrittle_init
module initialization
reads in material parameters, allocates arrays, and does sanity checks
Definition at line 53 of file source_damage_isoBrittle.f90.
References config::config_phase, debug::debug_constitutive, debug::debug_level, debug::debug_levelbasic, discretization::discretization_nip, prec::emptystringarray, io::io_error(), material::material_allocatesourcestate(), material::material_phaseat, param, material::phase_nsources, material::phase_source, material::source_damage_isobrittle_id, source_damage_isobrittle_instance, material::source_damage_isobrittle_label, source_damage_isobrittle_offset, and material::sourcestate.
Referenced by constitutive::constitutive_init().
source_damage_isobrittle_results()
subroutine, public source_damage_isobrittle::source_damage_isobrittle_results (integer, intent(in) phase, character(len=*), intent(in) group)
writes results to HDF5 output file
Definition at line 184 of file source_damage_isoBrittle.f90.
References param, source_damage_isobrittle_instance, and source_damage_isobrittle_offset.
Variable Documentation
param
type(tparameters), dimension(:), allocatable source_damage_isobrittle::param private
containers of constitutive parameters (len Ninstance)
Definition at line 36 of file source_damage_isoBrittle.f90.
Referenced by source_damage_isobrittle_deltastate(), source_damage_isobrittle_getrateanditstangent(), source_damage_isobrittle_init(), and source_damage_isobrittle_results().
source_damage_isobrittle_instance
integer, dimension(:), allocatable source_damage_isobrittle::source_damage_isobrittle_instance private
Definition at line 24 of file source_damage_isoBrittle.f90.
Referenced by source_damage_isobrittle_deltastate(), source_damage_isobrittle_getrateanditstangent(), source_damage_isobrittle_init(), and source_damage_isobrittle_results().
source_damage_isobrittle_offset
integer, dimension(:), allocatable source_damage_isobrittle::source_damage_isobrittle_offset private
Definition at line 24 of file source_damage_isoBrittle.f90.
Referenced by source_damage_isobrittle_deltastate(), source_damage_isobrittle_getrateanditstangent(), source_damage_isobrittle_init(), and source_damage_isobrittle_results().