DAMASK with grid solvers: cpfem2 Module Reference
cpfem2 Module Reference
needs a good name and description
Functions/Subroutines
subroutine cpfem_initall
call all module initializations
subroutine cpfem_init
Read restart information if needed.
subroutine cpfem_restartwrite
Write restart information.
subroutine cpfem_forward
Forward data for new time increment.
subroutine cpfem_results (inc, time)
Trigger writing of results.
Detailed Description
needs a good name and description
Author
Franz Roters, Max-Planck-Institut für Eisenforschung GmbH
Philip Eisenlohr, Max-Planck-Institut für Eisenforschung GmbH
Function/Subroutine Documentation
cpfem_forward()
subroutine cpfem2::cpfem_forward
Forward data for new time increment.
Definition at line 100 of file CPFEM2.f90.
References crystallite::crystallite_forward().
Referenced by damask_spectral().
cpfem_init()
subroutine cpfem2::cpfem_init
Read restart information if needed.
Definition at line 78 of file CPFEM2.f90.
References crystallite::crystallite_restartread(), and damask_interface::interface_restartinc.
Referenced by cpfem_initall().
cpfem_initall()
subroutine cpfem2::cpfem_initall
call all module initializations
Definition at line 45 of file CPFEM2.f90.
References config::config_init(), constitutive::constitutive_init(), cpfem_init(), crystallite::crystallite_init(), damask_interface::damask_interface_init(), debug::debug_init(), hdf5_utilities::hdf5_utilities_init(), homogenization::homogenization_init(), io::io_init(), lattice::lattice_init(), material::material_init(), math::math_init(), numerics::numerics_init(), prec::prec_init(), results::results_init(), and rotations::rotations_init().
Referenced by damask_spectral().
cpfem_restartwrite()
subroutine cpfem2::cpfem_restartwrite
Write restart information.
Definition at line 90 of file CPFEM2.f90.
References crystallite::crystallite_restartwrite().
Referenced by damask_spectral().
cpfem_results()
subroutine cpfem2::cpfem_results (integer, intent(in) inc, real(preal), intent(in) time)
Trigger writing of results.
Definition at line 110 of file CPFEM2.f90.
References constitutive::constitutive_results(), crystallite::crystallite_results(), discretization::discretization_results(), homogenization::homogenization_results(), results::results_addincrement(), results::results_closejobfile(), results::results_finalizeincrement(), and results::results_openjobfile().
Referenced by damask_spectral().