DAMASK with grid solvers: geometry_plastic_nonlocal Module Reference
geometry_plastic_nonlocal Module Reference
Geometric information about the IP cells needed for the nonlocal.
Functions/Subroutines
subroutine geometry_plastic_nonlocal_setipneighborhood (IPneighborhood)
Set the integration point (IP) neighborhood.
subroutine geometry_plastic_nonlocal_setipvolume (IPvolume)
Set the initial volume associated with an integration point.
subroutine geometry_plastic_nonlocal_setiparea (IParea)
Set the initial areas of the unit triangle/unit quadrilateral/tetrahedron/hexahedron.
subroutine geometry_plastic_nonlocal_setipareanormal (IPareaNormal)
Set the direction normal of the areas of the triangle/quadrilateral/tetrahedron/hexahedron.
subroutine geometry_plastic_nonlocal_disable
Free memory used by variables only needed by plastic_nonlocal.
subroutine geometry_plastic_nonlocal_results
Write geometry data to results file.
Variables
integer, protected geometry_plastic_nonlocal_nipneighbors
integer, dimension(:,:,:,:), allocatable, protected geometry_plastic_nonlocal_ipneighborhood
6 or less neighboring IPs as [element ID, IP ID, face ID that point to me]
real(preal), dimension(:,:), allocatable, protected geometry_plastic_nonlocal_ipvolume0
volume associated with IP (initially!)
real(preal), dimension(:,:,:), allocatable, protected geometry_plastic_nonlocal_iparea0
area of interface to neighboring IP (initially!)
real(preal), dimension(:,:,:,:), allocatable, protected geometry_plastic_nonlocal_ipareanormal0
area normal of interface to neighboring IP (initially!)
Detailed Description
Geometric information about the IP cells needed for the nonlocal.
Author
Philip Eisenlohr, Max-Planck-Institut f端r Eisenforschung GmbH
Christoph Koords, Max-Planck-Institut f端r Eisenforschung GmbH
Martin Diehl, Max-Planck-Institut f端r Eisenforschung GmbH
Function/Subroutine Documentation
geometry_plastic_nonlocal_disable()
subroutine geometry_plastic_nonlocal::geometry_plastic_nonlocal_disable
Free memory used by variables only needed by plastic_nonlocal.
Definition at line 98 of file geometry_plastic_nonlocal.f90.
References geometry_plastic_nonlocal_iparea0, geometry_plastic_nonlocal_ipareanormal0, geometry_plastic_nonlocal_ipneighborhood, and geometry_plastic_nonlocal_ipvolume0.
Referenced by constitutive::constitutive_init().
geometry_plastic_nonlocal_results()
subroutine geometry_plastic_nonlocal::geometry_plastic_nonlocal_results
Write geometry data to results file.
Definition at line 118 of file geometry_plastic_nonlocal.f90.
References geometry_plastic_nonlocal_iparea0, geometry_plastic_nonlocal_ipareanormal0, geometry_plastic_nonlocal_ipvolume0, and results::results_openjobfile().
geometry_plastic_nonlocal_setiparea()
subroutine geometry_plastic_nonlocal::geometry_plastic_nonlocal_setiparea (real(preal), dimension(:,:,:), intent(in) IParea)
Set the initial areas of the unit triangle/unit quadrilateral/tetrahedron/hexahedron.
Definition at line 73 of file geometry_plastic_nonlocal.f90.
References geometry_plastic_nonlocal_iparea0.
Referenced by discretization_grid::discretization_grid_init().
geometry_plastic_nonlocal_setipareanormal()
subroutine geometry_plastic_nonlocal::geometry_plastic_nonlocal_setipareanormal (real(preal), dimension(:,:,:,:), intent(in) IPareaNormal)
Set the direction normal of the areas of the triangle/quadrilateral/tetrahedron/hexahedron.
Definition at line 86 of file geometry_plastic_nonlocal.f90.
References geometry_plastic_nonlocal_ipareanormal0.
Referenced by discretization_grid::discretization_grid_init().
geometry_plastic_nonlocal_setipneighborhood()
subroutine geometry_plastic_nonlocal::geometry_plastic_nonlocal_setipneighborhood (integer, dimension(:,:,:,:), intent(in) IPneighborhood)
Set the integration point (IP) neighborhood.
: The IP neighborhood for element ID (last index), IP ID (second but last index) and
Definition at line 46 of file geometry_plastic_nonlocal.f90.
References geometry_plastic_nonlocal_ipneighborhood, and geometry_plastic_nonlocal_nipneighbors.
Referenced by discretization_grid::discretization_grid_init().
geometry_plastic_nonlocal_setipvolume()
subroutine geometry_plastic_nonlocal::geometry_plastic_nonlocal_setipvolume (real(preal), dimension(:,:), intent(in) IPvolume)
Set the initial volume associated with an integration point.
Definition at line 60 of file geometry_plastic_nonlocal.f90.
References geometry_plastic_nonlocal_ipvolume0.
Referenced by discretization_grid::discretization_grid_init().
Variable Documentation
geometry_plastic_nonlocal_iparea0
real(preal), dimension(:,:,:), allocatable, protected geometry_plastic_nonlocal::geometry_plastic_nonlocal_iparea0
area of interface to neighboring IP (initially!)
Definition at line 28 of file geometry_plastic_nonlocal.f90.
Referenced by geometry_plastic_nonlocal_disable(), geometry_plastic_nonlocal_results(), and geometry_plastic_nonlocal_setiparea().
geometry_plastic_nonlocal_ipareanormal0
real(preal), dimension(:,:,:,:), allocatable, protected geometry_plastic_nonlocal::geometry_plastic_nonlocal_ipareanormal0
area normal of interface to neighboring IP (initially!)
Definition at line 31 of file geometry_plastic_nonlocal.f90.
Referenced by geometry_plastic_nonlocal_disable(), geometry_plastic_nonlocal_results(), and geometry_plastic_nonlocal_setipareanormal().
geometry_plastic_nonlocal_ipneighborhood
integer, dimension(:,:,:,:), allocatable, protected geometry_plastic_nonlocal::geometry_plastic_nonlocal_ipneighborhood
6 or less neighboring IPs as [element ID, IP ID, face ID that point to me]
Definition at line 22 of file geometry_plastic_nonlocal.f90.
Referenced by geometry_plastic_nonlocal_disable(), and geometry_plastic_nonlocal_setipneighborhood().
geometry_plastic_nonlocal_ipvolume0
real(preal), dimension(:,:), allocatable, protected geometry_plastic_nonlocal::geometry_plastic_nonlocal_ipvolume0
volume associated with IP (initially!)
Definition at line 25 of file geometry_plastic_nonlocal.f90.
Referenced by geometry_plastic_nonlocal_disable(), geometry_plastic_nonlocal_results(), and geometry_plastic_nonlocal_setipvolume().
geometry_plastic_nonlocal_nipneighbors
integer, protected geometry_plastic_nonlocal::geometry_plastic_nonlocal_nipneighbors
Definition at line 19 of file geometry_plastic_nonlocal.f90.
Referenced by geometry_plastic_nonlocal_setipneighborhood().