DAMASK with grid solvers: quit.f90 File Reference
quit.f90 File Reference
Functions/Subroutines
subroutine quit (stop_id)
quit subroutine
Function/Subroutine Documentation
quit()
subroutine quit (integer, intent(in) stop_id)
quit subroutine
Author
Martin Diehl, Max-Planck-Institut für Eisenforschung GmbH
exits the program and reports current time and duration. Exit code 0 signals everything is fine. Exit code 1 signals an error, message according to IO_error.
Definition at line 12 of file quit.f90.
Referenced by damask_interface::damask_interface_init(), damask_spectral(), damask_interface::getgeometryfile(), damask_interface::getloadcasefile(), io::io_error(), damask_interface::setworkingdirectory(), and prec::unittest().