DAMASK with grid solvers: quaternions::quaternion Interface Reference
quaternions::quaternion Interface Reference
Public Member Functions
generic, public operator => add__, pos__
generic, public operator => sub__, neg__
generic, public operator => mul_quat__, mul_scal__
generic, public operator => div_quat__, div_scal__
generic, public operator => eq__
generic, public operator => neq__
generic, public operator => pow_quat__, pow_scal__
procedure, public abs => abs__
procedure, public conjg => conjg__
procedure, public real => real__
procedure, public aimag => aimag__
procedure, public homomorphed
procedure, public asarray
procedure, public inverse
Private Member Functions
procedure, private add__
procedure, private pos__
procedure, private sub__
procedure, private neg__
procedure, private mul_quat__
procedure, private mul_scal__
procedure, private div_quat__
procedure, private div_scal__
procedure, private eq__
procedure, private neq__
procedure, private pow_quat__
procedure, private pow_scal__
type(quaternion) pure function init__ (array)
construct a quaternion from a 4-vector
Private Attributes
real(preal), private w = 0.0_pReal
real(preal), private x = 0.0_pReal
real(preal), private y = 0.0_pReal
real(preal), private z = 0.0_pReal
Detailed Description
Definition at line 21 of file quaternions.f90.
Member Function/Subroutine Documentation
abs()
procedure, public quaternions::quaternion::abs
Definition at line 55 of file quaternions.f90.
add__()
procedure, private quaternions::quaternion::add__ private
Definition at line 29 of file quaternions.f90.
aimag()
procedure, public quaternions::quaternion::aimag
Definition at line 58 of file quaternions.f90.
asarray()
procedure, public quaternions::quaternion::asarray
Definition at line 61 of file quaternions.f90.
conjg()
procedure, public quaternions::quaternion::conjg
Definition at line 56 of file quaternions.f90.
div_quat__()
procedure, private quaternions::quaternion::div_quat__ private
Definition at line 41 of file quaternions.f90.
div_scal__()
procedure, private quaternions::quaternion::div_scal__ private
Definition at line 42 of file quaternions.f90.
eq__()
procedure, private quaternions::quaternion::eq__ private
Definition at line 45 of file quaternions.f90.
homomorphed()
procedure, public quaternions::quaternion::homomorphed
Definition at line 60 of file quaternions.f90.
init__()
type(quaternion) pure function quaternions::quaternion::init__ (real(preal), dimension(4), intent(in) array) private
construct a quaternion from a 4-vector
Definition at line 128 of file quaternions.f90.
inverse()
procedure, public quaternions::quaternion::inverse
Definition at line 62 of file quaternions.f90.
mul_quat__()
procedure, private quaternions::quaternion::mul_quat__ private
Definition at line 37 of file quaternions.f90.
mul_scal__()
procedure, private quaternions::quaternion::mul_scal__ private
Definition at line 38 of file quaternions.f90.
neg__()
procedure, private quaternions::quaternion::neg__ private
Definition at line 34 of file quaternions.f90.
neq__()
procedure, private quaternions::quaternion::neq__ private
Definition at line 48 of file quaternions.f90.
operator() [1/7]
generic, public quaternions::quaternion::operator
Definition at line 31 of file quaternions.f90.
References quaternions::add__(), and quaternions::pos__().
operator() [2/7]
generic, public quaternions::quaternion::operator
Definition at line 43 of file quaternions.f90.
References quaternions::div_quat__(), and quaternions::div_scal__().
operator() [3/7]
generic, public quaternions::quaternion::operator
Definition at line 46 of file quaternions.f90.
References quaternions::eq__().
operator() [4/7]
generic, public quaternions::quaternion::operator
Definition at line 39 of file quaternions.f90.
References quaternions::mul_quat__(), and quaternions::mul_scal__().
operator() [5/7]
generic, public quaternions::quaternion::operator
Definition at line 49 of file quaternions.f90.
References quaternions::neq__().
operator() [6/7]
generic, public quaternions::quaternion::operator
Definition at line 53 of file quaternions.f90.
References quaternions::pow_quat__(), and quaternions::pow_scal__().
operator() [7/7]
generic, public quaternions::quaternion::operator
Definition at line 35 of file quaternions.f90.
References quaternions::neg__(), and quaternions::sub__().
pos__()
procedure, private quaternions::quaternion::pos__ private
Definition at line 30 of file quaternions.f90.
pow_quat__()
procedure, private quaternions::quaternion::pow_quat__ private
Definition at line 51 of file quaternions.f90.
pow_scal__()
procedure, private quaternions::quaternion::pow_scal__ private
Definition at line 52 of file quaternions.f90.
real()
procedure, public quaternions::quaternion::real
Definition at line 57 of file quaternions.f90.
sub__()
procedure, private quaternions::quaternion::sub__ private
Definition at line 33 of file quaternions.f90.
Member Data Documentation
w
real(preal), private quaternions::quaternion::w = 0.0_pReal private
Definition at line 22 of file quaternions.f90.
x
real(preal), private quaternions::quaternion::x = 0.0_pReal private
Definition at line 23 of file quaternions.f90.
y
real(preal), private quaternions::quaternion::y = 0.0_pReal private
Definition at line 24 of file quaternions.f90.
z
real(preal), private quaternions::quaternion::z = 0.0_pReal private
Definition at line 25 of file quaternions.f90.
The documentation for this interface was generated from the following file:
quaternions.f90