6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        56         63         17         48         54         47         24          5          1         45
        20         57         53         30         46         19         51         14         22          7
        27          6         49         11          9          4         10         12         23          8
        29         43         64         28         26         50         13         31         61         32
        38         44         35          3         58         36         15         16         62         39
        41         60         59         55         33         18         52         42         25          2
        21         40         37         34