6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         8         38         43         52         49         24         12         15         56         19
        47         30         54         23          4         21         37         11         58         13
         7         50         36         45         10         59          2         57          5         60
         3         32         41          9         31         62         26         40         17          6
        53         42         22         35         33         34         39          1         28         29
        18         48         51         61         44         46         14         63         16         64
        27         25         55         20