6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         7         17         36         33         32         15         47         13         54         26
        56         59         48         11         57         41         34         37         40         22
        62         43         50         46         31         49         10         14          2         35
        25         52          8         63         19         38         23         21          3         24
         6         61         28         27         39         51         60         29         42         58
         5         45         44         30          4          1         55         64         12         18
        20         16         53          9