6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        37         35         40         50         11          4         16         34         20         64
         8         55         39         51         27         46         17         53         42          1
        62         48          7         10         30         32         14         12         28         49
        43          6         44         58         57         61         21         18         45         47
        24         63          2         15         33         29         60         38         23         26
         3          9         56         22         59         25          5         19         36         52
        54         31         13         41