6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        18         57         63         35         60         41         14         21         33         23
        51         50         40         55         30          8          5         37          7         39
        26         47         20         44         24         34         19         46         10         25
        64         59         58         56         61         54         12          6         36         38
        43          3          4         49         31         42         28         22         53         62
         2         16         17         52         29         13         15         45         27          1
         9         11         32         48