6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        15         11         18         16         26         44         13         53         54         57
        64         19         17         38         46          6          8         37         59         49
        56         22          5         27         33         52         31         55         60         36
        51         21         40         39          9         24          7          2         45         50
        25         14          3         23          1         62         35         32         48         63
        43         10         28         42         20         34         30         29          4         41
        12         58         61         47