6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        18         21         20         49          4         62         63         42         59          5
        41          1          6         53         35         57         22         36         11          9
        10          8         47         45         30         29         46         23          2         25
        38         51         39         43         44         37         13         55         27         50
        17         58         52         33         28         32         48         24         61         12
        26         54         31         16         60          7         19         34         15          3
        14         64         40         56