6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        29         57         22         11         53         13         48         47         46          3
        43         58          8         38         20         30         14         62         54         40
        52         18         12         25         27         45         44         50         21         63
        33         60         24         42         61         56         16          9         36          6
        32         35         15         64         34         19         17         55          1          4
        51          7          5         39          2         10         31         37         26         23
        49         41         28         59