6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         3         31          5         16         28         46         35         12         61         37
        18         32         51         21         13         64         25          8          4         52
        40         34         23          9         50         56         38         62         45          2
        15         60         17         42         55         63         10         36         14         58
         7         11         53         19         24         59         49         22         41         29
        39         27         30         57          6         54         43         48         26         20
        44         33          1         47