6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        54         36         39         35         38         58         16         21          9         30
        55         41         50         42         14         59         60         23         32         12
        13          1          7         56         31         48         49          8         57         17
        51         11         47         46          2         26         15         18         10         45
         4         27         22          5         34          6          3         19         64         43
        40         25         29         44         37         63         53         61         33         62
        28         24         20         52