6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        51         45         44         30          7          5         22         60         50          3
        43          8         23         37         24         61         25         56         27         40
         1         18         34         31         32         64         38         55         53         13
        29         41         35         49         16          9         21         63         28         12
         2         57         17         52         58         26         54         15          6         14
        33         11         39         42         59         19         10         36         20         47
        46         48         62          4