6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        14         41         50         13         15         45         43         60         27         25
        17         26         54         35         40         33         47         52         48         30
         3         11         38         44         39         55         62          8          9         12
        42         16          5         23         61         58         59         57         31         32
        34         49         21         24         53          7         28         10         29         64
        37          2         22          4          6         56         18         46         63         19
        20         51          1         36