6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         3         15         62         63          1         37         56         47          2         19
        17          9         28         42         22         23         11         24         40         32
        10         46         50         53         52         55         14         30         21         29
        48          4         25          6         38         43         49         57         41         34
        16         31         45         12         20         39         18         36         64         13
        35         44         51         61         58          5         54         33          7         26
        27         60         59          8