6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        52         57         51         38         56         44          4          2         36         31
        35         61         25         19         30         45         49         59          6         46
        28         26         12         18         32         37         41          8         15         22
        40          9         33         24          5          1         58         13         27         17
        39         55         23         60         53         16         10         54         47         64
        34         48         43         50         14          3         20         62         21         11
        42         29         63          7