6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        38         36         30         20         49         56         42         50         18         47
        53         23         54         51         52         11          3         59         62         57
         7         24          4         37         14         55         29         40         25         64
         5         32         26         12         39         21          2         22         16         58
        48         27          6         15         28          1         10          9         46         13
        63         31         35         34         61         44         45         60         19         43
        41         33          8         17