6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        18          6         60         26         13         20         35         24         55         49
        53         27         48         32         54         38          3          7          4         44
        42         56         22         36         16         50          9         62         17         28
        59         11         30         58         15         25         47         57         41         40
        64         10         29          8         37         45         46         34         33         61
        52         21         39         19         43         23         12          2         51         63
        14         31          1          5