6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        42         29         37         10         49         45          1         34         61          8
         6         18         15          5         44         19         16         62          2         50
        11         30         36         59         52         38         57         12         20         39
        22          7         64         25         46         58         53         51          4         26
        35          3         55         24         41         56         13         23         31         47
        32         21          9         28         40         43         54         60         63         14
        33         27         17         48