6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        18         11         54         13         45         32          7         23          5          4
        16          8         27         47         51          6         63         40         53         50
        35         48         31         30          2         52         15         55         44         56
        59         62         57          1         26         60         58         42          3          9
        38         12         49         28         36         39         22         64         46         43
        10         41         24         61         20         19         34         25         33         17
        21         14         29         37