6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        54         61         32         18         19         33         13          2         29         49
        23         31          9         25         34          1         28          7         52          5
        57         22          3         17         55         43         56         51         53          4
        20         60         27         35         62         42          8         48         39         59
        58         37          6         40         30         50         46         15         16         63
        44         47         12         24         45         14         21         36         26         41
        11         10         64         38