6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        60         46         56         28         41         62         45         57         29         11
         3         38         16         14          5         22         19         18         52         63
        20         25         49         12         43          9         26         13         55         61
        44         27         24         50          8         15         51         21         64         37
        42         54          7         35         17         40         48          6         10         47
        23         53         32          4          1          2         58         30         31         59
        39         33         34         36