6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        25         18         10         57         34          7          9         58         47         44
        42         41         24         61         13         63         30         27         40         16
        21         56          2         50         37          4         46          1         45         60
        64         15         55         35         33         43         62         53         23          8
         6         59         52          3         26         29         54         51         14         31
         5         11         17         20         38         12         36         48         19         39
        32         28         22         49