6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        64         10         43         28         48          5          1         17         31         20
        38          2         40         27         56         37         29         62          8         32
        21         41         47         57         51          9         23         16         12         13
        33         60         36         49         14          7         44         15         30         45
        55         53         58         39         61         46         63          4         19         22
        35         24          6         25         34         42         59         52         18         54
        50          3         11         26