6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        62         21         16         45          8         22         15         10         31         17
        18          6         53         49         27         54         50          7          1          9
        29         11         13          5         28         52         12         43         59         41
         2         35          4         55         44         24         19         33          3         60
        40         37         23         26         51         20         42         57         56         30
        63         47         61         38         39         64         48         36         14         34
        25         46         32         58