6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        35         27          5         58         19         10         11         20         54         64
        36         57         63         15         25         60         24         23         31         44
         7         51         18         41         53         46         39         17         33         47
        62         43         61          2          8         52         26         29         48         38
        45         59         16         14          3          1         32         42         40         55
        34         13          4         56         30          6         37         28          9         21
        22         49         12         50