6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        36         30         41         23         61         60          9          5         44         49
        45         31         13          1         63         46         21         48         34         15
        50         59          4         42         32         47          8         52         54         53
        10         18         58         37         22         20         19         62          7         51
        25         33         57          2         16         29         17         39         64         43
         6         27         55          3         12         26         40         14         35         11
        24         38         28         56