6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        34         13         12         14         11         40         21         30         33         37
        53         63         52         39         28          9         31         24         46         19
        49         25          6          2          1         43          7         35         61         48
        44         50          4         10          3         55         64          8         42         32
        18         27         59         15         56         26         16         22         45         51
        29         62         47         20         38         41         54         58         57          5
        36         60         23         17