6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        62         51         30          5         16         57         34         28          8          9
        61         44         20         37         25         10         46         22         12         60
        54          3          2         23         38         59          6         55          4         27
        63         17         13         58         39         32         48         64         15         19
        45          1         42         50         11         40         53         26          7         33
        49         43         31         24         14         36         18         56         47         21
        35         52         41         29