6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        55         39          9         53         40          8         51          6         34          3
        23         32         33          1         63         38         48         28         49         16
        11         24         36         31         12         27         21         35         14         43
        19         41         10         44         59         22         45         57         64          7
        62         17         60         25         47         61          4         56         18         15
         5          2         50         58         26         20         30         46         52         37
        54         42         13         29