6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        58         60         10          6         36         20         32         38         41         56
        37         23         15         47         53          8          7         45         12         55
         2         57          4         13         27          5         25         64         11         21
        19         48         28         22         50         61         49         52         34         42
        62          3         46         35         18         54         16         24         31         51
        14         59          9         40         30         17         29          1         44         39
        43         63         33         26