6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        48          2         38         25         59         15         30         58         17          3
         9         50         11         16         26         46         44         61          4         43
        62         21          1         49         35          5         33          6         55         54
        32         29         57         23         60         14         24         34         64         19
        22         42         53         63         12         39         47         37         18          7
        13         51         31         10         41         28         27         40         52          8
        56         36         20         45