6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        20          1         14          9         42         41         59         57         44         56
        43         22         49         54         13         27         58         52         18         63
        35         37         51         11         21         26          3         25          2         23
        60         29         30         15          4         46         62         48         45          7
        24         50         36         39         31          6         17         33         64         55
        16          8         38         40         47         10         12         19         34         32
        53          5         28         61