6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        43         46         15         53          4         52         11         40         60         38
        45         25         55         35         31         62         17         18         41          7
         9         26          2         63          1         28         58          6         44         64
        42         12          3         37         57         49         54         59          8         16
        21         27         50         19         20         48         10         39         30         29
        36         56         23         22         32         24         13          5         34         14
        51         33         61         47