6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        59         17         61         12          1         32         35          2         19         26
        21         64         30          9         54         31         11         41         15          3
        10         22         36         55         24         16         47         49         28         13
        14         20         18         39          8         40         60         63         52         37
        58         48         56         45         43         38         27          7         25         34
        23         50          4         46         57         44         53         51          5         42
         6         33         29         62