6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        11         10         21         24         54         25         36          3         19         53
        52         59         16          9         61         27          2         15         12         20
         4         43         17          1         39         26          5         46         30         35
         8         18         33         38         50         22         47         55         44         28
        13         60         31         23         57         49         51         63         37         32
        41          6          7         64         48         29         45         42         62         14
        34         58         56         40