6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        34          7         18         56          5          6         60         22         25         55
        63          3         54         59         26         23          1         30          9         64
        27         28         42         19         43         49         37         39         41         14
        51          8         40         35          2         31         20         48         53         46
        13         17         44         10         57         58         50         32         61         33
        36         11         24         62          4         21         16         52         47         29
        45         12         15         38