6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        44          8         33         64         34         11          9         57         27         16
        49         61         37         50         43         51         55         56         54          1
        47         58         22          3         13          6         53         32         48         40
         2         59         18         14         15          5         31         23          4         29
        62         39         35         38         41         52         45         17          7         10
        63         46         12         26         30         24         21         60         28         25
        20         42         36         19