6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        36         12         52         45         42         18         16         54         40         11
        35         30         44         46         64         56         37         39         28          2
         4          7         49         21         17          9         22         50         34          8
        48         13         57         19         63         59         15          1         60         41
        61          5         14         33         29         24         53          3         43         20
        51         26         38          6         31         58         62         27         47         10
        25         32         55         23