6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        36         47         39         51         45         17         18         42         54          1
        53         11         22         64         24          6         10         26         41         50
         3         13         44         58         46         14         61         48         31         19
        29         32         49         38         25         62         59         37         34         28
         9         40         27         52         15         21         60          7         57         12
        30         23         33         56          2          8         63          5         55         20
        35         16          4         43