6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        34         55          4         38         25         56         14          7         59         12
         1         41         11         58          8         62         63         61         52         21
        19         44         46         51         39         45         20         60         47         49
        33         42         24         54         37          2         16         26         10         35
         3         15          9         29         43         17         40         13         57         36
        32         53          5          6         27         18         31         30         50         28
        64         22         48         23