6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         9         53         39         13          1         17          3         42          6          5
         7         37         43         20         51         58         16         62         57          2
        22         36         44         24         35         25         19         45         47         27
         8         55         31         14         52         26          4         12         61         56
        11         49         60         30         50         54         23         38         18         32
        41         33         15         10         48         21         46         40         63         29
        28         59         34         64