6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        17         45          1         44         30         56         50          9         63         33
        39         34         48         32         16          2         15         36          5         64
        18         35         58         24         53         54         25         21          6         23
        59         52          8         55         51         43          3         14         28         20
        61         37         41         42         46         11         38         47         13         60
        26         27          4         19         10         49         31         22         12         57
         7         40         62         29