6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         7         23         49         61         15         29         52         54         28         62
        31         57         32         17         25         26         21         22         39          5
        35          6         55          8         20         19         34          2         27         33
        58         59         37         43         44         45         63         51          3         14
        40         10          9         18         24         47         30         11         42         53
         1         36         60         48         64         41         38         46         16         12
        50          4         56         13