6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        64         32         31         23          9         12         53         15          4         62
        63         42         17         55         60         25         59         38         33         18
        14          6         48         34         47         10         27         19         29         61
         3         49         21         22         37         58         44         50         20         40
         2         26          7         51         56         57         36          1         16         30
        35         28         52         24         54         13          5         41          8         11
        39         43         45         46