6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        26          2         42         59         64         48         19         29         10         15
         1         61         57         46         50         41         21         23          9         54
         7         14         43         35         49         60         62         58         37         44
        63         20          4         32          8         13          3         55         34         11
        22         39         40         33         27         47         17         51         45         30
        25         53         52         24          5         36         31         38          6         18
        28         12         16         56