6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        20         29         24         37         47         30         49         38         59         50
        61         27         23         28         11         46         25          4         36         13
        52         32         18         35         15          7         60         42          6         16
        19         58         56         45         40         57          9         64         33         62
        54         51         34         39         26         63         12         43         44          8
        55          2         53         21          5          1         31         48          3         41
        14         10         17         22