6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        38          9         29         50         28         45         59         16         64          5
         2         22         31         35         21         24         41         62         39         51
         3         52         33         23         47         13         37         61         18         63
        10         53         36         42         15         19         48         34         11         40
        26         55         32         17         56          1         46         60          6          4
        12         14         49         43          8         27         30         20         44         25
        54         58          7         57