6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        56          7         51         31         59         55         62         18         60         41
        42         11         13         40         28         63         21          4         19         23
        47         27         24         12         35         36          8         26         20         45
         6          9         33         61         15         46         38         49         39         54
         1         53         50          2         37         29         48         14         44         30
         3         64         58         32         17         10          5         52         22         43
        25         34         57         16