6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         4         49         11          9         34         10         18          8         41         23
        38         12         28         39         17         20         26         24         31          1
         5         22         53         56         55         52         61         43         30         62
        13         64         37         27         32         59         48         51         57          3
        36         46         58         14          7         60         33          6         45         21
        63         40         19          2         42         50         44         54         29         15
        35         47         25         16