6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        46         25         54         40         53         43         13         38         28         45
         5         12         37         33         36         20         42          4         52         55
        10         60         31         50         51          9         49         62         56         35
        15          3         29         61         22         24         26          6         11          8
        19         41         39         30         21         14         44         63         57         23
        18         48          2         16         34          1         17         47          7         59
        32         64         27         58