6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         5         50          4         22         40         56         31         18         25          3
        33         51         58         47         26          2         14         17         37         13
        20         49         24         53         12         42         64         43         38          8
        44          7         63         10         45         30         57         29         48         19
         9         34         21         27          1         54         59         11         16         55
        41         15         32         23         28         35         60          6         39         52
        46         62         61         36