6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        25          7         39          1         61         15         50         43         60         30
        37          8         28         31         19         17         24          6         63          9
        62         55         49         59         16         46         51         41         35         27
        52         44         12          4         34         11         57         32         48         42
         3         10         56         53          5         33         47         18         54         23
        14         20         21         22         40         13         26         58         45         38
        36         29          2         64