6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        61         51         25         63         10         18         43          4         60         54
        52         55         44         37         39         49         48         13         38         14
        15         32         42         28         23         27         58         12         30         47
        33         22         31          2         17         64         36         50         46         59
         9          7         62         16         57         40          8         26         53         19
         5         20         29         24         45         21          1         56         41         34
        11          3         35          6