6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        26          6         12         36         27          9         11         39         56         21
        59          1         31         43         13         40          7         32         38         19
        42         34          3         14         45         22         16         53         30         63
        10         52         62         47         61         58         35         23         15         57
        33         64         50         25          4         29         60          2         51         46
        37         28         18         17         49         41         48          8         55         24
        44         20          5         54