6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        55          3         53         23         39         60          8         30         33         21
        13         11         42         25         43         47         46         58         10         54
        57         27         50         61          6         35         24         56         44          1
        19         45         41         48         28         15         38          4         26         32
        49         51         40          9         59         16         18         22         36         29
        37         62         20         14          5          7         34         64         17          2
        12         31         52         63