6       header
# Generated by DREAM.3D
grid    a 8    b 8    c 1
size    x 1024.000    y 1024.000    z 1024.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 40
         8         34          5         40         40         21          1          7         23         34
        16         40         40          6          6          7         28         29         29         17
        37         11         14         22         10         12         27         24         19         11
         9         10         32         26         27          3         33         25          9         31
        20         20         38          2         30         18         15         15         20         35
        35         30         30         15         15         39         36         36         35         35
        13         21          4          4