6       header
# Generated by DREAM.3D
grid    a 8    b 8    c 1
size    x 1024.000    y 1024.000    z 1024.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 31
         7         29         22         22         23         12          1          1          3         29
         8          8         14         11          1          1          5         15          8          8
        27         26         26          2         13         18          9          4          4         26
        26         26         28          9          9          9          4         26         26         26
        21          6          9         10         17         17         16         19         19         25
        25         10         10         16         16         19         20         30         31         31
        12         12         24         20