6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        17         47         51         48         25          5          3         18         32         15
        55         54         34         37         33         41          9         50         16         30
        31         23          2          7          8         60          1         62         13         59
        27         22          6         11         57         42         49         35         24         12
        44         28          4         53         64         20         19         29         46         40
        36         43         63         14         26         21         39         45         61         52
        58         56         10         38