6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        20         18          8         62         19         22         59         33         54         24
        39         12         25         48         51          9         60         14         46         16
        28         41         38         37         17         11          2         57         49         58
        47         27         26         45         55          5          6         53         50          3
        52         56          4          7         64         30         42         44         10         61
        15         43         21         29         34         63         35         31         32         36
        40          1         23         13