6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        55         14         26         48         10          7         36         22         64         61
        16         47         21         32         15         29         42         25         51         38
        35         44          3         49         53         20         27         39         13         52
        63         58         37         24         54          2         59          1         46         57
         6          5         41         56          8         43         17          4         30         40
        19         50         12         33         28         45         18         60         62          9
        34         31         11         23