6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         5         48         11          1         21         34         53         17         61         35
         7         13         54         10          6         25          2         12          9         47
        49          4         37         55         45         40         60         18         63         52
        64         33         15         19         56         22         24         20         57         62
        50          3         59         30         46          8         41         44         31         29
        51         38         36         26         43         16         42         39         32         14
        58         27         28         23