6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         6         15         33         35         53         37         50         17         51         27
        34         49         19         20         58         10          3         61         24          4
        36         45         21         47         55         18          7         13         28         42
        63         23         52         11         38          8         14          5         12         60
        59         30         16          1         32         46         29          2         54         56
        41         31         44         25         40         64         57         48          9         26
        43         22         39         62