6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        23         55         10          3         61         38          6         42         34         41
         4         35         50         21         44         22         27         60         48         28
        54         25         14         58         26         40         46         59         45         52
        57          5          1         36         11         31         32         37         15         24
        19          8          7         29          2         16         56         12         49         39
        30         51         43         33         17         62         18         47          9         13
        63         20         64         53