6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        56         48         57         51         61         17         30         16         50         47
        39         40          2         19         31         25          3         42          8         26
        45         46         21         44         11         22          6         53         34         58
         4         55         38         63         32         12         35         49         28          5
        54          1         27         33         41         18         20         36         10         60
        13         15         14         23         52         43         37         59          7         29
         9         62         64         24