6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        62         57         59          9          4         48         22         56         18         15
        20         37         53         39         42         29         26         35          3         61
         5         19         25         23          7         43         63         30         34         31
        38         28         32         46         40          1         64         44         41         33
        24         17         47         49         52         10         55         50          8         58
        60         36         14         54         13         27          2         21         45         51
        16          6         11         12