6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         4         22          9         16         15         10         13         43         46         40
        48         24         17         37          8         27         57         41         44         38
        25         30         63         47         64         54          2         29         32         28
        18         35         52          3         12         59         23         34         42         19
        51         49         61         58          5          7         53         60         50          1
        31         55         20         21          6         62         33         26         39         45
        56         11         36         14