6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        38          7         58         11         29          3         59          1         42         33
         5         32         15         46         13         16         54         50         60         25
        35         64         20         40         31         30         48         61          2         18
        17         44          8          9         19         14         51         37         28         56
        49         24         27         52         43         36         47         21         57         53
        62         12         26         63         23         10          4          6         39         45
        41         55         22         34