6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        40          1         48          2         25         44         14         57         42         31
        56         34         22         52         53          4         23         60         15         38
        29         37          5          7         55         62         24         30         17         47
        27         20         33         26         10         50         41         13         45         16
        39         54          9          3         32         35          6         36         19         51
        18         43         49         11         21         63         28         12         64         46
        59         61          8         58