6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        57         28         18         12         17         48         59         33         60         37
        19         42         40          1         39         24         30         34          9         36
        29         56         55          5         51         47         38         58         64         31
        53         27         45         21         63          7         22         13         49         50
        41         61         32         46         23          4         26         52         10         14
         2         25         11          8         43         15         16          6         44         54
        35         62          3         20