6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        41         27          9         25         50         51         17         42         13         33
        54         12         26         21         34          1         47         14          8         61
        44         46         23         56         39         30         18         52         60         32
        29         45         55         64         57         43          7         10         35         20
        37         28         49         58         31         24          6         19          3          4
        38         36          5         63         22         40         59          2         16         11
        53         15         48         62