6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        29         25         44         15         31         32         47         59          8         49
        35         40         52         30         21         63         50         45          1         41
        43         34          7          2         33         39         27          9         48         53
        58         56         23         19         64         12         14         18         54         17
        20         37         28         51         22         16         10          3         60         57
        13         36          5          4         55         62         24          6         42         46
        61         38         11         26