6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 1024.000    y 1024.000    z 1024.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 62
        25          5         57         13          7          1         41         14         15         45
        45         19         60         35         49         31         26         39         24         11
        23          6         18         37         17         62         38         21         59         16
        29         55         32         43         54         46         61         36         22          3
        42         56         48         30         27          9         51         52         53         40
         8         58         44         20         34         44         28         50         47         10
         2          4         12         33