6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        23         42         63         39         36         44          7         27         18         57
         3         28         30         12         35         43         61         13         51          5
        20         24         56         53         48         15         62         59         29         32
        58         40         17          4         10         14         26         50         38         34
        60         55         47          6         31         49         21         19         33         64
        25         37         45         41         16         11         46         52          9          2
        54          1         22          8