6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        58         27         35         31         25         62         43         47         45         13
        36         21         38         41         42          5         53         28         30         18
        26         37         33         55         48         22         16         52          9          3
        39         17         40          1         24         29         64         46         60         15
        10         50          2         54          4         61         14         63         49         11
         8         19         12         57         20         23          7         44         32         59
        56         34         51          6