6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        30         10         39          3          4         22         43         51          8         62
         9         44         18         53          6          7         55         13         38         15
        33         56         20         31         21         36         45         59         48         64
        49         24         25          1         29          2         41         17         26         46
        23         60         28         54         19         12         42         32         35         11
        63         27         50         16         58         61         57         34         37         40
         5         52         14         47