6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        25         63         24         19         34         27         41         28         32         53
        42         58         15         35         43         16         64         49         33         26
        39         59         46          9         55         40         31         17         11         62
        48         45         22         54          4         23         12         47         29         57
        30         51         61          5         10         36          8          7         38          3
        60         14         20         21         18          6         13         44         37          2
         1         52         56         50