6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        40         63         52         18         37         15         56         31         32         48
        33         17         41         47         36         16          3         49         44         29
        25         38         54         28         61         20          7         27         43         34
        62         13         55          6         53         64         60         59         22         58
        14          1         35          5          8         12         19         39          2         57
        11          4         50         26         30         46         23         51         24         21
        45         42         10          9