6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        20         32         64         17         60         25          9         62         18         21
        36         57         10          7         52         28         47         31         42         22
        13         41         34         23         12         15         58         14          4         44
        39         26         51         61         37         56         38         30         45         35
        24         19         11         49          6         29         16         54         48         46
        59          3          2         50          1         53         27         33         40         55
         8         63         43          5