6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        40          9         26         41         39         32         29         36         15         33
        37          5         16         21          8         47         23         57         14         62
        38          4         59         64         17         52         31         61         30         60
        10         25         42         34         28         63          2         12         45         50
        56          1         55         44         58         54         22         11          7         35
         6         51         43         24         48         27         46          3         53         20
        18         19         13         49