6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        24         40         58         26         50         34         55         54         35          4
        10         27          1         60          6          2         44         61         64         48
        43         29          9         32         16         14         28         51         30         46
        15         37         38         17         11         25         21         52          8         63
        31         23         59         53         36         12         18          3         56          5
        47         42         62         39         33         20         22          7         49         41
        19         13         57         45