6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         2         20         44         15         34         57         25         62          1         26
        12         38         60         24         47         39         29          9         56         36
        22         59         23         64         52          7         18         48         46         49
        55         27         14         31         35         40         42          3         41         54
         4         33         17         13         43          6         16         21         58         53
        30         50         32         45         51          8         37         61         28          5
        63         11         10         19