6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         5         63         25         31         29         36         42         45         50         52
        17         48         23          4         10         54         46         53         64         12
        28         24         22         38          8         20         49          3         55         37
        43         26         18         27         15         47         59         40         11         39
        32          6         30         61         33         19         44          2          7          9
        13         60         56          1         41         62         57         35         34         51
        16         58         21         14