6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        10         57         56         17         42         29          4         21         28          5
        35         19         61         22         16         23         34         12         31         25
        59          8         27          3         41         14         44         63         60         26
        39         15         64          2         20         13         54          9         45          1
        47         53         38         46         33         43          6         32         36         24
         7         49         50         52         18         55         51         11         40         48
        58         37         62         30