6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        41         31         39         44         64         59         18         32         17         48
        50         60         37         27         26         19         56         24         14         58
        28         10          2         54         36         30          9         46          7         13
        35         57          5         43         51         33         16         22         15         38
        21         23         42         34         29          3         52          8         53          4
        49         20          1          6         47         11         61         45         62         25
        55         12         63         40