6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         4         25          7          9         36         19         63         22         35         57
        58         28         15         31         62         10         18         16         29         53
        26         30         51          3         41         13         64         14         12         17
        11         48         20          8         37         54         27         61         40          2
        44         39          6         34         33         32         55         52         46         23
         5         42         60         38         24          1         45         21         49         56
        43         59         50         47