6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        58         27         31          5         35         29          2         34         40         61
         6          7         59         33          3         62         26         57         37         17
        16         54         50         52         23         28         45         20         48          8
        12         22          4         47         60         14         32         30         19         51
        53         10         18         56         38         64         21         55          1         15
        25         41         49         36         39          9         63         46         42         43
        11         13         24         44