6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        42         53         35         13          5         44         23         20         33         34
        27         40         63         61         28         38         11         10         26         62
        25         15         16         19          1         29         54         41         56         18
         6         17         59         22         50         49         64         46          7         24
         2         31          3         57         47         37         51         43         14         12
        52         30         32          4         48         45          9         21         39         60
        36          8         55         58