6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        49         60          6         29         62          2          7         10         36         51
        42         44         31         47         34         12         24         33         39         53
        63         22         19         16         58         20         46          1         27         45
         4         41          8         37         32         57         43         35         13         15
        11         21         14         55         54         23         30         28         64         59
        18         52         38         50         25         17         56         61         48         26
         5          3          9         40