6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        42         14         45         53         49          7         17         60         10          4
        46         39         12         35         30         21         56         38         58         55
        23          5          9         52         18         59         61         48          8         41
        27         15         64         43         62         16         44         54         26         63
        47         28         20         32         40          1          2         24          3         29
        13         51         33         36         31         11          6         37         57         34
        19         22         25         50