6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 10
         5          5         10         10          5          5         10         10          2          2
         1          1          2          2          1          7          8          5          9          7
         8          8          9          8          2          2          1          7          7          5
         1          7          6          6         10         10          8          6         10         10
         4          4          4         10          4          4          4          7          6          6
        10         10         10          6         10         10          4          4          4         10
         4          4          4          3