6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        48         51         25         46         12         14         60         22         19         50
         8          6         63         53         64         11         62          7         57          5
        52         20         47         37          9         33         17         28         44          4
        24         49         36         21         26         39         34         38         10          1
        31         58          2         45         23         16         42         29         35         18
        32         41         30         56         59         55         27         43         40         13
         3         54         15         61