6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        42          7         14         39         61          3         38         16         37         48
         2         28         26          6         30         64         55         56         34         58
        22         36         44         10         47         60         15         32         13          1
        31         52         51         63         29         17         45         46         19         35
        25         41         18          9         59         27         21          8         54         11
        20         57         40          4         33          5         53         43         23         50
        62         24         49         12