6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        49         38         63         43          7         28          8         15         42         29
        61         47         60         22         26         13          6         51         54         30
        37         18         58         57         48         31         41         12         36         44
        56          4         21         53         55         62         39          2         32         46
        50          5         14         20         25         23         33         27         52         59
        11         45         17         24         35         40         19         10          3          9
        16         64         34          1