6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        48          5         52         17         42         37         62         45         58         31
        39         44          2         20         21          3          7         22          4          1
        43         41         19         10          8         56         53         24         26         54
        33         34         36         32         25         50         55         40         59         38
        60         15         64         51         14         18         49         28         57         63
        29         46         47         16         11         13         35         27         23          6
        30          9         61         12