6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        52         22         47         30         42         48         18         25         55         46
        50         16         33         38         13         32         14         53         40         29
        12         56         62         19         36         11         15          7         64         23
        37         59          4         57          5         51         31         28         21         60
         1         26         58         27         35          2         34         20         39         43
        63          9         49         17          6          8         54         41         10         61
        45          3         24         44