6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        15         28         42         26         43         13         22         31         34          1
        45         54          5         57         52          9         59          6         29         14
        46         58         49          7         48         25         32         51         27         18
        44         33          3         20         21         10         63         50         36         35
        24         60         19          2         37         55         53         11         23         64
        38         41         39         17         30         40         12         61         62         56
         4         16          8         47