6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        43         46         61          6         11         34         21         25         39         36
        19         37          3         23         28         16         24         52         62         64
        59         15          1         17         60         56         14         10          2         40
        53         57          8         31          5         27         41         54          4         30
        45         29         58         12         18         35         32         20          7         42
        33         49         44         63         26         38         48         13         22         51
        50         47          9         55