6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        30         61         29          5         48         46         20         17         42         37
        18         26         64         44         57         62         16         10         27         25
        19         50         63         41          2         14         31         13         47         54
        49          3         32         52         59         28         56          7         12         34
        39         22         21         43          8         15         24         36          4         23
        35         60         53         33         40         51         38         45         58          6
         1         11         55          9