6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         3         40         32          6         60         35         21         27          4         34
        50          8          7         24         28         43         44         14         20         19
        63          2         55         26         12         49         36         56         15         37
        30         11         62         54         47         53         23         39          1         41
        45         33         31         29         61         64         13         17         59         38
         9         58         25         57         10          5         16         51         22         46
        48         18         42         52