6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        49          6         16         30         31         51         42         48         34         44
        45         29         54         15          5          1         59         14         53         46
        60         64          4         17         21         23         41         38         58         36
        43         55         52         13         32         37          2         57         33          3
        11          7         20         12         22          8         28         18         10         25
        35         61          9         39         62         47         56         50         63         40
        26         19         24         27