6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
         4         40          7         28          3         16          8         34          2         38
        36         27         59         12         62         60         24         54         46         29
        19         63         32         30         26          9         44         18         17         47
        21         15         45         35         64         55         14          5         49         50
        25         48         13         33         43         57         22         61         42         37
         6         39         23         31         51         10         58         56         52         53
         1         20         11         41