6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        26         48          9          5         30         46         18         21         61         36
         4         39         31         10         59         52         14         19          1         40
        57         62         63         54         49         50          8         29          2         11
        42         35         41         13         22         27         47         23         28         33
        60          7         17         16          6         53         34         25         37         43
        64         24         38         45         44         51         12         15          3         58
        55         32         56         20