6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        52         43         33          2         16         56         15         37         53         60
        20          3         26         55          1         30         34         28         51         54
        63         22         59         12         18          7         39         25         61         10
        62         41         47         11          4         13         17          8         50         42
        32         48         24         27         64         21         35         31         49         23
         6         38         46         40         58         19         36         45         57         29
         9         44          5         14