#!/bin/bash

cd *r55/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r56/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r57/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r58/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r59/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r60/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r61/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r62/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r63/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r64/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r65/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r66/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r67/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r68/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r69/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r70/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r71/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r72/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r73/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r74/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r75/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r76/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r77/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r78/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r79/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r80/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r81/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r82/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r83/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r84/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r85/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r86/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r87/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r88/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r89/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r90/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r91/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r92/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r93/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r94/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r95/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r96/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r97/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r98/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r99/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r100/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r101/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r102/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r103/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r104/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r105/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r106/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r107/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r108/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r109/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r110/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r111/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r112/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r113/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r114/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r115/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r116/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r117/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r118/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r119/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r120/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r121/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r122/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r123/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r124/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r125/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r126/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r127/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r128/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r129/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r130/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r131/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r132/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r133/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r134/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r135/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r136/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r137/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r138/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r139/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r140/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r141/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r142/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r143/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r144/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r145/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
cd *r146/; cp ../MonteCarloSS304L_Template/computeLossFunction.py .; python3 averageLossFunction.py; cd ..
