6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        56         62         10         37         30         17         34         19         64          2
        21         23         12         16         14         11          9         53         15          7
         5         47         61         20         39         43         32         55         51         24
        54         58         48          1         29          6         27          8         63         36
        59         45         57         44         22         26         33         50         52         42
        40         31         28         41          4         18          3         46         38         60
        49         13         35         25