6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 64
        50         63         14         57         21         41          8         53         26         38
        22         61         52         27         13         11         30         17          2          7
        20          5         10         15         31         64         19         54         46         18
        39         56         35         42         49         44         23         43          6         47
        60         24          4         34         25         37         48          1         36         58
        40         59         33         55         32          3          9         28         16         12
        62         29         45         51