6       header
# Generated by DREAM.3D
grid    a 4    b 4    c 4
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 63
        13         52         59         42         15         45         51          3         48         19
         4          5         33         19         58         56         25         60         47         23
        28         35         53         14          1         29          2         10         63         24
        26         37         38         44         40         11         36         46          8         17
        31         27         49         41         16         50         21          7         39         61
        57         54         20         43         34         22         12          6         30          9
        18         32         55         62