6       header
# Generated by DREAM.3D
grid    a 2    b 2    c 2
size    x 80.000    y 80.000    z 80.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 8
         4          3          6          7          2          1          5          8